/* AUTO-GENERATED by scripts/build_goldenprofile_wasm.mjs — DO NOT EDIT. */
export function resolve_json(request: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
