/* AUTO-GENERATED by scripts/build_autoconfig_wasm.mjs — DO NOT EDIT. */
export function autoconfig_classify_columns(cols_json: string): string;
export function autoconfig_decide_plan(input_json: string): string;
export function autoconfig_extrapolate_pair_count(input_json: string): string;
export function autoconfig_sparse_match_floor(input_json: string): string;
export function autoconfig_exact_matchkey_floor(input_json: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
