/* AUTO-GENERATED by scripts/build_cluster_wasm.mjs — DO NOT EDIT. */
export function mst_split_components(
  members: Int32Array,
  edges_a: Int32Array,
  edges_b: Int32Array,
  edges_w: Float64Array,
): string;
export function cluster_confidence(
  edges_a: Int32Array,
  edges_b: Int32Array,
  edges_w: Float64Array,
  size: number,
): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
