/* AUTO-GENERATED by scripts/build_documents_wasm.mjs — DO NOT EDIT. */
export function schema_validate(schema_json: string): string;
export function parse_message_text(resp_json: string): string;
export function extract_instruction(schema_json: string): string;
export function suggest_prompt(): string;
export function normalize_record(
  values_json: string,
  confidence_json: string,
  schema_json: string,
): string;
export function documents_template(doctype: string): string;
export function documents_template_list(): string;
export function documents_classify_prompt(): string;
export function documents_parse_classify(text: string): string;
export function documents_parse_structured(
  text: string,
  template_json: string,
): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
