/* AUTO-GENERATED by scripts/build_fingerprint_wasm.mjs — DO NOT EDIT. */
export function fingerprint_json(record_json: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
