/* AUTO-GENERATED by scripts/build_fs_wasm.mjs — DO NOT EDIT. */
export function score_block_pairs_fs(
  row_ids: BigInt64Array,
  block_sizes: Uint32Array,
  field_values_flat: string[],
  field_nulls: Uint8Array,
  n_fields: number,
  scorer_ids: Uint8Array,
  levels: Uint8Array,
  partial_thresholds: Float64Array,
  match_weights_flat: Float64Array,
  match_weights_lens: Uint32Array,
  calibrated: boolean,
  prior_w: number,
  min_weight: number,
  weight_range: number,
  threshold: number,
  level_thresholds_flat: Float64Array,
  level_thresholds_lens: Int32Array,
  ne_values_flat: string[],
  ne_nulls: Uint8Array,
  n_ne: number,
  ne_scorer_ids: Uint8Array,
  ne_thresholds: Float64Array,
  ne_weights: Float64Array,
): string;
export function train_em_from_counts(
  n_levels: Uint32Array,
  patterns_flat: Int32Array,
  counts: Float64Array,
  u_flat: Float64Array,
  conditioned: Uint8Array,
  max_iterations: number,
  convergence: number,
): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
