/* AUTO-GENERATED by scripts/build_goldenembed_wasm.mjs — DO NOT EDIT. */
export class Embedder {
  free(): void;
  constructor(
    weights: Float32Array,
    dim: number,
    bias: Float32Array | undefined,
    n_features: number,
    ngram_min: number,
    ngram_max: number,
    lowercase: boolean,
    boundary: string,
    seed: number,
  );
  readonly dim: number;
  embed(texts: string[]): Float32Array;
}
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
