/* AUTO-GENERATED by scripts/build_goldenhnsw_wasm.mjs — DO NOT EDIT. */
export class WasmHnswIndex {
  constructor(
    dim: number,
    m: number,
    ef_construction: number,
    ef_search: number,
    seed: number,
  );
  free(): void;
  add(vec: Float32Array): number;
  add_batch(flat: Float32Array, n: number): number;
  search(query: Float32Array, k: number): Float64Array;
  readonly dim: number;
  readonly len: number;
  readonly is_empty: boolean;
}
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
