/* AUTO-GENERATED by scripts/build_graph_wasm.mjs — DO NOT EDIT. */
export function connected_components(
  edges_a: Int32Array,
  edges_b: Int32Array,
  all_ids: Int32Array,
): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
