/* AUTO-GENERATED by scripts/build_key_integrity_wasm.mjs — DO NOT EDIT. */
export function certify_structural_json(input_json: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
