/* AUTO-GENERATED by scripts/build_perceptual_wasm.mjs — DO NOT EDIT. */
export function phash_image_hex(grid_json: string): string;
export function hamming_hex(a_hex: string, b_hex: string): number;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
