/* AUTO-GENERATED by scripts/build_suggest_wasm.mjs — DO NOT EDIT. */
export function suggest_review(input_json: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
