"""Byte-parity gate for the goldenflow card-identifier (Luhn) kernel.

Parametrizes over ``tests/parity/identifiers_corpus.jsonl`` (regenerated by
``scripts/gen_identifiers_corpus.py``) and asserts both the pure-Python
fallback path (``GOLDENFLOW_NATIVE=0``) and the native path agree with the
committed ``expected`` values byte-for-byte.
"""
from __future__ import annotations

import json
from pathlib import Path

import polars as pl
import pytest
from goldenflow.core._native_loader import native_available
from goldenflow.transforms.email import (
    email_extract_domain,
    email_lowercase,
    email_normalize,
    email_validate,
)
from goldenflow.transforms.identifiers import (
    aba_validate,
    cc_format,
    cc_mask,
    cc_validate,
    ean_validate,
    iban_format,
    iban_validate,
    imei_validate,
    isbn_normalize,
    isbn_validate,
    swift_format,
    swift_validate,
    vat_format,
    vat_validate,
)
from goldenflow.transforms.names import name_script, name_transliterate
from goldenflow.transforms.numeric import _currency_strip_series as currency_strip
from goldenflow.transforms.numeric import _percentage_normalize_series as percentage_normalize
from goldenflow.transforms.numeric import _to_integer_series as to_integer
from goldenflow.transforms.numeric import (
    comma_decimal,
    scientific_to_decimal,
)
from goldenflow.transforms.url import url_extract_domain, url_normalize

_CORPUS_PATH = Path(__file__).parent.parent / "parity" / "identifiers_corpus.jsonl"

# Transforms in this family output floats/ints -- parity is compared by
# VALUE (numeric), not string repr / exact object equality, since a
# byte-identical value could arrive as `2.0` vs `2` after a JSON round-trip.
_NUMERIC_TRANSFORMS = frozenset(
    {
        "currency_strip",
        "percentage_normalize",
        "to_integer",
        "comma_decimal",
        "scientific_to_decimal",
    }
)


def _assert_value_parity(transform: str, actual: object, expected: object) -> None:
    """Numeric-aware equality for the numeric family; exact equality for
    everything else. Both `None` -> pass. Prefer EXACT float equality (the
    same IEEE754 parse ops on both sides should produce bit-identical
    results) over a fuzzy epsilon -- only fall back to a tiny epsilon if
    exact equality genuinely doesn't hold, which would indicate a real
    cross-surface drift worth investigating, not paper over it."""
    if transform not in _NUMERIC_TRANSFORMS:
        assert actual == expected
        return
    if actual is None or expected is None:
        assert actual == expected
        return
    if actual == expected:
        return
    # Both are numeric at this point (float or int) -- fall back to a tiny
    # epsilon ONLY to absorb a genuine last-bit float discrepancy, never to
    # mask a real logic divergence.
    assert abs(float(actual) - float(expected)) < 1e-9, (
        f"{transform}: {actual!r} != {expected!r} (beyond float epsilon)"
    )

_TRANSFORMS = {
    "cc_validate": cc_validate,
    "cc_format": cc_format,
    "cc_mask": cc_mask,
    "iban_validate": iban_validate,
    "iban_format": iban_format,
    "isbn_validate": isbn_validate,
    "isbn_normalize": isbn_normalize,
    "ean_validate": ean_validate,
    "swift_validate": swift_validate,
    "swift_format": swift_format,
    "vat_validate": vat_validate,
    "vat_format": vat_format,
    "aba_validate": aba_validate,
    "imei_validate": imei_validate,
    "name_transliterate": name_transliterate,
    "name_script": name_script,
    "email_lowercase": email_lowercase,
    "email_normalize": email_normalize,
    "email_extract_domain": email_extract_domain,
    "email_validate": email_validate,
    "url_normalize": url_normalize,
    "url_extract_domain": url_extract_domain,
    "currency_strip": currency_strip,
    "percentage_normalize": percentage_normalize,
    "to_integer": to_integer,
    "comma_decimal": comma_decimal,
    "scientific_to_decimal": scientific_to_decimal,
}

# Floor native symbol per transform's component -- used to skip a row when the
# installed/built goldenflow-native predates that transform's kernel (wheel
# skew), mirroring _native_loader._COMPONENT_SYMBOLS.
_NATIVE_FLOOR_SYMBOL = {
    "cc_validate": "cc_validate_arrow",
    "cc_format": "cc_validate_arrow",
    "cc_mask": "cc_validate_arrow",
    "iban_validate": "iban_validate_arrow",
    "iban_format": "iban_validate_arrow",
    "isbn_validate": "isbn_validate_arrow",
    "isbn_normalize": "isbn_validate_arrow",
    "ean_validate": "ean_validate_arrow",
    "swift_validate": "swift_validate_arrow",
    "swift_format": "swift_validate_arrow",
    "vat_validate": "vat_validate_arrow",
    "vat_format": "vat_validate_arrow",
    "aba_validate": "aba_validate_arrow",
    "imei_validate": "imei_validate_arrow",
    "name_transliterate": "name_transliterate_arrow",
    "name_script": "name_script_arrow",
    # email: all 4 transforms are wired via the single "email" component
    # (floor symbol email_validate_arrow), region-free/locale-free.
    "email_lowercase": "email_validate_arrow",
    "email_normalize": "email_validate_arrow",
    "email_extract_domain": "email_validate_arrow",
    "email_validate": "email_validate_arrow",
    # url: both transforms are wired via the single "url" component (floor
    # symbol url_normalize_arrow), region-free/locale-free.
    "url_normalize": "url_normalize_arrow",
    "url_extract_domain": "url_normalize_arrow",
    # numeric: all 5 string-parser transforms are wired via the single
    # "numeric" component (floor symbol currency_strip_arrow), region-free/
    # locale-free.
    "currency_strip": "currency_strip_arrow",
    "percentage_normalize": "currency_strip_arrow",
    "to_integer": "currency_strip_arrow",
    "comma_decimal": "currency_strip_arrow",
    "scientific_to_decimal": "currency_strip_arrow",
}


def _load_corpus() -> list[dict[str, object]]:
    rows = []
    with _CORPUS_PATH.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


_CORPUS = _load_corpus()
_IDS = [f"{r['transform']}[{r['input']!r}]" for r in _CORPUS]


@pytest.mark.parametrize("row", _CORPUS, ids=_IDS)
def test_identifiers_fallback_parity(row, monkeypatch):
    """Pure-Python fallback path (GOLDENFLOW_NATIVE=0) matches the committed
    corpus exactly."""
    monkeypatch.setenv("GOLDENFLOW_NATIVE", "0")
    transform = _TRANSFORMS[row["transform"]]
    result = transform(pl.Series("v", [row["input"]]))
    _assert_value_parity(row["transform"], result.to_list()[0], row["expected"])


@pytest.mark.parametrize("row", _CORPUS, ids=_IDS)
def test_identifiers_native_parity(row, monkeypatch):
    """Native path matches the committed corpus exactly (skips if the native
    module isn't built/importable, or the transform's kernel symbol isn't in
    the wheel)."""
    if not native_available():
        pytest.skip("goldenflow-native not built/importable")
    from goldenflow.core._native_loader import native_module

    floor_symbol = _NATIVE_FLOOR_SYMBOL[row["transform"]]
    if not hasattr(native_module(), floor_symbol):
        pytest.skip(
            f"installed goldenflow-native predates the {row['transform']} kernel "
            "(wheel skew)"
        )
    monkeypatch.setenv("GOLDENFLOW_NATIVE", "auto")
    transform = _TRANSFORMS[row["transform"]]
    result = transform(pl.Series("v", [row["input"]]))
    _assert_value_parity(row["transform"], result.to_list()[0], row["expected"])
