"""Byte-parity gate for the goldenflow card-identifier (Luhn) kernel.

Parametrizes over ``tests/parity/identifiers_corpus.jsonl`` (regenerated by
``scripts/gen_identifiers_corpus.py``) and asserts both the pure-Python
fallback path (``GOLDENFLOW_NATIVE=0``) and the native path agree with the
committed ``expected`` values byte-for-byte.
"""
from __future__ import annotations

import json
from pathlib import Path

import polars as pl
import pytest
from goldenflow.core._native_loader import native_available
from goldenflow.transforms.identifiers import cc_format, cc_mask, cc_validate

_CORPUS_PATH = Path(__file__).parent.parent / "parity" / "identifiers_corpus.jsonl"

_TRANSFORMS = {
    "cc_validate": cc_validate,
    "cc_format": cc_format,
    "cc_mask": cc_mask,
}


def _load_corpus() -> list[dict[str, object]]:
    rows = []
    with _CORPUS_PATH.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


_CORPUS = _load_corpus()
_IDS = [f"{r['transform']}[{r['input']!r}]" for r in _CORPUS]


@pytest.mark.parametrize("row", _CORPUS, ids=_IDS)
def test_identifiers_fallback_parity(row, monkeypatch):
    """Pure-Python fallback path (GOLDENFLOW_NATIVE=0) matches the committed
    corpus exactly."""
    monkeypatch.setenv("GOLDENFLOW_NATIVE", "0")
    transform = _TRANSFORMS[row["transform"]]
    result = transform(pl.Series("v", [row["input"]]))
    assert result.to_list()[0] == row["expected"]


@pytest.mark.parametrize("row", _CORPUS, ids=_IDS)
def test_identifiers_native_parity(row, monkeypatch):
    """Native path matches the committed corpus exactly (skips if the native
    module isn't built/importable, or the ``cc`` symbols aren't in the wheel)."""
    if not native_available():
        pytest.skip("goldenflow-native not built/importable")
    from goldenflow.core._native_loader import native_module

    if not hasattr(native_module(), "cc_validate_arrow"):
        pytest.skip("installed goldenflow-native predates the cc kernel (wheel skew)")
    monkeypatch.setenv("GOLDENFLOW_NATIVE", "auto")
    transform = _TRANSFORMS[row["transform"]]
    result = transform(pl.Series("v", [row["input"]]))
    assert result.to_list()[0] == row["expected"]
