"""Byte-parity gate for the goldenflow card-identifier (Luhn) kernel.

Parametrizes over ``tests/parity/identifiers_corpus.jsonl`` (regenerated by
``scripts/gen_identifiers_corpus.py``) and asserts both the pure-Python
fallback path (``GOLDENFLOW_NATIVE=0``) and the native path agree with the
committed ``expected`` values byte-for-byte.
"""
from __future__ import annotations

import json
from pathlib import Path

import polars as pl
import pytest
from goldenflow.core._native_loader import native_available
from goldenflow.transforms.address import (
    _address_expand_series as address_expand,
)
from goldenflow.transforms.address import (
    _address_standardize_series as address_standardize,
)
from goldenflow.transforms.address import (
    _state_abbreviate_series as state_abbreviate,
)
from goldenflow.transforms.address import (
    _state_expand_series as state_expand,
)
from goldenflow.transforms.address import (
    _zip_normalize_series as zip_normalize,
)
from goldenflow.transforms.address import (
    country_standardize,
    unit_normalize,
)
from goldenflow.transforms.categorical import (
    _category_normalize_key_series,
    boolean_normalize,
    gender_standardize,
    null_standardize,
)
from goldenflow.transforms.email import (
    email_extract_domain,
    email_lowercase,
    email_normalize,
    email_validate,
)
from goldenflow.transforms.identifiers import (
    aba_validate,
    cc_format,
    cc_mask,
    cc_validate,
    ean_validate,
    iban_format,
    iban_validate,
    imei_validate,
    isbn_normalize,
    isbn_validate,
    swift_format,
    swift_validate,
    vat_format,
    vat_validate,
)
from goldenflow.transforms.names import (
    _has_initial_series as has_initial,
)
from goldenflow.transforms.names import (
    _strip_suffixes_series as strip_suffixes,
)
from goldenflow.transforms.names import (
    _strip_titles_series as strip_titles,
)
from goldenflow.transforms.names import (
    name_proper,
    name_script,
    name_transliterate,
    nickname_standardize,
)
from goldenflow.transforms.numeric import _currency_strip_series as currency_strip
from goldenflow.transforms.numeric import _percentage_normalize_series as percentage_normalize
from goldenflow.transforms.numeric import _to_integer_series as to_integer
from goldenflow.transforms.numeric import (
    comma_decimal,
    scientific_to_decimal,
)
from goldenflow.transforms.phonetic import soundex
from goldenflow.transforms.text import (
    _collapse_whitespace_series as collapse_whitespace,
)
from goldenflow.transforms.text import (
    _extract_numbers_series as extract_numbers,
)
from goldenflow.transforms.text import (
    _lowercase_series as lowercase,
)
from goldenflow.transforms.text import (
    _normalize_line_endings_series as normalize_line_endings,
)
from goldenflow.transforms.text import (
    _normalize_quotes_series as normalize_quotes,
)
from goldenflow.transforms.text import (
    _remove_digits_series as remove_digits,
)
from goldenflow.transforms.text import (
    _remove_emojis_series as remove_emojis,
)
from goldenflow.transforms.text import (
    _remove_html_tags_series as remove_html_tags,
)
from goldenflow.transforms.text import (
    _remove_punctuation_series as remove_punctuation,
)
from goldenflow.transforms.text import (
    _remove_urls_series as remove_urls,
)
from goldenflow.transforms.text import (
    _strip_series as strip,
)
from goldenflow.transforms.text import (
    _title_case_series as title_case,
)
from goldenflow.transforms.text import (
    _uppercase_series as uppercase,
)
from goldenflow.transforms.text import (
    fix_mojibake,
    normalize_unicode,
)
from goldenflow.transforms.url import url_extract_domain, url_normalize

_CORPUS_PATH = Path(__file__).parent.parent / "parity" / "identifiers_corpus.jsonl"

# Transforms in this family output floats/ints -- parity is compared by
# VALUE (numeric), not string repr / exact object equality, since a
# byte-identical value could arrive as `2.0` vs `2` after a JSON round-trip.
_NUMERIC_TRANSFORMS = frozenset(
    {
        "currency_strip",
        "percentage_normalize",
        "to_integer",
        "comma_decimal",
        "scientific_to_decimal",
    }
)


def _assert_value_parity(transform: str, actual: object, expected: object) -> None:
    """Numeric-aware equality for the numeric family; exact equality for
    everything else. Both `None` -> pass. Prefer EXACT float equality (the
    same IEEE754 parse ops on both sides should produce bit-identical
    results) over a fuzzy epsilon -- only fall back to a tiny epsilon if
    exact equality genuinely doesn't hold, which would indicate a real
    cross-surface drift worth investigating, not paper over it."""
    if transform not in _NUMERIC_TRANSFORMS:
        assert actual == expected
        return
    if actual is None or expected is None:
        assert actual == expected
        return
    if actual == expected:
        return
    # Both are numeric at this point (float or int) -- fall back to a tiny
    # epsilon ONLY to absorb a genuine last-bit float discrepancy, never to
    # mask a real logic divergence.
    assert abs(float(actual) - float(expected)) < 1e-9, (
        f"{transform}: {actual!r} != {expected!r} (beyond float epsilon)"
    )

_TRANSFORMS = {
    "cc_validate": cc_validate,
    "cc_format": cc_format,
    "cc_mask": cc_mask,
    "iban_validate": iban_validate,
    "iban_format": iban_format,
    "isbn_validate": isbn_validate,
    "isbn_normalize": isbn_normalize,
    "ean_validate": ean_validate,
    "swift_validate": swift_validate,
    "swift_format": swift_format,
    "vat_validate": vat_validate,
    "vat_format": vat_format,
    "aba_validate": aba_validate,
    "imei_validate": imei_validate,
    "soundex": soundex,
    "name_transliterate": name_transliterate,
    "name_script": name_script,
    "strip_titles": strip_titles,
    "strip_suffixes": strip_suffixes,
    "name_proper": name_proper,
    "nickname_standardize": nickname_standardize,
    "has_initial": has_initial,
    "email_lowercase": email_lowercase,
    "email_normalize": email_normalize,
    "email_extract_domain": email_extract_domain,
    "email_validate": email_validate,
    "url_normalize": url_normalize,
    "url_extract_domain": url_extract_domain,
    "address_standardize": address_standardize,
    "address_expand": address_expand,
    "state_abbreviate": state_abbreviate,
    "state_expand": state_expand,
    "zip_normalize": zip_normalize,
    "country_standardize": country_standardize,
    "unit_normalize": unit_normalize,
    "strip": strip,
    "collapse_whitespace": collapse_whitespace,
    "normalize_quotes": normalize_quotes,
    "normalize_line_endings": normalize_line_endings,
    "remove_html_tags": remove_html_tags,
    "remove_urls": remove_urls,
    "remove_digits": remove_digits,
    "remove_punctuation": remove_punctuation,
    "remove_emojis": remove_emojis,
    "extract_numbers": extract_numbers,
    "lowercase": lowercase,
    "uppercase": uppercase,
    "title_case": title_case,
    "normalize_unicode": normalize_unicode,
    "fix_mojibake": fix_mojibake,
    "currency_strip": currency_strip,
    "percentage_normalize": percentage_normalize,
    "to_integer": to_integer,
    "comma_decimal": comma_decimal,
    "scientific_to_decimal": scientific_to_decimal,
    "boolean_normalize": boolean_normalize,
    "gender_standardize": gender_standardize,
    "null_standardize": null_standardize,
    "category_normalize_key": _category_normalize_key_series,
}

# Floor native symbol per transform's component -- used to skip a row when the
# installed/built goldenflow-native predates that transform's kernel (wheel
# skew), mirroring _native_loader._COMPONENT_SYMBOLS.
_NATIVE_FLOOR_SYMBOL = {
    "cc_validate": "cc_validate_arrow",
    "cc_format": "cc_validate_arrow",
    "cc_mask": "cc_validate_arrow",
    "iban_validate": "iban_validate_arrow",
    "iban_format": "iban_validate_arrow",
    "isbn_validate": "isbn_validate_arrow",
    "isbn_normalize": "isbn_validate_arrow",
    "ean_validate": "ean_validate_arrow",
    "swift_validate": "swift_validate_arrow",
    "swift_format": "swift_validate_arrow",
    "vat_validate": "vat_validate_arrow",
    "vat_format": "vat_validate_arrow",
    "aba_validate": "aba_validate_arrow",
    "imei_validate": "imei_validate_arrow",
    "soundex": "soundex_arrow",
    "name_transliterate": "name_transliterate_arrow",
    "name_script": "name_script_arrow",
    # names_ext: strip_titles/strip_suffixes/name_proper/nickname_standardize/
    # has_initial -- floor symbol strip_titles_arrow.
    "strip_titles": "strip_titles_arrow",
    "strip_suffixes": "strip_titles_arrow",
    "name_proper": "strip_titles_arrow",
    "nickname_standardize": "strip_titles_arrow",
    "has_initial": "strip_titles_arrow",
    # email: all 4 transforms are wired via the single "email" component
    # (floor symbol email_validate_arrow), region-free/locale-free.
    "email_lowercase": "email_validate_arrow",
    "email_normalize": "email_validate_arrow",
    "email_extract_domain": "email_validate_arrow",
    "email_validate": "email_validate_arrow",
    # url: both transforms are wired via the single "url" component (floor
    # symbol url_normalize_arrow), region-free/locale-free.
    "url_normalize": "url_normalize_arrow",
    "url_extract_domain": "url_normalize_arrow",
    # address: all 7 scalar transforms wired via the single "address" component
    # (floor symbol address_standardize_arrow), US-scoped/locale-free.
    "address_standardize": "address_standardize_arrow",
    "address_expand": "address_standardize_arrow",
    "state_abbreviate": "address_standardize_arrow",
    "state_expand": "address_standardize_arrow",
    "zip_normalize": "address_standardize_arrow",
    "country_standardize": "address_standardize_arrow",
    "unit_normalize": "address_standardize_arrow",
    # text: the mechanical text family wired via the single "text" component
    # (floor symbol strip_arrow), locale-free (ASCII-bounded / explicit ranges).
    "strip": "strip_arrow",
    "collapse_whitespace": "strip_arrow",
    "normalize_quotes": "strip_arrow",
    "normalize_line_endings": "strip_arrow",
    "remove_html_tags": "strip_arrow",
    "remove_urls": "strip_arrow",
    "remove_digits": "strip_arrow",
    "remove_punctuation": "strip_arrow",
    "remove_emojis": "strip_arrow",
    "extract_numbers": "strip_arrow",
    "lowercase": "strip_arrow",
    "uppercase": "strip_arrow",
    "title_case": "strip_arrow",
    "normalize_unicode": "strip_arrow",
    "fix_mojibake": "strip_arrow",
    # numeric: all 5 string-parser transforms are wired via the single
    # "numeric" component (floor symbol currency_strip_arrow), region-free/
    # locale-free.
    "currency_strip": "currency_strip_arrow",
    "percentage_normalize": "currency_strip_arrow",
    "to_integer": "currency_strip_arrow",
    "comma_decimal": "currency_strip_arrow",
    "scientific_to_decimal": "currency_strip_arrow",
    # categorical: boolean_normalize/gender_standardize/null_standardize +
    # category_normalize_key are all wired via the single "categorical"
    # component (floor symbol boolean_normalize_arrow), region-free/
    # locale-free.
    "boolean_normalize": "boolean_normalize_arrow",
    "gender_standardize": "boolean_normalize_arrow",
    "null_standardize": "boolean_normalize_arrow",
    "category_normalize_key": "boolean_normalize_arrow",
}


def _load_corpus() -> list[dict[str, object]]:
    rows = []
    with _CORPUS_PATH.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


_CORPUS = _load_corpus()
_IDS = [f"{r['transform']}[{r['input']!r}]" for r in _CORPUS]


@pytest.mark.parametrize("row", _CORPUS, ids=_IDS)
def test_identifiers_fallback_parity(row, monkeypatch):
    """Pure-Python fallback path (GOLDENFLOW_NATIVE=0) matches the committed
    corpus exactly."""
    monkeypatch.setenv("GOLDENFLOW_NATIVE", "0")
    transform = _TRANSFORMS[row["transform"]]
    result = transform(pl.Series("v", [row["input"]]))
    _assert_value_parity(row["transform"], result.to_list()[0], row["expected"])


@pytest.mark.parametrize("row", _CORPUS, ids=_IDS)
def test_identifiers_native_parity(row, monkeypatch):
    """Native path matches the committed corpus exactly (skips if the native
    module isn't built/importable, or the transform's kernel symbol isn't in
    the wheel)."""
    if not native_available():
        pytest.skip("goldenflow-native not built/importable")
    from goldenflow.core._native_loader import native_module

    floor_symbol = _NATIVE_FLOOR_SYMBOL[row["transform"]]
    if not hasattr(native_module(), floor_symbol):
        pytest.skip(
            f"installed goldenflow-native predates the {row['transform']} kernel "
            "(wheel skew)"
        )
    monkeypatch.setenv("GOLDENFLOW_NATIVE", "auto")
    transform = _TRANSFORMS[row["transform"]]
    result = transform(pl.Series("v", [row["input"]]))
    _assert_value_parity(row["transform"], result.to_list()[0], row["expected"])
