//! Byte-parity: `email::email_normalize` / `url::url_normalize` /
//! `address::address_standardize` reproduce the GoldenFlow polars transforms
//! `email_normalize` / `url_normalize` / `address_standardize` exactly.
//!
//! The fixture `golden/email_url_address_golden.json` was generated by running
//! the ACTUAL goldenflow transforms in their PURE (polars reference) mode over a
//! corpus of tricky inputs (empty, whitespace, +tags, gmail dots, missing
//! scheme, tracking params, uppercase, address abbreviations). A green run here
//! proves the pyo3-free Rust kernels are byte-identical to the polars reference,
//! which is the precondition for the Postgres `goldenflow_*` externs to run
//! native-direct over these kernels (the P9 de-bridge) instead of the embedded
//! CPython bridge -- matching the SQL surface's prior output.
//!
//! `url_normalize` returns `Option<String>`; the reference maps unparseable /
//! empty input to a NULL cell (JSON `null`), which the Postgres extern turns back
//! into input-passthrough (matching the bridge's `unwrap_or(value)` contract).

use goldenflow_core::address::address_standardize;
use goldenflow_core::email::email_normalize;
use goldenflow_core::url::url_normalize;
use serde_json::Value;

#[test]
fn reproduces_polars_email_url_address_transforms() {
    let raw = include_str!("../golden/email_url_address_golden.json");
    let cases: Vec<Value> = serde_json::from_str(raw).expect("golden fixture parses");
    assert!(cases.len() >= 15, "expected a broad corpus");
    for case in &cases {
        let input = case["input"].as_str().unwrap();

        // email + address: the reference is a plain string on every non-null input.
        let want_email = case["email_normalize"].as_str().unwrap();
        assert_eq!(
            email_normalize(input),
            want_email,
            "email_normalize mismatch for input {input:?}"
        );

        let want_addr = case["address_standardize"].as_str().unwrap();
        assert_eq!(
            address_standardize(input),
            want_addr,
            "address_standardize mismatch for input {input:?}"
        );

        // url: the reference is either a string or null (empty/whitespace -> null).
        match &case["url_normalize"] {
            Value::Null => assert_eq!(
                url_normalize(input),
                None,
                "url_normalize should be None for input {input:?}"
            ),
            Value::String(want_url) => assert_eq!(
                url_normalize(input).as_deref(),
                Some(want_url.as_str()),
                "url_normalize mismatch for input {input:?}"
            ),
            other => panic!("unexpected url_normalize fixture value: {other:?}"),
        }
    }
}
