//! Byte-parity: `text::strip` / `text::collapse_whitespace` reproduce the
//! GoldenFlow polars transforms `strip` / `collapse_whitespace` exactly. The
//! fixture `golden/text_golden.json` was generated by running the ACTUAL
//! goldenflow transforms (polars) over a Unicode-whitespace corpus — see
//! scripts note in the PR. A green run here proves the pyo3-free Rust kernel is
//! byte-identical to the polars reference (so the Postgres native de-bridge
//! matches DuckDB / Python), across the tricky Unicode boundary (NBSP, VT, NEL,
//! line-sep, U+205F, U+3000, U+2009, U+1680 are whitespace; ZWSP U+200B is not).

use goldenflow_core::text::{collapse_whitespace, strip};
use serde_json::Value;

#[test]
fn reproduces_polars_text_transforms() {
    let raw = include_str!("../golden/text_golden.json");
    let cases: Vec<Value> = serde_json::from_str(raw).expect("golden fixture parses");
    assert!(cases.len() >= 20, "expected broad Unicode coverage");
    for case in &cases {
        let input = case["input"].as_str().unwrap();
        let want_strip = case["strip"].as_str().unwrap();
        let want_collapse = case["collapse_whitespace"].as_str().unwrap();
        assert_eq!(
            strip(input),
            want_strip,
            "strip mismatch for input {input:?}"
        );
        assert_eq!(
            collapse_whitespace(input),
            want_collapse,
            "collapse_whitespace mismatch for input {input:?}"
        );
    }
}
