/* AUTO-GENERATED by scripts/build_goldengraph_wasm.mjs — DO NOT EDIT. */
export function build_graph(mentions_json: string, edges_json: string, resolution_json: string): string;
export function neighborhood(graph_json: string, seeds_json: string, hops: number): string;
export function seeds_by_name(graph_json: string, name: string): string;
export function communities(graph_json: string): string;
export function store_append(snapshot_json: string, batch_json: string): string;
export function store_as_of(snapshot_json: string, valid_t: bigint, tx_t: bigint): string;
export function store_history(snapshot_json: string, id: bigint): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
