/* AUTO-GENERATED by scripts/build_goldengraph_wasm.mjs — DO NOT EDIT. */
export function build_graph(mentions_json: string, edges_json: string, resolution_json: string): string;
export function neighborhood(graph_json: string, seeds_json: string, hops: number): string;
export function seeds_by_name(graph_json: string, name: string): string;
export function communities(graph_json: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
