#!/usr/bin/env bash
# Build goldengraph-wasm for wasm32 and emit the artifact + glue into the (new)
# TS goldengraph package. Mirrors score-wasm/build_wasm.sh. Run from anywhere.
# Requires: rustup wasm32 target + wasm-bindgen-cli (installed below).
set -euo pipefail
export CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-$HOME/.rustup}"
export PATH="$CARGO_HOME/bin:$PATH"

CRATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$CRATE_DIR/../../../typescript/goldengraph/src/core/wasm/artifacts"
mkdir -p "$OUT_DIR"

rustup target add wasm32-unknown-unknown
cargo build --manifest-path "$CRATE_DIR/Cargo.toml" --target wasm32-unknown-unknown --release

# Install wasm-bindgen-cli at the EXACT version pinned in Cargo.lock — a CLI/crate
# version skew produces broken JS glue that fails at runtime, not build time (a
# known wasm-bindgen footgun). Read the pinned version straight from the committed
# lockfile. The anchored grep matches the exact `wasm-bindgen` package only.
WB_VER="$(grep -A1 '^name = "wasm-bindgen"$' "$CRATE_DIR/Cargo.lock" | grep '^version = ' | head -1 | sed -E 's/version = "([^"]+)"/\1/')"
if [ -z "$WB_VER" ]; then echo "could not resolve wasm-bindgen version from Cargo.lock" >&2; exit 1; fi
echo "Using wasm-bindgen $WB_VER"
if ! wasm-bindgen --version 2>/dev/null | grep -q "$WB_VER"; then
  cargo install wasm-bindgen-cli --version "=$WB_VER" --locked
fi
command -v wasm-bindgen >/dev/null 2>&1 || { echo "wasm-bindgen not on PATH after install; aborting" >&2; exit 1; }

wasm-bindgen \
  "$CRATE_DIR/target/wasm32-unknown-unknown/release/goldengraph_wasm.wasm" \
  --target web --out-dir "$OUT_DIR" --out-name goldengraph_wasm

# Universal (edge-safe) loader artifact: the .wasm base64-inlined into a tiny JS
# module so the bytes resolve with NO fetch / fs / import.meta.url (loads across
# Node / browser / Workers / Deno + every bundler). Gitignored like the .wasm.
# (`base64 -w0` is GNU-only; pipe through `tr -d '\n'` for portability.)
B64="$(base64 "$OUT_DIR/goldengraph_wasm_bg.wasm" | tr -d '\n')"
cat > "$OUT_DIR/goldengraph_wasm_base64.js" <<EOF
// GENERATED by goldengraph-wasm/build_wasm.sh — do not edit. The .wasm bytes
// inlined as standard base64 for the universal (edge-safe) loader. Gitignored.
export const WASM_BASE64 = "$B64";
EOF

echo "Artifact written to $OUT_DIR (goldengraph_wasm_bg.wasm + goldengraph_wasm.js + goldengraph_wasm_base64.js)"
