"""Anomaly diagnostics + prefilled GitHub issue prompts for the Golden Suite.

This module turns an *anomaly* into a better error message carrying a prefilled
"file an issue" URL. It **sends nothing anywhere** -- no network, no telemetry --
so unlike opt-in analytics it is safe to run by default.

The governing discipline is anti-spam: fire ONLY on anomalies, never on expected
fallbacks or user-input errors. "Native not installed -> pure Python" is normal
and must not nag; "native installed but the kernel symbol is missing" (wheel
skew) is an anomaly worth a prompt. A `ControllerNotConfidentError`, a bad
config, or a `FileNotFoundError` is the user's situation, not a suite bug -- those
get recovery guidance elsewhere, never an issue prompt.

Kill switch: ``GOLDEN_DIAGNOSTICS=0`` (or ``false``/``off``/``no``/``disabled``)
silences every prompt.
"""
from __future__ import annotations

import logging
import os
import platform
import traceback
import urllib.parse
from collections.abc import Iterable, Mapping, Sequence
from typing import Any

_DEFAULT_REPO = "benseverndev-oss/goldenmatch"
_KILL_ENV = "GOLDEN_DIAGNOSTICS"
_FALSEY = {"0", "false", "off", "no", "disabled"}
# Keep the issue URL comfortably under browser/query limits (~8k typical).
_MAX_URL_BODY = 6000
_MAX_TITLE = 250

# Process-level warn-once guard so a hot loop / distributed run prompts at most
# once per (category, key) -- the same posture as the native slow-path warning.
_REPORTED: set[str] = set()


def prompts_enabled() -> bool:
    """Whether issue prompts are enabled (default True; ``GOLDEN_DIAGNOSTICS=0`` off)."""
    return os.environ.get(_KILL_ENV, "").strip().lower() not in _FALSEY


def reset() -> None:
    """Clear the per-process warn-once guard (test isolation / per-run capture)."""
    _REPORTED.clear()


def _scrub(value: Any) -> str:
    """PII-safe scalar: drop path-like or long values (mirrors the analytics
    allow-list discipline -- never leak a filesystem path or a big blob into a
    URL that the user is about to open in a browser)."""
    s = str(value)
    if len(s) > 200 or "/" in s or "\\" in s:
        return "<omitted>"
    return s


def environment_report(
    package: str,
    version: str | None = None,
    extra: Mapping[str, Any] | None = None,
) -> dict[str, str]:
    """A small, PII-safe environment dict for an issue body.

    ``extra`` values are scrubbed (path-like / >200-char values become
    ``<omitted>``) so a caller can pass e.g. native availability without risking
    a leaked path.
    """
    env: dict[str, str] = {
        "package": str(package),
        "version": str(version or "unknown"),
        "python": platform.python_version(),
        "platform": platform.system(),
        "arch": platform.machine(),
    }
    if extra:
        for k, v in extra.items():
            env[str(k)] = _scrub(v)
    return env


def issue_url(
    title: str,
    body: str,
    *,
    repo: str = _DEFAULT_REPO,
    labels: Sequence[str] | None = None,
) -> str:
    """A prefilled GitHub 'new issue' URL. Title/body are length-capped so the
    URL stays within browser limits; unknown labels are ignored by GitHub."""
    params: dict[str, str] = {"title": title[:_MAX_TITLE], "body": body[:_MAX_URL_BODY]}
    if labels:
        params["labels"] = ",".join(labels)
    return f"https://github.com/{repo}/issues/new?" + urllib.parse.urlencode(params)


def _issue_body(
    category: str,
    summary: str,
    detail: str,
    env: Mapping[str, str],
    exc: BaseException | None,
) -> str:
    lines = [f"**What happened:** {summary}", ""]
    if detail:
        lines += [detail, ""]
    if exc is not None:
        tb = "".join(traceback.format_exception_only(type(exc), exc)).strip()
        lines += ["**Error:**", "```", tb, "```", ""]
    lines += ["**Environment:**", "```"]
    lines += [f"{k}: {v}" for k, v in env.items()]
    lines += [
        "```",
        "",
        f"_Category: `{category}`. Auto-generated by golden-diagnostics; "
        "please add what you were doing when this happened._",
    ]
    return "\n".join(lines)


def is_expected(exc: BaseException, expected: Iterable[type[BaseException]]) -> bool:
    """Whether ``exc`` is one of the ``expected`` (user-facing / by-design)
    exception types that must NOT trigger an issue prompt."""
    return isinstance(exc, tuple(expected))


def report_anomaly(
    category: str,
    summary: str,
    *,
    detail: str = "",
    package: str = "goldenmatch",
    version: str | None = None,
    repo: str = _DEFAULT_REPO,
    exc: BaseException | None = None,
    once_key: str | None = None,
    logger: logging.Logger | None = None,
    extra_env: Mapping[str, Any] | None = None,
    labels: Sequence[str] | None = None,
) -> str | None:
    """Emit an actionable anomaly message with a prefilled issue URL, at most
    once per ``(category, once_key)`` per process.

    Returns the emitted message (for testing), or ``None`` when suppressed by the
    kill switch or the warn-once guard. NEVER raises -- diagnostics must not
    become the failure. Callers pass only ANOMALIES here (see the module
    docstring); expected fallbacks / user errors do not belong.
    """
    try:
        if not prompts_enabled():
            return None
        key = once_key or f"{category}:{summary}"
        if key in _REPORTED:
            return None
        _REPORTED.add(key)

        env = environment_report(package, version, extra_env)
        title = f"[{category}] {summary}"
        url = issue_url(
            title,
            _issue_body(category, summary, detail, env, exc),
            repo=repo,
            labels=labels or [category],
        )
        msg = (
            f"{summary}\n"
            f"This looks anomalous and may be a bug in {package}. If it is "
            f"unexpected, please report it (prefilled issue): {url}\n"
            f"(set {_KILL_ENV}=0 to silence these prompts)"
        )
        (logger or logging.getLogger(package)).warning(msg)
        return msg
    except Exception:  # noqa: BLE001 - diagnostics must never be load-bearing
        return None


def report_exception(
    exc: BaseException,
    *,
    category: str,
    summary: str,
    expected: Iterable[type[BaseException]] = (),
    **kwargs: Any,
) -> str | None:
    """Convenience wrapper: report ``exc`` only if it is NOT one of ``expected``
    (the by-design / user-facing exceptions). Returns ``None`` for expected
    exceptions so the caller can ``report_exception(...); raise`` unconditionally.
    """
    if is_expected(exc, expected):
        return None
    return report_anomaly(category, summary, exc=exc, **kwargs)
