#!/usr/bin/env node
/**
 * build_goldenprofile_wasm.mjs — build the GoldenProfile Virtual Fingerprint
 * wasm core and embed it into this TS package so the JS/TS surface resolves
 * through the SAME kernel (`goldenprofile-core`) as the Python `-native` wheel
 * and the C ABI. One source of truth; no hand-maintained parallel resolver.
 *
 * What it produces (all committed, so `tsc`/`vitest`/`tsup` need NO rust
 * toolchain — only this regen step does):
 *   - src/core/_wasm/goldenprofileWasmBindings.js   wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/goldenprofileWasmBindings.d.ts  hand-fixed minimal types
 *   - src/core/_wasm/goldenprofileWasmBytes.ts       base64 of the .wasm (edge-safe, no fs)
 *
 * Why strip the async init: wasm-bindgen's `--target web` glue ships an async
 * `__wbg_init` default export that references `import.meta.url` + `fetch`. That
 * breaks the CJS build (esbuild would inject a `node:url` shim — a forbidden
 * `node:*` dep in edge-safe `src/core/**`). We only ever call `initSync(bytes)`,
 * so we neutralize `import.meta.url` and re-export only `initSync`.
 *
 * Usage: node scripts/build_goldenprofile_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 *
 * Re-run this whenever goldenprofile-core (or graph/score/sketch/fingerprint
 * -core) changes, or the committed artifacts go stale vs the kernel — CI guards
 * the drift with a `git diff --exit-code` after a rebuild.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/goldenprofile-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

// 1. Build the wasm (wasm-opt disabled via the crate's Cargo.toml metadata so
//    the build is hermetic — no binaryen download in a network-restricted CI).
run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });

// 2. Glue JS: neutralize the async init path, re-export only initSync.
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_goldenprofile_wasm: expected to find ${label} in the wasm-bindgen ` +
        `glue but did not. The wasm-bindgen output format likely changed — ` +
        `re-inspect the glue and update this script.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = readFileSync(resolve(pkgDir, "goldenprofile_wasm.js"), "utf8");
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldenprofile_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_goldenprofile_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldenprofile-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "goldenprofileWasmBindings.js"), banner + glue);

// 3. Hand-fixed minimal .d.ts (stable across wasm-bindgen versions).
writeFileSync(
  resolve(outWasmDir, "goldenprofileWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_goldenprofile_wasm.mjs — DO NOT EDIT. */
export function resolve_json(request: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

// 4. base64-embed the wasm bytes (edge-safe: decoded via atob, no node:Buffer).
const wasm = readFileSync(resolve(pkgDir, "goldenprofile_wasm_bg.wasm"));
const b64 = wasm.toString("base64");
writeFileSync(
  resolve(outWasmDir, "goldenprofileWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_goldenprofile_wasm.mjs — DO NOT EDIT.
 * base64 of goldenprofile_wasm_bg.wasm (${wasm.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const GOLDENPROFILE_WASM_BASE64 =
  "${b64}";
`,
);

// 5. Regenerate the shared cross-surface parity fixtures from the HOST kernel
//    (the same one the wasm + Python -native wheel wrap). Canonicalized + so
//    byte-stable across runs; the TS + Python parity tests assert this file.
const fixtureFile = resolve(
  tsPkg,
  "tests/parity/fixtures/goldenprofile/resolutions.json",
);
mkdirSync(dirname(fixtureFile), { recursive: true });
console.log(`$ cargo run --release --example gen_parity_fixtures > ${fixtureFile}`);
const fixtures = execFileSync(
  "cargo",
  ["run", "--release", "--example", "gen_parity_fixtures"],
  { cwd: wasmCrate, encoding: "utf8" },
);
writeFileSync(fixtureFile, fixtures);

console.log(
  `\nDone. wasm ${wasm.length} B -> ${b64.length} B base64; bindings + bytes + parity fixtures written.`,
);
