#!/usr/bin/env node
/**
 * build_goldengraph_wasm.mjs — build the GoldenGraph KG-engine wasm core and
 * embed it into this TS package so the JS/TS surface runs the SAME kernel
 * (`goldengraph-core`) as the Python `-native` wheel and the C ABI. One source
 * of truth; no hand-maintained parallel engine.
 *
 * Produces (all committed, so tsc/vitest/tsup need NO rust toolchain):
 *   - src/core/_wasm/goldengraphWasmBindings.js    wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/goldengraphWasmBindings.d.ts   hand-fixed minimal types (4 ops)
 *   - src/core/_wasm/goldengraphWasmBytes.ts        base64 of the .wasm (edge-safe)
 *
 * Async init is stripped (it references import.meta.url + fetch — a forbidden
 * node:* shim in edge-safe src/core). We only ever call initSync(bytes).
 *
 * Usage: node scripts/build_goldengraph_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/goldengraph-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

// 1. Build the wasm (wasm-opt disabled via the crate's Cargo.toml metadata so
//    the build is hermetic — no binaryen download in a network-restricted CI).
run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });

// 2. Glue JS: neutralize the async init path, re-export only initSync.
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_goldengraph_wasm: expected to find ${label} in the wasm-bindgen ` +
        `glue but did not. The wasm-bindgen output format likely changed — ` +
        `re-inspect the glue and update this script.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = readFileSync(resolve(pkgDir, "goldengraph_wasm.js"), "utf8");
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldengraph_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_goldengraph_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldengraph-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "goldengraphWasmBindings.js"), banner + glue);

// 3. Hand-fixed minimal .d.ts (the 4 graph+query ops; stable across versions).
writeFileSync(
  resolve(outWasmDir, "goldengraphWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_goldengraph_wasm.mjs — DO NOT EDIT. */
export function build_graph(mentions_json: string, edges_json: string, resolution_json: string): string;
export function neighborhood(graph_json: string, seeds_json: string, hops: number): string;
export function seeds_by_name(graph_json: string, name: string): string;
export function communities(graph_json: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

// 4. base64-embed the wasm bytes (edge-safe: decoded via atob, no node:Buffer).
const wasm = readFileSync(resolve(pkgDir, "goldengraph_wasm_bg.wasm"));
const b64 = wasm.toString("base64");
writeFileSync(
  resolve(outWasmDir, "goldengraphWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_goldengraph_wasm.mjs — DO NOT EDIT.
 * base64 of goldengraph_wasm_bg.wasm (${wasm.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const GOLDENGRAPH_WASM_BASE64 =
  "${b64}";
`,
);

// 5. Regenerate the shared parity fixtures from the HOST kernel (the same one
//    the wasm + Python -native wheel wrap). Canonicalized + byte-stable; the TS
//    parity test asserts this file.
const fixtureFile = resolve(tsPkg, "tests/parity/fixtures/goldengraph/queries.json");
mkdirSync(dirname(fixtureFile), { recursive: true });
console.log(`$ cargo run --release --example gen_parity_fixtures > ${fixtureFile}`);
const fixtures = execFileSync(
  "cargo",
  ["run", "--release", "--example", "gen_parity_fixtures"],
  { cwd: wasmCrate, encoding: "utf8" },
);
writeFileSync(fixtureFile, fixtures);

console.log(
  `\nDone. wasm ${wasm.length} B -> ${b64.length} B base64; bindings + bytes + parity fixtures written.`,
);
