#!/usr/bin/env node
/**
 * build_fs_wasm.mjs — build the fs-wasm Fellegi-Sunter block-scoring core and
 * embed it into the TS package so the JS/TS surface runs the SAME
 * `goldenmatch-fs-core::score_fs_pair` kernel as the Python -native wheel — one
 * source of truth, byte-identical FS block scoring across Python-native and
 * TS-WASM by construction (the 2026-07-17 fs-core cross-surface design).
 *
 * Mirrors build_autoconfig_wasm.mjs exactly. Produces (all committed, so
 * tsc/vitest/tsup need NO rust toolchain — only this regen step does):
 *   - src/core/_wasm/fsWasmBindings.js    wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/fsWasmBindings.d.ts  hand-fixed minimal types
 *   - src/core/_wasm/fsWasmBytes.ts       base64 of the .wasm (edge-safe, no fs)
 *
 * The cross-surface parity fixture (tests/parity/fixtures/fs/fs_block_scoring.json)
 * is authored by the Python native kernel (scripts/emit_fs_wasm_fixture.py), the
 * independent oracle — this build script does NOT generate it.
 *
 * Usage: node scripts/build_fs_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/fs-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

// 1. Build the wasm (wasm-opt disabled in the crate's Cargo.toml metadata so the
//    build is hermetic — no binaryen download in a network-restricted CI).
run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });

// 2. Glue JS: neutralize the async init path, re-export only initSync (keeps
//    src/core edge-safe: no import.meta.url / fetch / node:url).
const glueSrc = readFileSync(resolve(pkgDir, "goldenmatch_fs_wasm.js"), "utf8");
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_fs_wasm: expected to find ${label} in the wasm-bindgen glue but ` +
        `did not. The wasm-bindgen output format likely changed — re-inspect ` +
        `the glue and update this script.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = glueSrc;
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldenmatch_fs_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_fs_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldenmatch-fs-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "fsWasmBindings.js"), banner + glue);

// 3. Hand-fixed minimal .d.ts (stable across wasm-bindgen versions).
writeFileSync(
  resolve(outWasmDir, "fsWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_fs_wasm.mjs — DO NOT EDIT. */
export function score_block_pairs_fs(
  row_ids: BigInt64Array,
  block_sizes: Uint32Array,
  field_values_flat: string[],
  field_nulls: Uint8Array,
  n_fields: number,
  scorer_ids: Uint8Array,
  levels: Uint8Array,
  partial_thresholds: Float64Array,
  match_weights_flat: Float64Array,
  match_weights_lens: Uint32Array,
  calibrated: boolean,
  prior_w: number,
  min_weight: number,
  weight_range: number,
  threshold: number,
): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

// 4. base64-embed the wasm bytes (edge-safe: decoded via atob, no node:Buffer).
const wasmBytes = readFileSync(resolve(pkgDir, "goldenmatch_fs_wasm_bg.wasm"));
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "fsWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_fs_wasm.mjs — DO NOT EDIT.
 * base64 of goldenmatch_fs_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const FS_WASM_BASE64 =
  "${b64}";
`,
);

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes written.`,
);
