#!/usr/bin/env node
/**
 * build_perceptual_wasm.mjs — build the perceptual image-pHash wasm core and
 * embed it into the TS package so the JS/TS surface computes the SAME hash as the
 * Python reference + the native kernel. The committed DCT table (tables.rs /
 * _perceptual_tables.py) makes the hash bit-identical across CPython / native /
 * wasm, so a JS-computed pHash is directly comparable to a Python-built index.
 *
 * Produces (all committed, so tsc/vitest/tsup need NO rust toolchain):
 *   - src/core/_wasm/perceptualWasmBindings.js    wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/perceptualWasmBindings.d.ts   hand-fixed minimal types
 *   - src/core/_wasm/perceptualWasmBytes.ts        base64 of the .wasm (edge-safe)
 *
 * Usage: node scripts/build_perceptual_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/perceptual-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);
mkdirSync(outWasmDir, { recursive: true });

function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_perceptual_wasm: expected ${label} in the wasm-bindgen glue but ` +
        `did not find it — the output format likely changed.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = readFileSync(resolve(pkgDir, "goldenmatch_perceptual_wasm.js"), "utf8");
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldenmatch_perceptual_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_perceptual_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldenmatch-perceptual-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "perceptualWasmBindings.js"), banner + glue);

writeFileSync(
  resolve(outWasmDir, "perceptualWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_perceptual_wasm.mjs — DO NOT EDIT. */
export function phash_image_hex(grid_json: string): string;
export function hamming_hex(a_hex: string, b_hex: string): number;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

const wasm = readFileSync(resolve(pkgDir, "goldenmatch_perceptual_wasm_bg.wasm"));
const b64 = wasm.toString("base64");
writeFileSync(
  resolve(outWasmDir, "perceptualWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_perceptual_wasm.mjs — DO NOT EDIT.
 * base64 of goldenmatch_perceptual_wasm_bg.wasm (${wasm.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const PERCEPTUAL_WASM_BASE64 =
  "${b64}";
`,
);

console.log(`\nDone. wasm ${wasm.length} B -> ${b64.length} B base64; bindings + bytes written.`);
