#!/usr/bin/env node
/**
 * build_cluster_wasm.mjs — build the cluster (MST-split + confidence) wasm core
 * and embed it into the TS package, so the JS/TS clustering step consumes the
 * SAME cluster-core kernels as the Python native path and the Rust core. The
 * hand-written `splitOversizedCluster` / `computeClusterConfidence` stay the
 * faithful fallback. Mirrors scripts/build_graph_wasm.mjs.
 *
 * Produces (all committed, so tsc/vitest/tsup need NO rust toolchain):
 *   - src/core/_wasm/clusterWasmBindings.js     wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/clusterWasmBindings.d.ts    hand-fixed minimal types
 *   - src/core/_wasm/clusterWasmBytes.ts         base64 of the .wasm (edge-safe)
 *
 * (No golden-vector fixture is copied: cluster-core carries no `golden/` dir —
 * the parity test derives its oracle from the pure-TS impl + the Python
 * cluster-handoff conformance fixture.)
 *
 * Usage: node scripts/build_cluster_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/cluster-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });

const glueSrc = readFileSync(resolve(pkgDir, "cluster_wasm.js"), "utf8");
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_cluster_wasm: expected to find ${label} in the wasm-bindgen glue ` +
        `but did not. The wasm-bindgen output format likely changed — re-inspect.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = glueSrc;
glue = assertReplace(
  glue,
  "module_or_path = new URL('cluster_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_cluster_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for cluster-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "clusterWasmBindings.js"), banner + glue);

writeFileSync(
  resolve(outWasmDir, "clusterWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_cluster_wasm.mjs — DO NOT EDIT. */
export function mst_split_components(
  members: Int32Array,
  edges_a: Int32Array,
  edges_b: Int32Array,
  edges_w: Float64Array,
): string;
export function cluster_confidence(
  edges_a: Int32Array,
  edges_b: Int32Array,
  edges_w: Float64Array,
  size: number,
): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

const wasmBytes = readFileSync(resolve(pkgDir, "cluster_wasm_bg.wasm"));
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "clusterWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_cluster_wasm.mjs — DO NOT EDIT.
 * base64 of cluster_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const CLUSTER_WASM_BASE64 =
  "${b64}";
`,
);

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes written.`,
);
