#!/usr/bin/env node
/**
 * build_goldenhnsw_wasm.mjs — build the goldenhnsw wasm core and embed it into
 * the TS package so the JS/TS surface runs the SAME native HNSW kernel as the
 * Python wheel and the Rust core (one source of truth; byte-identical
 * inner-product ranking). Mirrors build_autoconfig_wasm.mjs.
 *
 * What it produces (all committed, so `tsc`/`vitest`/`tsup` need NO rust
 * toolchain — only this regen step does):
 *   - src/core/_wasm/goldenhnswWasmBindings.js    wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/goldenhnswWasmBindings.d.ts   hand-fixed minimal types
 *   - src/core/_wasm/goldenhnswWasmBytes.ts        base64 of the .wasm (edge-safe, no fs)
 *   - tests/parity/fixtures/hnsw/hnsw_vectors.json golden vector (cross-surface gate)
 *
 * Why strip the async init: wasm-bindgen's `--target web` glue ships an async
 * `__wbg_init` default export that references `import.meta.url` + `fetch`, which
 * breaks the edge-safe CJS build (esbuild would inject a `node:url` shim). We
 * only ever call `initSync(bytes)`, so we neutralize `import.meta.url` and
 * re-export only `initSync` (+ the WasmHnswIndex class); the dead async path
 * tree-shakes away.
 *
 * Usage: node scripts/build_goldenhnsw_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/goldenhnsw-wasm");
const coreCrate = resolve(tsPkg, "../../rust/extensions/goldenhnsw");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");
const fixturesDir = resolve(tsPkg, "tests/parity/fixtures/hnsw");

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

// 1. Build the wasm (wasm-opt disabled in the crate's Cargo.toml metadata so
//    the build is hermetic — no binaryen download in a network-restricted CI).
run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });
mkdirSync(fixturesDir, { recursive: true });

// 2. Glue JS: neutralize the async init path, re-export only initSync (the
//    WasmHnswIndex class is a top-level `export class`, so it survives as-is).
const glueSrc = readFileSync(resolve(pkgDir, "goldenhnsw_wasm.js"), "utf8");
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_goldenhnsw_wasm: expected to find ${label} in the wasm-bindgen ` +
        `glue but did not. The wasm-bindgen output format likely changed — ` +
        `re-inspect the glue and update this script.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = glueSrc;
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldenhnsw_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_goldenhnsw_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldenhnsw-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "goldenhnswWasmBindings.js"), banner + glue);

// 3. Hand-fixed minimal .d.ts (stable across wasm-bindgen versions).
writeFileSync(
  resolve(outWasmDir, "goldenhnswWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_goldenhnsw_wasm.mjs — DO NOT EDIT. */
export class WasmHnswIndex {
  constructor(
    dim: number,
    m: number,
    ef_construction: number,
    ef_search: number,
    seed: number,
  );
  free(): void;
  add(vec: Float32Array): number;
  add_batch(flat: Float32Array, n: number): number;
  search(query: Float32Array, k: number): Float64Array;
  readonly dim: number;
  readonly len: number;
  readonly is_empty: boolean;
}
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

// 4. base64-embed the wasm bytes (edge-safe: decoded via atob, no node:Buffer).
const wasmBytes = readFileSync(resolve(pkgDir, "goldenhnsw_wasm_bg.wasm"));
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "goldenhnswWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_goldenhnsw_wasm.mjs — DO NOT EDIT.
 * base64 of goldenhnsw_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const GOLDENHNSW_WASM_BASE64 =
  "${b64}";
`,
);

// 5. Copy the golden vector into the TS parity fixtures (cross-surface gate:
//    the Rust core test tests/golden.rs and the TS wasm parity test both read
//    the SAME expected neighbors).
copyFileSync(
  resolve(coreCrate, "golden/hnsw_vectors.json"),
  resolve(fixturesDir, "hnsw_vectors.json"),
);

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes + fixture written.`,
);
