#!/usr/bin/env node
/**
 * build_sketch_wasm.mjs — build the sketch (MinHash + LSH) wasm core and embed
 * it into the TS package so the JS/TS blocker consumes the SAME sketch kernel as
 * the Python reference and the Rust core (one hash family; the pure-TS
 * `sketch.ts` becomes a faithful fallback, not a third parallel implementation).
 *
 * What it produces (all committed, so `tsc`/`vitest`/`tsup` need NO rust
 * toolchain — only this regen step does):
 *   - src/core/_wasm/sketchWasmBindings.js    wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/sketchWasmBindings.d.ts   hand-fixed minimal types
 *   - src/core/_wasm/sketchWasmBytes.ts        base64 of the .wasm (edge-safe, no fs)
 *   - tests/parity/fixtures/sketch/sketch_golden.json   the shared cross-language
 *                                              oracle (copied from the Python pkg).
 *
 * Why strip the async init: wasm-bindgen's `--target web` glue ships an async
 * `__wbg_init` default export referencing `import.meta.url` + `fetch`. That
 * breaks the CJS build (esbuild would inject a `node:url` shim — forbidden in
 * edge-safe `src/core/**`). We only ever call `initSync(bytes)`, so we
 * neutralize `import.meta.url` and re-export only `initSync`.
 *
 * Usage: node scripts/build_sketch_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/sketch-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");
const fixturesDir = resolve(tsPkg, "tests/parity/fixtures/sketch");
// The shared golden vectors live with the Python reference package; Rust's
// `sketch-core/tests/golden.rs` and this TS parity test both check against them.
const goldenSrc = resolve(
  tsPkg,
  "../../python/goldenmatch/tests/fixtures/sketch_golden.json",
);

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

// 1. Build the wasm (wasm-opt disabled in the crate's Cargo.toml metadata so
//    the build is hermetic — no binaryen download in a network-restricted CI).
run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });
mkdirSync(fixturesDir, { recursive: true });

// 2. Glue JS: neutralize the async init path, re-export only initSync.
const glueSrc = readFileSync(resolve(pkgDir, "sketch_wasm.js"), "utf8");
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_sketch_wasm: expected to find ${label} in the wasm-bindgen ` +
        `glue but did not. The wasm-bindgen output format likely changed — ` +
        `re-inspect the glue and update this script.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = glueSrc;
glue = assertReplace(
  glue,
  "module_or_path = new URL('sketch_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_sketch_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for sketch-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "sketchWasmBindings.js"), banner + glue);

// 3. Hand-fixed minimal .d.ts (stable across wasm-bindgen versions).
writeFileSync(
  resolve(outWasmDir, "sketchWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_sketch_wasm.mjs — DO NOT EDIT. */
export function base_hash(data: Uint8Array): bigint;
export function shingle(text: string, mode: string, k: number): BigUint64Array;
export function signature(shingles: BigUint64Array, num_perms: number, seed: bigint): BigUint64Array;
export function band_hashes(sig: BigUint64Array, num_bands: number): BigUint64Array;
export function sketch_band_hashes(text: string, mode: string, k: number, num_perms: number, num_bands: number, seed: bigint): BigUint64Array;
export function sketch_band_hashes_batch(texts: string[], mode: string, k: number, num_perms: number, num_bands: number, seed: bigint): BigUint64Array;
export function estimate_jaccard(sig_a: BigUint64Array, sig_b: BigUint64Array): number;
export function optimal_bands(num_perms: number, threshold: number): Uint32Array;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

// 4. base64-embed the wasm bytes (edge-safe: decoded via atob, no node:Buffer).
const wasmBytes = readFileSync(resolve(pkgDir, "sketch_wasm_bg.wasm"));
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "sketchWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_sketch_wasm.mjs — DO NOT EDIT.
 * base64 of sketch_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const SKETCH_WASM_BASE64 =
  "${b64}";
`,
);

// 5. Copy the shared golden fixture into the TS parity fixtures (cross-surface
//    gate). Same file the Rust sketch-core golden test validates against.
copyFileSync(goldenSrc, resolve(fixturesDir, "sketch_golden.json"));

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes + golden fixture written.`,
);
