#!/usr/bin/env node
/**
 * build_documents_wasm.mjs — build the documents-core wasm kernels and embed
 * them into the TS package so the JS/TS surface consumes the SAME document-
 * ingest kernels as the Python -native wheel (one source of truth).
 *
 * Produces (all committed, so tsc/vitest/tsup need NO rust toolchain — only
 * this regen step does; requires wasm-pack + the wasm32-unknown-unknown target):
 *   - src/core/_wasm/documentsWasmBindings.js / .d.ts   wasm-bindgen glue (async path stripped)
 *   - src/core/_wasm/documentsWasmBytes.ts              base64 of the .wasm (edge-safe)
 *   - tests/parity/fixtures/documents/documents_corpus.jsonl  the shared corpus, copied
 *
 * The corpus is Python-authored (scripts/gen_documents_corpus.py) and already
 * asserted ==native in the Python parity lane; this script COPIES it so the TS
 * parity test runs the identical vectors. Async init is stripped for the same
 * reason as suggest-wasm (keeps src/core edge-safe: no node:url / fetch).
 *
 * Usage: node scripts/build_documents_wasm.mjs
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/documents-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");
const fixturesDir = resolve(tsPkg, "tests/parity/fixtures/documents");
const corpusSrc = resolve(
  tsPkg,
  "../../python/goldenmatch/tests/parity/documents_corpus.jsonl",
);

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

// 1. Build the wasm (wasm-opt disabled in the crate's Cargo.toml so the build
//    is hermetic — no binaryen download in a network-restricted CI).
run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });
mkdirSync(fixturesDir, { recursive: true });

// 2. Glue JS: neutralize the async init path, re-export only initSync.
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_documents_wasm: expected to find ${label} in the wasm-bindgen ` +
        `glue but did not. The wasm-bindgen output format likely changed — ` +
        `re-inspect the glue and update this script.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = readFileSync(resolve(pkgDir, "goldenmatch_documents_wasm.js"), "utf8");
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldenmatch_documents_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_documents_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldenmatch-documents-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "documentsWasmBindings.js"), banner + glue);

// 3. Hand-fixed minimal .d.ts (stable across wasm-bindgen versions) — all 10 exports.
writeFileSync(
  resolve(outWasmDir, "documentsWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_documents_wasm.mjs — DO NOT EDIT. */
export function schema_validate(schema_json: string): string;
export function parse_message_text(resp_json: string): string;
export function extract_instruction(schema_json: string): string;
export function suggest_prompt(): string;
export function normalize_record(
  values_json: string,
  confidence_json: string,
  schema_json: string,
): string;
export function documents_template(doctype: string): string;
export function documents_template_list(): string;
export function documents_classify_prompt(): string;
export function documents_parse_classify(text: string): string;
export function documents_parse_structured(
  text: string,
  template_json: string,
): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

// 4. base64-embed the wasm bytes (edge-safe: decoded via atob, no node:Buffer).
const wasmBytes = readFileSync(
  resolve(pkgDir, "goldenmatch_documents_wasm_bg.wasm"),
);
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "documentsWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_documents_wasm.mjs — DO NOT EDIT.
 * base64 of goldenmatch_documents_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const DOCUMENTS_WASM_BASE64 =
  "${b64}";
`,
);

// 5. Copy the shared Python-authored corpus into the TS parity fixtures.
copyFileSync(corpusSrc, resolve(fixturesDir, "documents_corpus.jsonl"));

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes + corpus written.`,
);
