#!/usr/bin/env node
/**
 * build_autoconfig_wasm.mjs — build the autoconfig wasm core and embed it into
 * the TS package so the JS/TS surface consumes the SAME decision core as the
 * Python -native wheel (one source of truth; no hand-maintained parallel
 * planner/classifier).
 *
 * What it produces (all committed, so `tsc`/`vitest`/`tsup` need NO rust
 * toolchain — only this regen step does):
 *   - src/core/_wasm/autoconfigWasmBindings.js   wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/autoconfigWasmBindings.d.ts  hand-fixed minimal types
 *   - src/core/_wasm/autoconfigWasmBytes.ts       base64 of the .wasm (edge-safe, no fs)
 *   - tests/parity/fixtures/autoconfig/*.json     golden vectors (cross-surface gate)
 *
 * Why strip the async init: wasm-bindgen's `--target web` glue ships an async
 * `__wbg_init` default export that references `import.meta.url` + `fetch`. That
 * breaks the CJS build (esbuild would inject a `node:url` shim — a forbidden
 * `node:*` dep in edge-safe `src/core/**`). We only ever call `initSync(bytes)`,
 * so we neutralize `import.meta.url` and re-export only `initSync`; tree-shaking
 * drops the dead async path entirely.
 *
 * Usage: node scripts/build_autoconfig_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/autoconfig-wasm");
const coreCrate = resolve(tsPkg, "../../rust/extensions/autoconfig-core");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");
const fixturesDir = resolve(tsPkg, "tests/parity/fixtures/autoconfig");

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

// 1. Build the wasm (wasm-opt disabled in the crate's Cargo.toml metadata so
//    the build is hermetic — no binaryen download in a network-restricted CI).
run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });
mkdirSync(fixturesDir, { recursive: true });

// 2. Glue JS: neutralize the async init path, re-export only initSync.
const glueSrc = readFileSync(
  resolve(pkgDir, "goldenmatch_autoconfig_wasm.js"),
  "utf8",
);
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_autoconfig_wasm: expected to find ${label} in the wasm-bindgen ` +
        `glue but did not. The wasm-bindgen output format likely changed — ` +
        `re-inspect the glue and update this script.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = glueSrc;
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldenmatch_autoconfig_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_autoconfig_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldenmatch-autoconfig-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "autoconfigWasmBindings.js"), banner + glue);

// 3. Hand-fixed minimal .d.ts (stable across wasm-bindgen versions).
writeFileSync(
  resolve(outWasmDir, "autoconfigWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_autoconfig_wasm.mjs — DO NOT EDIT. */
export function autoconfig_classify_columns(cols_json: string): string;
export function autoconfig_decide_plan(input_json: string): string;
export function autoconfig_extrapolate_pair_count(input_json: string): string;
export function autoconfig_sparse_match_floor(input_json: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

// 4. base64-embed the wasm bytes (edge-safe: decoded via atob, no node:Buffer).
const wasmBytes = readFileSync(
  resolve(pkgDir, "goldenmatch_autoconfig_wasm_bg.wasm"),
);
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "autoconfigWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_autoconfig_wasm.mjs — DO NOT EDIT.
 * base64 of goldenmatch_autoconfig_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const AUTOCONFIG_WASM_BASE64 =
  "${b64}";
`,
);

// 5. Copy the golden vectors into the TS parity fixtures (cross-surface gate).
for (const name of [
  "planner_vectors.json",
  "classifier_vectors.json",
  "extrapolation_vectors.json",
  "sparse_match_floor_vectors.json",
]) {
  copyFileSync(
    resolve(coreCrate, "golden", name),
    resolve(fixturesDir, name),
  );
}

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes + fixtures written.`,
);
