#!/usr/bin/env node
/**
 * build_key_integrity_wasm.mjs — build the structural key-integrity wasm core and
 * embed it into the TS package, so the JS/TS `certifyKeyIntegrity` STRUCTURAL
 * compute (group-by uniqueness + fan-out) runs the SAME key-integrity-core kernel
 * as the Python reference. The hand-written pure-TS reduction stays the faithful
 * fallback + default.
 *
 * Produces (all committed, so tsc/vitest/tsup need NO rust toolchain):
 *   - src/core/_wasm/keyIntegrityWasmBindings.js    wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/keyIntegrityWasmBindings.d.ts  hand-fixed minimal types
 *   - src/core/_wasm/keyIntegrityWasmBytes.ts       base64 of the .wasm (edge-safe)
 *   - tests/parity/fixtures/key-integrity/key_integrity_golden.json  the shared oracle
 *                                     (copied from key-integrity-core/golden/).
 *
 * Usage: node scripts/build_key_integrity_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/key-integrity-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");
const fixturesDir = resolve(tsPkg, "tests/parity/fixtures/key-integrity");
const goldenSrc = resolve(
  tsPkg,
  "../../rust/extensions/key-integrity-core/golden/key_integrity_golden.json",
);

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });
mkdirSync(fixturesDir, { recursive: true });

const glueSrc = readFileSync(resolve(pkgDir, "key_integrity_wasm.js"), "utf8");
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_key_integrity_wasm: expected to find ${label} in the wasm-bindgen glue ` +
        `but did not. The wasm-bindgen output format likely changed — re-inspect.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = glueSrc;
glue = assertReplace(
  glue,
  "module_or_path = new URL('key_integrity_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_key_integrity_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for key-integrity-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "keyIntegrityWasmBindings.js"), banner + glue);

writeFileSync(
  resolve(outWasmDir, "keyIntegrityWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_key_integrity_wasm.mjs — DO NOT EDIT. */
export function certify_structural_json(input_json: string): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

const wasmBytes = readFileSync(resolve(pkgDir, "key_integrity_wasm_bg.wasm"));
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "keyIntegrityWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_key_integrity_wasm.mjs — DO NOT EDIT.
 * base64 of key_integrity_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const KEY_INTEGRITY_WASM_BASE64 =
  "${b64}";
`,
);

copyFileSync(goldenSrc, resolve(fixturesDir, "key_integrity_golden.json"));

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes + golden fixture written.`,
);
