#!/usr/bin/env node
/**
 * build_goldenembed_wasm.mjs — build the in-house-embedder wasm core and embed
 * it into the TS package, so char n-gram featurize + the linear projection head
 * run at the edge (the SAME kernels as the Python native path and the SQL
 * surfaces). This is what closes parity-roadmap P10 (embed -> edge): unlike the
 * `ort`-linked `goldenembed` runtime, `goldenembed-core` pulls no ONNX/C++ and
 * so compiles to wasm32.
 *
 * Produces (all committed, so tsc/vitest/tsup need NO rust toolchain):
 *   - src/core/_wasm/goldenembedWasmBindings.js    wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/goldenembedWasmBindings.d.ts  hand-fixed minimal types
 *   - src/core/_wasm/goldenembedWasmBytes.ts       base64 of the .wasm (edge-safe)
 *   - tests/parity/fixtures/goldenembed/project_golden.json  the shared oracle
 *                             (copied from goldenembed-core/golden/).
 *
 * Usage: node scripts/build_goldenembed_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/goldenembed-wasm");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");
const fixturesDir = resolve(tsPkg, "tests/parity/fixtures/goldenembed");
const goldenSrc = resolve(
  tsPkg,
  "../../rust/extensions/goldenembed-core/golden/project_golden.json",
);

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });
mkdirSync(fixturesDir, { recursive: true });

const glueSrc = readFileSync(resolve(pkgDir, "goldenembed_wasm.js"), "utf8");
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_goldenembed_wasm: expected to find ${label} in the wasm-bindgen glue ` +
        `but did not. The wasm-bindgen output format likely changed — re-inspect.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = glueSrc;
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldenembed_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_goldenembed_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldenembed-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "goldenembedWasmBindings.js"), banner + glue);

writeFileSync(
  resolve(outWasmDir, "goldenembedWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_goldenembed_wasm.mjs — DO NOT EDIT. */
export class Embedder {
  free(): void;
  constructor(
    weights: Float32Array,
    dim: number,
    bias: Float32Array | undefined,
    n_features: number,
    ngram_min: number,
    ngram_max: number,
    lowercase: boolean,
    boundary: string,
    seed: number,
  );
  readonly dim: number;
  embed(texts: string[]): Float32Array;
}
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

const wasmBytes = readFileSync(resolve(pkgDir, "goldenembed_wasm_bg.wasm"));
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "goldenembedWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_goldenembed_wasm.mjs — DO NOT EDIT.
 * base64 of goldenembed_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const GOLDENEMBED_WASM_BASE64 =
  "${b64}";
`,
);

copyFileSync(goldenSrc, resolve(fixturesDir, "project_golden.json"));

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes + golden fixture written.`,
);
