// Regenerates src/core/refdata/{givenNameAliases,censusSurnames}.ts from the
// Python source of truth. Run from packages/typescript/goldenmatch/. Node >= 18.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const PY_JSON = join(
  here,
  "../../../python/goldenmatch/goldenmatch/refdata/data/given_name_aliases.json",
);
const OUT = join(here, "../src/core/refdata/givenNameAliases.ts");

const payload = JSON.parse(readFileSync(PY_JSON, "utf-8"));
const banner =
  "// GENERATED by scripts/sync_ts_refdata.mjs from\n" +
  "// packages/python/goldenmatch/goldenmatch/refdata/data/given_name_aliases.json\n" +
  "// Do NOT edit by hand. Run `node scripts/sync_ts_refdata.mjs` to refresh.\n" +
  "// Drift is guarded by tests/unit/refdata-sync.test.ts.\n";
const body =
  banner +
  "export const GIVEN_NAME_ALIASES = " +
  JSON.stringify(payload, null, 2) +
  " as const;\n";
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body, "utf-8");
console.log(`wrote ${OUT}`);

// --- census surnames ---
const CSV = join(
  here,
  "../../../python/goldenmatch/goldenmatch/refdata/data/census_surnames_2010_top10k.csv",
);
const OUT_SURNAMES = join(here, "../src/core/refdata/censusSurnames.ts");
const csvText = readFileSync(CSV, "utf-8");
const csvLines = csvText.split(/\r?\n/).filter((l) => l.length > 0);
csvLines.shift(); // drop "name,rank,count" header
const surnameRows = csvLines.map((line) => {
  const [name, rank, count] = line.split(",");
  return [name, Number(rank), Number(count)];
});
const surnameBanner =
  "// GENERATED by scripts/sync_ts_refdata.mjs from\n" +
  "// packages/python/goldenmatch/goldenmatch/refdata/data/census_surnames_2010_top10k.csv\n" +
  "// Do NOT edit by hand. Run `node scripts/sync_ts_refdata.mjs` to refresh.\n" +
  "// Drift is guarded by tests/unit/refdata-sync.test.ts. Rows: [name, rank, count].\n";
// NOTE: explicit type annotation, NO `as const` — `as const` on a 10k-tuple
// array creates a pathological literal type that bloats tsc.
const surnameBody =
  surnameBanner +
  "export const CENSUS_SURNAMES: ReadonlyArray<readonly [string, number, number]> = " +
  JSON.stringify(surnameRows) +
  ";\n";
mkdirSync(dirname(OUT_SURNAMES), { recursive: true });
writeFileSync(OUT_SURNAMES, surnameBody, "utf-8");
console.log(`wrote ${OUT_SURNAMES}`);
