// Regenerates src/core/refdata/givenNameAliases.ts from the Python source of
// truth. Run from packages/typescript/goldenmatch/. Node >= 18.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const PY_JSON = join(
  here,
  "../../../python/goldenmatch/goldenmatch/refdata/data/given_name_aliases.json",
);
const OUT = join(here, "../src/core/refdata/givenNameAliases.ts");

const payload = JSON.parse(readFileSync(PY_JSON, "utf-8"));
const banner =
  "// GENERATED by scripts/sync_ts_refdata.mjs from\n" +
  "// packages/python/goldenmatch/goldenmatch/refdata/data/given_name_aliases.json\n" +
  "// Do NOT edit by hand. Run `node scripts/sync_ts_refdata.mjs` to refresh.\n" +
  "// Drift is guarded by tests/unit/refdata-sync.test.ts.\n";
const body =
  banner +
  "export const GIVEN_NAME_ALIASES = " +
  JSON.stringify(payload, null, 2) +
  " as const;\n";
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body, "utf-8");
console.log(`wrote ${OUT}`);
