/**
 * Cross-language conformance for the referential-integrity engine.
 *
 * `refs` has no Rust `-core` owner (cheap set-membership — "kernelize on
 * measurement" says don't), so the Python engine (engine/referential.py) and the
 * TS port (core/engine/referential.ts) are two hand-written implementations. Per
 * the repo thesis, co-equal ports must be locked by a conformance contract or they
 * silently drift. This fixture is that lock: the Python engine's findings on a
 * committed child/parent pair, which the TS port must reproduce.
 *
 * Ground truth (`refs_conformance.expected.json`) generated by:
 *   uv run python -c "from goldencheck.engine.referential import \
 *     referential_integrity_files; ... json.dumps([norm(f) for f in fs])"
 * (see the commit for the exact normalizer). `sample_values` are compared as a
 * SORTED set because polars `Series.unique()` ordering is not stable — the SET of
 * representative orphans is the semantic invariant, not their order.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { basename, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { readFile } from "../../src/node/reader.js";
import { referentialIntegrity } from "../../src/core/engine/referential.js";
import { severityLabel, type Finding } from "../../src/core/types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(__dirname, "..", "fixtures");

interface NormalizedFinding {
  severity: string;
  column: string;
  check: string;
  message: string;
  affected_rows: number;
  sample_values: string[];
  metadata: Record<string, unknown>;
}

function normalize(f: Finding): NormalizedFinding {
  return {
    severity: severityLabel(f.severity),
    column: f.column,
    check: f.check,
    message: f.message,
    affected_rows: f.affectedRows,
    sample_values: [...f.sampleValues].sort(),
    metadata: f.metadata as Record<string, unknown>,
  };
}

describe("referential-integrity cross-language conformance", () => {
  it("TS findings match the committed Python output", () => {
    const childPath = join(FIXTURES_DIR, "refs_child.csv");
    const parentPath = join(FIXTURES_DIR, "refs_parent.csv");
    const expected = JSON.parse(
      readFileSync(join(FIXTURES_DIR, "refs_conformance.expected.json"), "utf-8"),
    ) as NormalizedFinding[];

    const child = readFile(childPath);
    const parent = readFile(parentPath);
    // childName/parentName mirror the Python CLI (basename of each path).
    const findings = referentialIntegrity(child, parent, undefined, {
      childName: basename(childPath),
      parentName: basename(parentPath),
    });

    expect(findings.map(normalize)).toEqual(expected);
  });
});
