#!/usr/bin/env node
/**
 * build_goldencheck_wasm.mjs — build the goldencheck-core deep-profiling kernels
 * as wasm and embed them into the TS package, so the JS/TS surface runs the SAME
 * code as the Python `goldencheck-native` wheel (one source of truth; the
 * hand-written TS composite-key / FD logic becomes a pure-TS fallback). Mirrors
 * goldenmatch's build_autoconfig_wasm.mjs / build_goldenhnsw_wasm.mjs.
 *
 * Produces (all committed, so tsc/vitest/tsup need NO rust toolchain):
 *   - src/core/_wasm/goldencheckWasmBindings.js    wasm-bindgen glue, async path stripped
 *   - src/core/_wasm/goldencheckWasmBindings.d.ts   hand-fixed minimal types
 *   - src/core/_wasm/goldencheckWasmBytes.ts        base64 of the .wasm (edge-safe, no fs)
 *   - tests/parity/fixtures/gc_vectors.json         golden vector (cross-surface gate)
 *
 * Usage: node scripts/build_goldencheck_wasm.mjs
 * Requires: wasm-pack + the wasm32-unknown-unknown rust target on PATH.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tsPkg = resolve(here, "..");
const wasmCrate = resolve(tsPkg, "../../rust/extensions/goldencheck-wasm");
const coreCrate = resolve(tsPkg, "../../rust/extensions/goldencheck-core");
const pkgDir = resolve(wasmCrate, "pkg");
const outWasmDir = resolve(tsPkg, "src/core/_wasm");
const fixturesDir = resolve(tsPkg, "tests/parity/fixtures");

function run(cmd, args, cwd) {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  execFileSync(cmd, args, { cwd, stdio: "inherit" });
}

// 1. Build the wasm (wasm-opt disabled in the crate's Cargo.toml metadata so the
//    build is hermetic — no binaryen download in a network-restricted CI).
run("wasm-pack", ["build", wasmCrate, "--target", "web"], tsPkg);

mkdirSync(outWasmDir, { recursive: true });
mkdirSync(fixturesDir, { recursive: true });

// 2. Glue JS: neutralize the async init path, re-export only initSync (the free
//    gc_* functions are top-level `export function`s, so they survive as-is).
const glueSrc = readFileSync(resolve(pkgDir, "goldencheck_wasm.js"), "utf8");
function assertReplace(src, needle, repl, label) {
  if (!src.includes(needle)) {
    throw new Error(
      `build_goldencheck_wasm: expected to find ${label} in the wasm-bindgen ` +
        `glue but did not. The wasm-bindgen output format likely changed — ` +
        `re-inspect the glue and update this script.`,
    );
  }
  return src.replace(needle, repl);
}
let glue = glueSrc;
glue = assertReplace(
  glue,
  "module_or_path = new URL('goldencheck_wasm_bg.wasm', import.meta.url);",
  "module_or_path = undefined; // import.meta.url stripped (async path unused; keeps src/core edge-safe)",
  "the import.meta.url URL construction",
);
glue = assertReplace(
  glue,
  "export { initSync, __wbg_init as default };",
  "export { initSync };",
  "the module export line",
);
const banner =
  "/* AUTO-GENERATED by scripts/build_goldencheck_wasm.mjs — DO NOT EDIT.\n" +
  "   wasm-bindgen glue for goldencheck-wasm, async init path stripped. */\n";
writeFileSync(resolve(outWasmDir, "goldencheckWasmBindings.js"), banner + glue);

// 3. Hand-fixed minimal .d.ts (stable across wasm-bindgen versions).
writeFileSync(
  resolve(outWasmDir, "goldencheckWasmBindings.d.ts"),
  `/* AUTO-GENERATED by scripts/build_goldencheck_wasm.mjs — DO NOT EDIT. */
export function gc_discover_functional_dependencies(columns_json: string): string;
export function gc_discover_approximate_fds(columns_json: string, min_confidence: number): string;
export function gc_functional_dependency_holds(lhs_json: string, rhs_json: string): string;
export function gc_fd_violation_rows(det_json: string, dep_json: string): string;
export function gc_composite_key_search(columns_json: string, max_size: number, single_unique_json: string): string;
export function gc_benford_leading_digits(values_json: string): string;
export function gc_near_duplicate_clusters(values_json: string, min_similarity: number): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
`,
);

// 4. base64-embed the wasm bytes (edge-safe: decoded via atob, no node:Buffer).
const wasmBytes = readFileSync(resolve(pkgDir, "goldencheck_wasm_bg.wasm"));
const b64 = wasmBytes.toString("base64");
writeFileSync(
  resolve(outWasmDir, "goldencheckWasmBytes.ts"),
  `/* AUTO-GENERATED by scripts/build_goldencheck_wasm.mjs — DO NOT EDIT.
 * base64 of goldencheck_wasm_bg.wasm (${wasmBytes.length} bytes).
 * Inlined so the loader stays synchronous + edge-safe (no fs / fetch). */
export const GOLDENCHECK_WASM_BASE64 =
  "${b64}";
`,
);

// 5. Copy the golden vector into the TS parity fixtures (cross-surface gate: the
//    Rust core test goldencheck-core/tests/golden.rs and the TS parity test both
//    read the SAME expected values).
copyFileSync(
  resolve(coreCrate, "golden/gc_vectors.json"),
  resolve(fixturesDir, "gc_vectors.json"),
);

console.log(
  `\nDone. wasm ${wasmBytes.length} B -> ${b64.length} B base64; ` +
    `bindings + bytes + fixture written.`,
);
