#!/usr/bin/env python3
"""Generate `src/combining_table.rs` — the sorted codepoint ranges of Unicode
combining marks (general categories Mn = Nonspacing_Mark and Me = Enclosing_Mark).

`nysiis` follows jellyfish in segmenting GRAPHEME clusters. We implement UAX-29
rule GB9 (a run of Grapheme_Extend attaches to the preceding character) over this
table, which reproduces `unicode-segmentation`'s clustering for every combining-
mark (accented) input -- the phonetically relevant case -- without a runtime dep.
Mn u Me is the combining-mark core of Grapheme_Extend; it covers all diacritics
(U+0300..U+036F etc.). Emoji-ZWJ / regional-indicator / Hangul-conjoining
clustering (GB11/GB12/GB6..8) is out of scope: those never appear in names, and
this crate documents that residual edge.

Regenerate:
    uv run --no-project --python 3.12 python \
        packages/rust/extensions/goldenphonetic-core/scripts/gen_combining_table.py
"""
from __future__ import annotations

import unicodedata
from pathlib import Path


def main() -> None:
    marks = [cp for cp in range(0, 0x110000) if unicodedata.category(chr(cp)) in ("Mn", "Me")]

    # collapse to inclusive ranges
    ranges: list[tuple[int, int]] = []
    for cp in marks:
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], cp)
        else:
            ranges.append((cp, cp))

    lines = [
        "// AUTO-GENERATED by scripts/gen_combining_table.py from Python unicodedata "
        "(Unicode 15.0.0).",
        "// Inclusive codepoint ranges of combining marks (general category Mn or Me) --",
        "// the Grapheme_Extend core used by the UAX-29 GB9 grapheme clustering in",
        "// `grapheme.rs`. Sorted ascending; binary-searched at runtime. DO NOT EDIT.",
        "",
        "/// Inclusive (lo, hi) ranges of combining-mark codepoints, sorted by `lo`.",
        "pub(crate) static COMBINING: &[(u32, u32)] = &[",
    ]
    for lo, hi in ranges:
        lines.append("    (0x%X, 0x%X)," % (lo, hi))
    lines.append("];")
    lines.append("")

    out_path = Path(__file__).resolve().parent.parent / "src" / "combining_table.rs"
    out_path.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"combining ranges: {len(ranges)} (from {len(marks)} codepoints) -> {out_path}")


if __name__ == "__main__":
    main()
