#!/usr/bin/env python3
"""Generate `src/nfkd_table.rs` — the full NFKD (compatibility) decomposition
table goldenphonetic-core embeds so its `soundex` / `metaphone` match jellyfish's
`s.to_uppercase().nfkd()` byte-for-byte WITHOUT a `unicode-normalization` runtime
dep. Every non-Hangul codepoint whose NFKD differs from itself is emitted as a
`(u32, &str)` pair, sorted by source codepoint (binary-searched at runtime).
Hangul syllables are decomposed algorithmically in `nfkd.rs`, so they are skipped
here. Source of truth: Python `unicodedata` (Unicode 15.0.0, == CPython 3.12).

Regenerate:
    uv run --no-project --python 3.12 python \
        packages/rust/extensions/goldenphonetic-core/scripts/gen_nfkd_table.py
"""
from __future__ import annotations

import unicodedata
from pathlib import Path

HANGUL_LO, HANGUL_HI = 0xAC00, 0xD7A3

QUOTE = '"'
BACKSLASH = chr(92)


def esc(s: str) -> str:
    out = []
    for c in s:
        o = ord(c)
        if 0x20 <= o < 0x7F and c not in (QUOTE, BACKSLASH):
            out.append(c)
        else:
            out.append("\\u{%x}" % o)
    return "".join(out)


def main() -> None:
    entries = []
    for cp in range(0, 0x110000):
        if HANGUL_LO <= cp <= HANGUL_HI:
            continue  # algorithmic in nfkd.rs
        ch = chr(cp)
        d = unicodedata.normalize("NFKD", ch)
        if d != ch:
            entries.append((cp, d))

    lines = [
        "// AUTO-GENERATED by scripts/gen_nfkd_table.py from Python unicodedata "
        "(Unicode 15.0.0).",
        "// Full NFKD (compatibility) decomposition for every non-Hangul codepoint whose",
        "// decomposition differs from itself. Hangul syllables are decomposed algorithmically",
        "// in `nfkd.rs`. Sorted by source codepoint for binary search. DO NOT EDIT BY HAND.",
        "",
        "/// (source codepoint, its full NFKD decomposition), sorted ascending by codepoint.",
        "pub(crate) static NFKD: &[(u32, &str)] = &[",
    ]
    for cp, d in entries:
        lines.append('    (0x%X, "%s"),' % (cp, esc(d)))
    lines.append("];")
    lines.append("")

    out_path = Path(__file__).resolve().parent.parent / "src" / "nfkd_table.rs"
    out_path.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"entries: {len(entries)} -> {out_path}")


if __name__ == "__main__":
    main()
