"""FastDC-style minimal-cover derivation of denial constraints from evidence.

An *evidence map* is ``{mask: count}`` where ``mask`` (one u64) is the set of
predicates a single element (a row for Pass 1, an ordered pair for Pass 2)
satisfies, and ``count`` is how many elements share that exact mask.

A **denial constraint** (DC) is a predicate set ``X`` (a bitmask over predicate
indices) whose conjunction is (almost) never satisfied: the number of elements
whose mask is a superset of ``X`` is ``<= eps * total``. We derive the MINIMAL,
non-redundant such ``X`` s.

This is the pure-Python correctness / parity ORACLE. A Rust kernel replaces it
for speed in a later task and must reproduce these masks; the complement
convention in :func:`_complement` is load-bearing for that port.
"""
from __future__ import annotations

from itertools import combinations

from goldencheck.denial.constants import MAX_CONSTRAINTS, MAX_REPORT_ARITY

__all__ = ["discover", "rank", "_complement"]


def _complement(mask: int, n_predicates: int) -> int:
    """Bit-complement of ``mask`` bounded to ``n_predicates`` low bits.

    The naive ``~mask`` sets phantom high bits above ``n_predicates`` (Python
    ints are unbounded / two's-complement negative), which would corrupt any
    reasoning over the predicate space. Always bound: ``(~mask) & ((1<<p)-1)``.
    """
    return (~mask) & ((1 << n_predicates) - 1)


def _satisfied_count(mask_x: int, evidence: dict[int, int]) -> int:
    """Number of elements whose mask is a superset of ``mask_x`` (X ⊆ mask)."""
    return sum(cnt for mask, cnt in evidence.items() if (mask & mask_x) == mask_x)


def discover(
    evidence: dict[int, int],
    n_predicates: int,
    total: int,
    eps: float,
    arity_bound: int = MAX_REPORT_ARITY,
) -> list[int]:
    """Return minimal DC bitmasks.

    ``total`` is the true element count (typically ``sum(evidence.values())``).
    A returned ``X`` (bitmask) is a DC iff ``satisfied_count(X) <= eps * total``,
    it is minimal (no proper subset is also a DC), and ``arity(X) <=
    arity_bound``.

    Candidates are generated by INCREASING size, so every DC found is minimal by
    construction: a candidate that is a superset of an already-found DC is
    pruned before its satisfied-count is even computed.
    """
    threshold = eps * total

    # Predicate bit indices that appear set in at least one evidence mask. Bits
    # that are always 0 can never be part of a satisfiable conjunction. (A
    # predicate that is NEVER satisfied is itself a trivial size-1 DC; we keep
    # it via the size-1 pass below for correctness, interestingness-filtering
    # is a later concern.)
    active = [b for b in range(n_predicates) if any((mask >> b) & 1 for mask in evidence)]

    found: list[int] = []
    for size in range(1, arity_bound + 1):
        for combo in combinations(active, size):
            xmask = 0
            for b in combo:
                xmask |= 1 << b
            # Minimality prune: skip any superset of a known DC.
            if any((f & xmask) == f for f in found):
                continue
            if _satisfied_count(xmask, evidence) <= threshold:
                found.append(xmask)
    return found


def _arity(mask: int) -> int:
    return bin(mask).count("1")


def rank(
    dcs: list[int],
    evidence: dict[int, int],
    total: int,
    max_constraints: int = MAX_CONSTRAINTS,
) -> list[int]:
    """Rank DCs by interestingness = support * succinctness, return top-N.

    ``support(X) = 1 - satisfied_count(X) / total`` (how strongly the constraint
    holds); ``succinctness = 1 / arity(X)`` (fewer predicates = more
    interesting). Sort descending, cap at ``max_constraints``. Deterministic
    tie-break by ``(arity, mask)``.
    """
    def key(x: int):
        support = 1.0 - (_satisfied_count(x, evidence) / total if total else 0.0)
        succinctness = 1.0 / _arity(x) if x else 0.0
        interestingness = support * succinctness
        # Descending interestingness; ascending (arity, mask) tie-break.
        return (-interestingness, _arity(x), x)

    return sorted(dcs, key=key)[:max_constraints]
