#!/usr/bin/env python3
"""Export a goldenmatch graph to the `graph-layout` edge-list format.

The `graph-layout` crate reads `a b [weight]` per line (whitespace/TSV, `#`
comments). This script turns real goldenmatch output into that format so the
visualizer lays out *actual resolved entities*, not a synthetic toy:

  # from a persistent identity graph (.goldenmatch/identity.db) -- the durable
  # resolved-entity output; edges are the evidence_edges between source records:
  python export_graph_layout.py from-identity .goldenmatch/identity.db -o edges.tsv

  # from any scored-pair CSV (e.g. an export of the dedupe pair scores):
  python export_graph_layout.py from-pairs pairs.csv --a id_a --b id_b --score score -o edges.tsv

  # then:
  ./target/release/graph-layout --input edges.tsv --out frames

Stdlib only (sqlite3 + csv) so it runs anywhere goldenmatch produced the data,
without importing goldenmatch itself.
"""
from __future__ import annotations

import argparse
import csv
import sqlite3
import sys
from pathlib import Path


def _sanitize(token: str) -> str:
    """Edge-list tokens are whitespace-delimited; record ids shouldn't contain
    whitespace, but coerce to be safe (the crate interns arbitrary strings)."""
    return "_".join(str(token).split())


def _write(edges: list[tuple[str, str, float]], out: Path) -> int:
    written = 0
    with out.open("w", encoding="utf-8") as f:
        f.write("# a\tb\tweight  (generated by export_graph_layout.py)\n")
        for a, b, w in edges:
            a, b = _sanitize(a), _sanitize(b)
            if a == b:
                continue
            f.write(f"{a}\t{b}\t{w:g}\n")
            written += 1
    return written


def from_identity(args: argparse.Namespace) -> int:
    """Read `evidence_edges` (record_a_id, record_b_id, score) from a goldenmatch
    identity SQLite db. Each edge links two source records that were resolved into
    the same entity; connected components ARE the resolved entities."""
    db = Path(args.db)
    if not db.exists():
        print(f"no such db: {db}", file=sys.stderr)
        return 2
    con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    try:
        # Be tolerant of schema drift: confirm the table + columns exist.
        cols = {r[1] for r in con.execute("PRAGMA table_info(evidence_edges)")}
        if not {"record_a_id", "record_b_id"} <= cols:
            print(
                "evidence_edges missing record_a_id/record_b_id "
                f"(found: {sorted(cols)})",
                file=sys.stderr,
            )
            return 2
        has_score = "score" in cols
        has_run = "run_name" in cols
        sel = "record_a_id, record_b_id" + (", score" if has_score else "")
        sql = f"SELECT {sel} FROM evidence_edges"
        params: tuple = ()
        if args.run and has_run:
            sql += " WHERE run_name = ?"
            params = (args.run,)
        edges: list[tuple[str, str, float]] = []
        for r in con.execute(sql, params):
            score = float(r["score"]) if has_score and r["score"] is not None else 1.0
            if score < args.min_score:
                continue
            edges.append((r["record_a_id"], r["record_b_id"], score))
    finally:
        con.close()
    n = _write(edges, Path(args.out))
    print(f"wrote {n} edges -> {args.out}")
    return 0


def from_pairs(args: argparse.Namespace) -> int:
    """Read a scored-pair CSV (`a, b[, score]`) into the edge list. Works for any
    exported pair source -- dedupe scored pairs, a labeled training set, etc."""
    src = Path(args.csv)
    if not src.exists():
        print(f"no such csv: {src}", file=sys.stderr)
        return 2
    edges: list[tuple[str, str, float]] = []
    with src.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None or args.a not in reader.fieldnames or args.b not in reader.fieldnames:
            print(
                f"csv must have columns {args.a!r} and {args.b!r} "
                f"(found: {reader.fieldnames})",
                file=sys.stderr,
            )
            return 2
        for row in reader:
            try:
                w = float(row[args.score]) if args.score and row.get(args.score) else 1.0
            except (TypeError, ValueError):
                w = 1.0
            if w < args.min_score:
                continue
            edges.append((row[args.a], row[args.b], w))
    n = _write(edges, Path(args.out))
    print(f"wrote {n} edges -> {args.out}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    pi = sub.add_parser("from-identity", help="export from a goldenmatch identity SQLite db")
    pi.add_argument("db", help="path to identity.db")
    pi.add_argument("-o", "--out", default="edges.tsv")
    pi.add_argument("--run", default=None, help="filter to one run_name")
    pi.add_argument("--min-score", type=float, default=0.0)
    pi.set_defaults(func=from_identity)

    pp = sub.add_parser("from-pairs", help="export from a scored-pair CSV")
    pp.add_argument("csv", help="path to pairs csv")
    pp.add_argument("-o", "--out", default="edges.tsv")
    pp.add_argument("--a", default="a", help="column for the first record id")
    pp.add_argument("--b", default="b", help="column for the second record id")
    pp.add_argument("--score", default="score", help="column for the edge weight (optional)")
    pp.add_argument("--min-score", type=float, default=0.0)
    pp.set_defaults(func=from_pairs)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
