/**
 * #1317 acceptance parity — TS `autoConfigureRows(...).blocking` vs Python
 * `build_blocking(...)` on the strong-identifier blocking union.
 *
 * The fixture `blocking_union_vectors.json` is the Python oracle, generated by
 * running `build_blocking(profile_columns(df), df)` directly (isolating the
 * union decision from controller-iteration noise). It carries two cases:
 *   - `union_strong_id_multisource`: null-sparse multi-source strong-id data
 *     where Python emits the #1207 UNION (one pass per strong id + name+geo).
 *     Before 2b, TS silently emitted a name-only fallback here and lost recall —
 *     the exact #1317 gap. TS must now emit the SAME union.
 *   - `mixed_blocking_name_fallback`: bare `first`/`last` (classify_by_name →
 *     None) where Python emits the name fallback, NOT a union. TS must NOT
 *     over-fire the union here (the regression the 2a→2b classifyByName fix
 *     guards).
 *
 * Comparison is on the union-determining structure: strategy + the pass set
 * ({fields, transforms}, order-independent) + the primary key. `maxBlockSize` /
 * `skipOversized` are engine-populated defaults (stripped, mirroring
 * `controller-stoppoint`'s `normalizeConfig`).
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, it, expect } from "vitest";

import { autoConfigureRows } from "../../src/core/autoconfig.js";
import type { Row } from "../../src/core/types.js";

interface PassLike {
  fields: string[];
  transforms: string[];
}
interface Case {
  name: string;
  input_rows: Row[];
  expected_blocking: {
    strategy: string;
    keys: PassLike[];
    passes: PassLike[];
  };
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const cases = JSON.parse(
  readFileSync(
    resolve(__dirname, "fixtures/blocking-union/blocking_union_vectors.json"),
    "utf8",
  ),
) as Case[];

const passKey = (p: PassLike): string =>
  `${p.fields.join(",")}|${p.transforms.join(",")}`;
const passSet = (ps: PassLike[]): string[] => ps.map(passKey).sort();

describe("blocking union parity (#1317)", () => {
  it("fixture carries both the union-firing and the name-fallback cases", () => {
    expect(cases.map((c) => c.name).sort()).toEqual([
      "mixed_blocking_name_fallback",
      "union_strong_id_multisource",
    ]);
  });

  for (const c of cases) {
    it(`${c.name}: TS blocking matches Python`, () => {
      const config = autoConfigureRows(c.input_rows);
      const b = config.blocking;
      expect(b).toBeDefined();
      if (!b) return;
      const got: PassLike[] = (b.passes ?? []).map((p) => ({
        fields: [...p.fields],
        transforms: [...p.transforms],
      }));
      const gotKeys: PassLike[] = (b.keys ?? []).map((k) => ({
        fields: [...k.fields],
        transforms: [...k.transforms],
      }));

      expect(b.strategy).toEqual(c.expected_blocking.strategy);
      expect(passSet(got)).toEqual(passSet(c.expected_blocking.passes));
      // primary key: same field set + transforms as Python's chosen primary.
      expect(passSet(gotKeys)).toEqual(passSet(c.expected_blocking.keys));
    });
  }
});
