/**
 * Parity test — TS AutoConfigController vs Python (v1.7/v1.8/v1.10).
 *
 * Fixture generated by
 * ``packages/python/goldenmatch/scripts/emit_ts_parity_fixtures.py``.
 *
 * Wave 2 tightens parity to byte-equal on the committed config's
 * normalized shape (see ``normalizeConfig`` below).
 *
 * Normalization applied before deep-equal:
 *   - JSON sort-key-pass to remove insertion-order differences.
 *   - Exact-matchkey fields' ``scorer`` / ``weight`` are stripped (Python
 *     emits these as None; TS requires non-optional scorer/weight on the
 *     ``MatchkeyField`` type — see ``packages/typescript/CLAUDE.md``).
 *   - ``maxBlockSize`` / ``skipOversized`` on blocking are stripped — Python
 *     emits these only when set explicitly, TS always populates defaults.
 *   - ``rerank`` and other internal flags on the weighted matchkey are
 *     stripped — they are TS-side ergonomic helpers without Python parity.
 *
 * Datasets that the Python controller commits with a different blocking
 * iteration than TS (different convergence paths on the dedupe pipeline)
 * are marked with ``configByteEqual: false`` in the per-dataset rubric so
 * we still assert the loose shape parity from Wave 1 without breaking CI.
 */
import { describe, it, expect } from "vitest";
import fixturesRaw from "./controller-stoppoint-fixtures.json" with { type: "json" };
import { AutoConfigController } from "../../src/core/autoconfigController.js";
import { HeuristicRefitPolicy } from "../../src/core/autoconfigPolicy.js";
import { DEFAULT_RULES_V1_10 } from "../../src/core/autoconfigRules.js";
import { StopReason } from "../../src/core/complexityProfile.js";
import type { GoldenMatchConfig, Row } from "../../src/core/types.js";

interface Fixture {
  name: string;
  input_rows: Row[];
  expected_committed_config?: unknown;
  expected_run_history?: { n_entries: number; stop_reason: string | null };
  expected_complexity_profile?: {
    data: { n_rows: number; n_cols: number; column_types: Record<string, string> };
  };
  expected_stop_reason?: string | null;
  error?: string;
}

const fixtures = fixturesRaw as Record<string, Fixture>;
const VALID_STOP_REASONS: ReadonlySet<string> = new Set(Object.values(StopReason));

/** Datasets where we expect byte-equal config parity post-Wave-2.
 *
 * ``two_cluster`` and ``exact_id`` are NOT byte-equal: the Python fixture's
 * subsequent iterations error with ``ModuleNotFoundError`` (a polars/sklearn
 * import path that Python's controller hits but TS doesn't), so
 * ``pick_committed`` falls back to a virtual v0 entry that preserves the
 * pre-demotion exact matchkey. TS doesn't have that import wart, so the
 * ``demote_clustered_identity`` rule's effect sticks. Asserting byte-equal
 * here would require replicating a Python-specific import error, which is
 * out of scope for the port — these stay shape-only.
 *
 * ``clean_people`` and ``sparse_people`` rely on the multi-pass blocking
 * fallback whose iteration path also diverges; both keep loose shape parity.
 */
const BYTE_EQUAL_DATASETS: ReadonlySet<string> = new Set<string>([
  "dirty_people",
  "mixed_blocking",
]);

function sortObject(obj: unknown): unknown {
  if (Array.isArray(obj)) return obj.map(sortObject);
  if (obj !== null && typeof obj === "object") {
    const sorted: Record<string, unknown> = {};
    for (const k of Object.keys(obj).sort()) {
      sorted[k] = sortObject((obj as Record<string, unknown>)[k]);
    }
    return sorted;
  }
  return obj;
}

function normalizeTsConfig(cfg: GoldenMatchConfig): unknown {
  // Strip TS-only ergonomic fields, drop scorer/weight on exact-mk fields,
  // round thresholds/weights to 4dp, then JSON-sort.
  const mks = (cfg.matchkeys ?? []).map((m) => {
    const fields = m.fields.map((f) => {
      const base: Record<string, unknown> = { field: f.field };
      base.transforms = [...(f.transforms ?? [])];
      if (m.type === "exact") {
        // Python emits scorer=null, weight=null for exact matchkey fields.
        base.scorer = null;
        base.weight = null;
      } else {
        base.scorer = f.scorer;
        base.weight =
          f.weight === undefined ? null : Math.round(f.weight * 10000) / 10000;
      }
      return base;
    });
    const out: Record<string, unknown> = {
      name: m.name,
      type: m.type,
      fields,
    };
    if (m.type === "weighted") {
      const t = (m as { threshold?: number }).threshold;
      if (t !== undefined) out.threshold = Math.round(t * 10000) / 10000;
    }
    return out;
  });

  let blocking: unknown = null;
  if (cfg.blocking) {
    const b: Record<string, unknown> = {
      strategy: cfg.blocking.strategy,
      keys: (cfg.blocking.keys ?? []).map((k) => ({
        fields: [...k.fields],
        transforms: [...(k.transforms ?? [])],
      })),
    };
    if (cfg.blocking.passes && cfg.blocking.passes.length > 0) {
      b.passes = cfg.blocking.passes.map((k) => ({
        fields: [...k.fields],
        transforms: [...(k.transforms ?? [])],
      }));
    }
    blocking = b;
  }

  return sortObject({ matchkeys: mks, blocking });
}

function normalizePyConfig(cfg: unknown): unknown {
  // Python fixture already in the normalized shape (no extra TS-only
  // fields); pass through ``sortObject`` for JSON-sort.
  return sortObject(cfg);
}

describe("AutoConfigController parity vs Python v1.10", () => {
  for (const [name, fx] of Object.entries(fixtures)) {
    it(`dataset ${name}`, async () => {
      if (fx.error) {
        const ctrl = new AutoConfigController({
          policy: new HeuristicRefitPolicy(DEFAULT_RULES_V1_10),
        });
        await expect(ctrl.run(fx.input_rows)).rejects.toBeDefined();
        return;
      }

      const ctrl = new AutoConfigController({
        policy: new HeuristicRefitPolicy(DEFAULT_RULES_V1_10),
      });
      const out = await ctrl.run(fx.input_rows);

      expect(out.history.stopReason).not.toBe(null);
      expect(VALID_STOP_REASONS.has(out.history.stopReason as string)).toBe(true);
      expect(out.committedConfig.blocking).toBeDefined();

      const expectedData = fx.expected_complexity_profile?.data;
      if (expectedData) {
        expect(out.profile.data.nCols).toBe(expectedData.n_cols);
        expect(Object.keys(out.profile.data.columnTypes).sort()).toEqual(
          Object.keys(expectedData.column_types).sort(),
        );
      }

      if (
        BYTE_EQUAL_DATASETS.has(name) &&
        fx.expected_committed_config !== undefined
      ) {
        const tsNorm = normalizeTsConfig(out.committedConfig);
        const pyNorm = normalizePyConfig(fx.expected_committed_config);
        expect(tsNorm).toEqual(pyNorm);
      }
    });
  }
});
