/**
 * domain-extractors.parity.test.ts — gap 3 (software / biblio extractors).
 *
 * Fixtures generated by
 * ``packages/python/goldenmatch/scripts/emit_v2_parity_fixtures.py``
 * (section ``domain``). Asserts the TS ports of extract_software_features /
 * extract_biblio_features byte-match Python's regex-based extraction across
 * product/software/biblio inputs (including DOI/ISBN-style tokens and the
 * empty-string edge case).
 */
import { describe, it, expect } from "vitest";
import fixturesRaw from "./v2-fixtures.json" with { type: "json" };
import {
  extractSoftwareFeatures,
  extractBiblioFeatures,
} from "../../src/core/domain.js";

interface SwExpected {
  name_normalized: string | null;
  version: string | null;
  edition: string | null;
  platform: string | null;
  part_number: string | null;
  is_upgrade: boolean;
  confidence: number;
}
interface BiblioExpected {
  year: string | null;
  doi: string | null;
  title_key: string | null;
}

const domain = (
  fixturesRaw as {
    domain: {
      software: { input: string; expected: SwExpected }[];
      biblio: { input: string; expected: BiblioExpected }[];
    };
  }
).domain;

describe("software feature extraction parity vs Python", () => {
  for (const c of domain.software) {
    it(`software: ${JSON.stringify(c.input.slice(0, 40))}`, () => {
      const r = extractSoftwareFeatures(c.input);
      expect(r.nameNormalized).toBe(c.expected.name_normalized);
      expect(r.version).toBe(c.expected.version);
      expect(r.edition).toBe(c.expected.edition);
      expect(r.platform).toBe(c.expected.platform);
      expect(r.partNumber).toBe(c.expected.part_number);
      expect(r.isUpgrade).toBe(c.expected.is_upgrade);
      expect(r.confidence).toBeCloseTo(c.expected.confidence, 6);
    });
  }
});

describe("biblio feature extraction parity vs Python", () => {
  for (const c of domain.biblio) {
    it(`biblio: ${JSON.stringify(c.input.slice(0, 40))}`, () => {
      const r = extractBiblioFeatures(c.input);
      expect(r.year).toBe(c.expected.year);
      expect(r.doi).toBe(c.expected.doi);
      expect(r.titleKey).toBe(c.expected.title_key);
    });
  }
});
