/**
 * heavy-algorithms.parity.test.ts — broadened parity harness.
 *
 * Cross-language goldens for heavy algorithms that previously lacked them:
 * blocker (static), clustering (Union-Find + confidence/quality), and
 * golden/survivorship (mergeField). Fixtures generated by
 * ``packages/python/goldenmatch/scripts/emit_v2_parity_fixtures.py`` (sections
 * ``blocker`` / ``clustering`` / ``golden``).
 *
 * (Discrete-EM golden coverage lives in probabilistic.parity.test.ts.)
 */
import { describe, it, expect } from "vitest";
import fixturesRaw from "./v2-fixtures.json" with { type: "json" };
import { buildBlocks } from "../../src/core/blocker.js";
import { buildClusters } from "../../src/core/cluster.js";
import { mergeField } from "../../src/core/golden.js";
import type {
  Row,
  BlockingConfig,
  GoldenFieldRule,
} from "../../src/core/types.js";

// --- Blocker --------------------------------------------------------------
interface BlockerFixture {
  input_rows: Row[];
  blocking: { strategy: string; keys: { fields: string[]; transforms: string[] }[] };
  expected_blocks: { key: string; row_ids: number[] }[];
}
const blockerFx = (fixturesRaw as { blocker: BlockerFixture }).blocker;

describe("blocker parity vs Python (static blocking)", () => {
  it("produces the same blocks (key -> sorted row_ids)", () => {
    const config: BlockingConfig = {
      strategy: "static",
      keys: blockerFx.blocking.keys.map((k) => ({
        fields: k.fields,
        transforms: k.transforms,
      })),
      maxBlockSize: 1000,
      skipOversized: false,
    };
    const blocks = buildBlocks(blockerFx.input_rows, config);
    const got = blocks
      .map((b) => ({
        key: b.blockKey,
        row_ids: b.rows
          .map((r) => r["__row_id__"] as number)
          .sort((a, c) => a - c),
      }))
      .sort((a, b) => a.key.localeCompare(b.key));
    const expected = [...blockerFx.expected_blocks].sort((a, b) =>
      a.key.localeCompare(b.key),
    );
    expect(got).toEqual(expected);
  });
});

// --- Clustering -----------------------------------------------------------
interface ClusteringFixture {
  input_pairs: { a: number; b: number; score: number }[];
  expected_clusters: {
    members: number[];
    size: number;
    oversized: boolean;
    confidence: number;
    cluster_quality: string | null;
  }[];
}
const clusterFx = (fixturesRaw as { clustering: ClusteringFixture }).clustering;

describe("clustering parity vs Python (Union-Find + confidence)", () => {
  it("produces the same multi-member clusters", () => {
    const pairs = clusterFx.input_pairs.map(
      (p) => [p.a, p.b, p.score] as [number, number, number],
    );
    // Python build_clusters derives members from the pairs only.
    const idSet = new Set<number>();
    for (const p of pairs) {
      idSet.add(p[0]);
      idSet.add(p[1]);
    }
    const clusters = buildClusters(pairs, [...idSet]);
    const got = [...clusters.values()]
      .filter((c) => c.size >= 2)
      .map((c) => ({
        members: [...c.members].sort((a, b) => a - b),
        size: c.size,
        oversized: c.oversized,
        confidence: Math.round(c.confidence * 10000) / 10000,
        cluster_quality: c.clusterQuality,
      }))
      .sort((a, b) => (a.members[0] ?? 0) - (b.members[0] ?? 0));
    const expected = [...clusterFx.expected_clusters].sort(
      (a, b) => (a.members[0] ?? 0) - (b.members[0] ?? 0),
    );
    expect(got.length).toBe(expected.length);
    for (let i = 0; i < expected.length; i++) {
      expect(got[i]!.members).toEqual(expected[i]!.members);
      expect(got[i]!.size).toBe(expected[i]!.size);
      expect(got[i]!.oversized).toBe(expected[i]!.oversized);
      expect(got[i]!.cluster_quality).toBe(expected[i]!.cluster_quality);
      expect(got[i]!.confidence).toBeCloseTo(expected[i]!.confidence, 3);
    }
  });
});

// --- Golden / survivorship ------------------------------------------------
interface GoldenFixture {
  cases: {
    id: string;
    strategy: string;
    values: unknown[];
    expected: { value: unknown; confidence: number; source_index: number | null };
  }[];
}
const goldenFx = (fixturesRaw as { golden: GoldenFixture }).golden;

describe("golden/survivorship parity vs Python (mergeField)", () => {
  for (const c of goldenFx.cases) {
    it(`golden: ${c.id} (${c.strategy})`, () => {
      const rule: GoldenFieldRule = { strategy: c.strategy as GoldenFieldRule["strategy"] };
      const r = mergeField(c.values, rule);
      expect(r.value).toEqual(c.expected.value);
      expect(r.confidence).toBeCloseTo(c.expected.confidence, 6);
      expect(r.sourceIndex).toBe(c.expected.source_index);
    });
  }
});
