/**
 * indicators.parity.test.ts — TS indicators vs Python v1.10.
 *
 * Fixture generated by
 * ``packages/python/goldenmatch/scripts/emit_ts_parity_fixtures.py``
 * with ``--indicators-out``.
 *
 * Compares the 5 indicator outputs across 8 curated datasets:
 *   - column_priors: identity_score / corruption_score per column (4dp)
 *   - sparsity: is_sparse + estimated_n_true_pairs (exact)
 *   - corruption_per_column: per-column scalar (4dp)
 *   - full_pop_hits: per-column collision pairs (exact, allow null)
 *   - cross_blocking_overlap: pairwise Jaccard on co-blocked pairs (4dp)
 *
 * NOTE: token_sort_ratio similarity differs between TS (pure-JS
 * Levenshtein on whitespace-sorted tokens) and Python (rapidfuzz). The
 * collision-signal indicator therefore is exercised by the unit suite
 * rather than asserted here.
 */
import { describe, it, expect } from "vitest";
import fixturesRaw from "./indicators-fixtures.json" with { type: "json" };
import {
  computeColumnPriors,
  estimateSparseMatchSignal,
  computeCorruptionScore,
  estimateFullPopHits,
  computeCrossBlockingOverlap,
} from "../../src/core/indicators.js";
import type { Row } from "../../src/core/types.js";

interface Fixture {
  name: string;
  input_rows: Row[];
  expected_indicators: {
    column_priors: Record<string, { identity_score: number; corruption_score: number }>;
    sparsity: { is_sparse: boolean; estimated_n_true_pairs: number };
    corruption_per_column: Record<string, number>;
    full_pop_hits: Record<string, number | null>;
    cross_blocking_overlap: Record<string, number | null>;
  };
}

const fixtures = fixturesRaw as Record<string, Fixture>;

function round4(x: number): number {
  return Math.round(x * 10000) / 10000;
}

describe("indicators parity vs Python v1.10", () => {
  for (const [name, fx] of Object.entries(fixtures)) {
    it(`dataset ${name}`, () => {
      const rows = fx.input_rows;

      // ---- column_priors ----
      const tsPriors = computeColumnPriors(rows);
      for (const [col, expected] of Object.entries(fx.expected_indicators.column_priors)) {
        const got = tsPriors[col];
        expect(got, `column_priors missing for '${col}'`).toBeDefined();
        expect(round4(got!.identityScore)).toBeCloseTo(expected.identity_score, 3);
        expect(round4(got!.corruptionScore)).toBeCloseTo(expected.corruption_score, 3);
      }

      // ---- sparsity ----
      // Mirror generator's exact_columns selection logic to keep parity.
      const candidates = Object.keys(rows[0] ?? {}).filter(
        (c) => !c.startsWith("__"),
      );
      const exactCandidates = candidates
        .filter(
          (c) => c.toLowerCase().includes("email") || c.toLowerCase().includes("id"),
        )
        .slice(0, 1);
      const sv = estimateSparseMatchSignal(rows, {
        exactColumns: exactCandidates.length > 0 ? exactCandidates : [],
      });
      expect(sv.isSparse).toBe(fx.expected_indicators.sparsity.is_sparse);
      expect(sv.estimatedNTruePairs).toBe(
        fx.expected_indicators.sparsity.estimated_n_true_pairs,
      );

      // ---- corruption_per_column ----
      for (const [col, expected] of Object.entries(
        fx.expected_indicators.corruption_per_column,
      )) {
        const got = computeCorruptionScore(rows, col);
        expect(round4(got)).toBeCloseTo(expected, 3);
      }

      // ---- full_pop_hits ----
      for (const [col, expected] of Object.entries(
        fx.expected_indicators.full_pop_hits,
      )) {
        const got = estimateFullPopHits(rows, col);
        if (expected === null) {
          expect(got).toBeNull();
        } else {
          expect(got).toBe(expected);
        }
      }

      // ---- cross_blocking_overlap ----
      for (const [pair, expected] of Object.entries(
        fx.expected_indicators.cross_blocking_overlap,
      )) {
        const [a, b] = pair.split("|");
        const got = computeCrossBlockingOverlap(rows, a!, b!);
        if (expected === null) {
          expect(got).toBeNull();
        } else {
          expect(got).not.toBeNull();
          expect(round4(got!)).toBeCloseTo(expected, 3);
        }
      }
    });
  }
});
