/**
 * memory_json.parity.test.ts -- cross-language JSON wire-format parity.
 *
 * Loads the shared `memory_corrections.json` fixture (generated by Python
 * `tests/parity/memory/gen_memory_fixtures.py`), runs each entry through
 * `correctionFromJSON` -> `correctionToJSON`, and asserts:
 *
 *   1. Snake_case keys are preserved (`id_a`, `field_hash`, etc.) so the JSON
 *      remains a Python-compatible wire format.
 *   2. Trust values stay numerically `1.0` / `0.5` (not coerced to integers).
 *   3. The round-tripped object is structurally equal to the source, with the
 *      sole expected normalization being JS-side number formatting (e.g.
 *      `1.0` -> `1`, `0.40` -> `0.4`). Numeric equality is asserted; literal
 *      byte equality is asserted on the non-numeric fields only.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  correctionFromJSON,
  correctionToJSON,
  type CorrectionJSON,
} from "../../src/core/memory/types.js";

const FIXTURE_PATH = join(
  __dirname,
  "fixtures",
  "memory_corrections.json",
);

describe("memory JSON parity", () => {
  const raw = readFileSync(FIXTURE_PATH, "utf-8");
  const source = JSON.parse(raw) as CorrectionJSON[];

  it("fixture has 12 corrections", () => {
    expect(source).toHaveLength(12);
  });

  it("snake_case keys are preserved (no camelCase leakage)", () => {
    for (const entry of source) {
      expect(entry).toHaveProperty("id_a");
      expect(entry).toHaveProperty("id_b");
      expect(entry).toHaveProperty("field_hash");
      expect(entry).toHaveProperty("record_hash");
      expect(entry).toHaveProperty("original_score");
      expect(entry).toHaveProperty("matchkey_name");
      expect(entry).toHaveProperty("created_at");
      // Inverse: camelCase keys must NOT appear on the wire.
      expect(entry).not.toHaveProperty("idA");
      expect(entry).not.toHaveProperty("fieldHash");
      expect(entry).not.toHaveProperty("createdAt");
    }
  });

  it("trust values stay 1.0 / 0.5 numerically", () => {
    const trustValues = new Set(source.map((c) => c.trust));
    expect(trustValues.has(1.0)).toBe(true);
    expect(trustValues.has(0.5)).toBe(true);
    for (const c of source) {
      expect([1.0, 0.5]).toContain(c.trust);
      // Specifically guard against integer coercion: 1.0 must equal 1.0 as a
      // Number, not be silently truncated. JS treats 1 === 1.0 so the real
      // failure mode is loss of fractional precision -- assert >= 0.5 catches
      // anything that landed at 0 by accident.
      expect(c.trust).toBeGreaterThanOrEqual(0.5);
      expect(c.trust).toBeLessThanOrEqual(1.0);
    }
  });

  it("each correction round-trips via correctionFromJSON -> correctionToJSON", () => {
    for (const entry of source) {
      const c = correctionFromJSON(entry);
      const back = correctionToJSON(c);
      // Structural equality on every non-Date field.
      expect(back.id).toBe(entry.id);
      expect(back.id_a).toBe(entry.id_a);
      expect(back.id_b).toBe(entry.id_b);
      expect(back.decision).toBe(entry.decision);
      expect(back.source).toBe(entry.source);
      expect(back.trust).toBe(entry.trust);
      expect(back.field_hash).toBe(entry.field_hash);
      expect(back.record_hash).toBe(entry.record_hash);
      expect(back.original_score).toBe(entry.original_score);
      expect(back.matchkey_name).toBe(entry.matchkey_name);
      expect(back.reason).toBe(entry.reason);
      expect(back.dataset).toBe(entry.dataset);
      // created_at: re-serialization may add/strip trailing `.000` depending
      // on Python's ISO output, but the parsed Date must be identical.
      expect(new Date(back.created_at).getTime()).toBe(
        new Date(entry.created_at).getTime(),
      );
    }
  });

  it("Correction object preserves camelCase fields after parse", () => {
    const c = correctionFromJSON(source[0]!);
    expect(c.idA).toBe(0);
    expect(c.idB).toBe(1);
    expect(c.fieldHash).toBe(source[0]!.field_hash);
    expect(c.matchkeyName).toBe("identity");
    expect(c.createdAt).toBeInstanceOf(Date);
  });

  it("covers every CorrectionSource", () => {
    const sources = new Set(source.map((c) => c.source));
    expect(sources.has("steward")).toBe(true);
    expect(sources.has("boost")).toBe(true);
    expect(sources.has("unmerge")).toBe(true);
    expect(sources.has("agent")).toBe(true);
    expect(sources.has("llm")).toBe(true);
    expect(sources.has("api")).toBe(true);
  });

  it("covers both decisions and includes empty-hash + full-hash cases", () => {
    const decisions = new Set(source.map((c) => c.decision));
    expect(decisions.has("approve")).toBe(true);
    expect(decisions.has("reject")).toBe(true);

    const emptyHash = source.filter((c) => c.field_hash === "" && c.record_hash === "");
    expect(emptyHash.length).toBeGreaterThan(0);
    const fullHash = source.filter((c) => c.field_hash !== "" && c.record_hash !== "");
    expect(fullHash.length).toBeGreaterThan(0);
  });
});
