/**
 * planner.parity.test.ts — gap 4 (autoconfig v3 planner rules).
 *
 * Fixtures generated by
 * ``packages/python/goldenmatch/scripts/emit_v2_parity_fixtures.py``
 * (section ``planner``). Drives applyPlannerRules over DEFAULT_PLANNER_RULES
 * for the same (profile, runtime, n_rows, context) inputs Python evaluates and
 * asserts the full ExecutionPlan (backend, chunk_size, max_workers,
 * spill-threshold, clustering-strategy, rule_name) matches.
 *
 * Note: the Python goldens were generated with the ray auto-select env gate
 * OFF (default), so 50M+ inputs fall through to duckdb on BOTH sides — the
 * edge-safe TS port can never select ray. autoChunkSize is exercised by the
 * chunked / user_override_chunked cases (chunk_size values match exactly).
 */
import { describe, it, expect } from "vitest";
import fixturesRaw from "./v2-fixtures.json" with { type: "json" };
import { applyPlannerRules } from "../../src/core/autoconfigPlanner.js";
import { DEFAULT_PLANNER_RULES } from "../../src/core/autoconfigPlannerRules.js";
import { makeComplexityProfile, makeBlockingProfile } from "../../src/core/complexityProfile.js";
import { makeRuntimeProfile } from "../../src/core/runtimeProfile.js";

interface PlannerCase {
  name: string;
  input: {
    n_rows: number;
    pair_count: number;
    ram_gb: number;
    cpu_count: number;
    disk_gb: number;
    user_backend: string | null;
  };
  expected_plan: {
    backend: string;
    chunk_size: number | null;
    max_workers: number;
    pair_spill_threshold: string | null;
    clustering_strategy: string;
    rule_name: string | null;
  };
}

const cases = (fixturesRaw as { planner: PlannerCase[] }).planner;

describe("autoconfig v3 planner parity vs Python", () => {
  for (const c of cases) {
    it(`planner: ${c.name}`, () => {
      const profile = makeComplexityProfile({
        blocking: makeBlockingProfile({ totalComparisons: c.input.pair_count }),
      });
      const runtime = makeRuntimeProfile({
        availableRamGb: c.input.ram_gb,
        cpuCount: c.input.cpu_count,
        diskFreeGb: c.input.disk_gb,
      });
      const plan = applyPlannerRules(
        profile,
        runtime,
        c.input.n_rows,
        DEFAULT_PLANNER_RULES,
        { userBackend: c.input.user_backend },
      );
      expect(plan.backend).toBe(c.expected_plan.backend);
      expect(plan.chunkSize).toBe(c.expected_plan.chunk_size);
      expect(plan.maxWorkers).toBe(c.expected_plan.max_workers);
      expect(plan.pairSpillThreshold).toBe(c.expected_plan.pair_spill_threshold);
      expect(plan.clusteringStrategy).toBe(c.expected_plan.clustering_strategy);
      expect(plan.ruleName).toBe(c.expected_plan.rule_name);
    });
  }
});
