/**
 * probabilistic.parity.test.ts — TS Fellegi-Sunter (discrete + continuous EM)
 * vs Python ``goldenmatch/core/probabilistic.py``.
 *
 * Fixtures generated by
 * ``packages/python/goldenmatch/scripts/emit_v2_parity_fixtures.py``
 * (section ``probabilistic``).
 *
 * Determinism contract: every dataset is small enough that pair sampling
 * enumerates ALL pairs (no RNG divergence between Python's random.Random and
 * the TS xorshift), so the comparison/score matrices are identical. Scorers
 * are limited to jaro_winkler / exact, which are 4dp-parity between rapidfuzz
 * and the pure-JS TS port (tests/parity/scorer-ground-truth.test.ts).
 *
 * Tolerance: EM probabilities/means/variances compared at 4dp; final pair
 * scores at 3dp (iterated EM accumulates last-digit float drift).
 */
import { describe, it, expect } from "vitest";
import fixturesRaw from "./v2-fixtures.json" with { type: "json" };
import {
  trainEM,
  scoreProbabilistic,
  trainEMContinuous,
  scoreProbabilisticContinuous,
} from "../../src/core/probabilistic.js";
import type { MatchkeyConfig, MatchkeyField, Row } from "../../src/core/types.js";

interface FixtureField {
  field: string;
  transforms: string[];
  scorer: string;
  weight: number;
  levels: number | null;
  partial_threshold: number | null;
}
interface FixtureMatchkey {
  name: string;
  type: string;
  fields: FixtureField[];
}
interface EMFixture {
  m_probs: Record<string, number[]>;
  u_probs: Record<string, number[]>;
  match_weights: Record<string, number[]>;
  proportion_matched: number;
  iterations: number;
  converged: boolean;
}
interface ContEMFixture {
  m_mean: Record<string, number>;
  m_var: Record<string, number>;
  u_mean: Record<string, number>;
  u_var: Record<string, number>;
  proportion_matched: number;
  iterations: number;
  converged: boolean;
}
interface PairFixture {
  a: number;
  b: number;
  score: number;
}
interface ProbCase {
  input_rows: Row[];
  matchkey: FixtureMatchkey;
  expected_em: EMFixture | ContEMFixture;
  expected_pairs: PairFixture[];
}

const fixtures = (fixturesRaw as { probabilistic: Record<string, ProbCase> })
  .probabilistic;

function toMatchkey(fx: FixtureMatchkey): MatchkeyConfig {
  const fields: MatchkeyField[] = fx.fields.map((f) => ({
    field: f.field,
    transforms: f.transforms,
    scorer: f.scorer,
    weight: f.weight,
    ...(f.levels !== null ? { levels: f.levels } : {}),
    ...(f.partial_threshold !== null ? { partialThreshold: f.partial_threshold } : {}),
  }));
  return {
    name: fx.name,
    type: "probabilistic",
    fields,
    emIterations: 20,
    convergenceThreshold: 0.001,
    linkThreshold: 0.0,
  };
}

function sortPairs(pairs: PairFixture[]): PairFixture[] {
  return [...pairs].sort((x, y) => x.a - y.a || x.b - y.b);
}

describe("probabilistic EM parity vs Python", () => {
  for (const key of ["discrete_2level", "discrete_3level"] as const) {
    it(`discrete EM: ${key}`, () => {
      const fx = fixtures[key]!;
      const mk = toMatchkey(fx.matchkey);
      const em = trainEM(fx.input_rows, mk, { seed: 42 });
      const expected = fx.expected_em as EMFixture;

      expect(em.converged).toBe(expected.converged);
      expect(em.iterations).toBe(expected.iterations);
      expect(em.proportionMatched).toBeCloseTo(expected.proportion_matched, 4);

      for (const f of mk.fields) {
        expect(em.m[f.field]!.length).toBe(expected.m_probs[f.field]!.length);
        for (let k = 0; k < expected.m_probs[f.field]!.length; k++) {
          expect(em.m[f.field]![k]!).toBeCloseTo(expected.m_probs[f.field]![k]!, 4);
          expect(em.u[f.field]![k]!).toBeCloseTo(expected.u_probs[f.field]![k]!, 4);
          expect(em.matchWeights[f.field]![k]!).toBeCloseTo(
            expected.match_weights[f.field]![k]!,
            4,
          );
        }
      }

      const got = sortPairs(
        scoreProbabilistic(fx.input_rows, mk, em, { threshold: 0.0 }).map((p) => ({
          a: p.idA,
          b: p.idB,
          score: p.score,
        })),
      );
      const exp = sortPairs(fx.expected_pairs);
      expect(got.length).toBe(exp.length);
      for (let i = 0; i < exp.length; i++) {
        expect(got[i]!.a).toBe(exp[i]!.a);
        expect(got[i]!.b).toBe(exp[i]!.b);
        expect(got[i]!.score).toBeCloseTo(exp[i]!.score, 3);
      }
    });
  }

  it("continuous EM: continuous_2field", () => {
    const fx = fixtures.continuous_2field!;
    const mk = toMatchkey(fx.matchkey);
    const em = trainEMContinuous(fx.input_rows, mk, { seed: 42 });
    const expected = fx.expected_em as ContEMFixture;

    expect(em.converged).toBe(expected.converged);
    expect(em.iterations).toBe(expected.iterations);
    expect(em.proportionMatched).toBeCloseTo(expected.proportion_matched, 4);

    for (const f of mk.fields) {
      expect(em.mMean[f.field]!).toBeCloseTo(expected.m_mean[f.field]!, 4);
      expect(em.mVar[f.field]!).toBeCloseTo(expected.m_var[f.field]!, 4);
      expect(em.uMean[f.field]!).toBeCloseTo(expected.u_mean[f.field]!, 4);
      expect(em.uVar[f.field]!).toBeCloseTo(expected.u_var[f.field]!, 4);
    }

    const got = sortPairs(
      scoreProbabilisticContinuous(fx.input_rows, mk, em, { threshold: 0.0 }).map(
        (p) => ({ a: p.idA, b: p.idB, score: p.score }),
      ),
    );
    const exp = sortPairs(fx.expected_pairs);
    expect(got.length).toBe(exp.length);
    for (let i = 0; i < exp.length; i++) {
      expect(got[i]!.a).toBe(exp[i]!.a);
      expect(got[i]!.b).toBe(exp[i]!.b);
      expect(got[i]!.score).toBeCloseTo(exp[i]!.score, 3);
    }
  });
});
