/**
 * Cross-language parity: the TS consume-side parsers vs Python. The fixture is
 * generated by `packages/python/goldenmatch/scripts/emit_semantic_parse_fixtures.py`.
 *
 * - cube / osi: the fixture holds canonical Python-emitted YAML for FULL models.
 *   The TS `emit(parse(yaml))` must reproduce it byte-for-byte — a round-trip that
 *   fails if the parser drops or misreads any field (dimensions/measures/meta;
 *   datasets/fields/metrics/version/custom_extensions).
 * - metricflow: `parseSemanticModels` is a lossy key extractor, so the TS parse
 *   must reproduce Python's `DeclaredKeySpec`s exactly.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

import { parseCubeModels, emitCubeYaml } from "../../src/core/semantic/cube.js";
import { parseOsiModels, emitOsiYaml } from "../../src/core/semantic/osi.js";
import { parseSemanticModels } from "../../src/core/semantic/metricflow.js";
import type { LoadedDoc } from "../../src/core/semantic/parseUtil.js";

interface YamlCase {
  name: string;
  yaml: string;
}
interface MfCase extends YamlCase {
  specs: Array<{
    model: string;
    key: string[];
    measures: string[];
    grain: string[] | null;
    foreign_keys: string[];
  }>;
}

const fixturePath = fileURLToPath(new URL("./fixtures/semantic/parse.json", import.meta.url));
const fixture = JSON.parse(readFileSync(fixturePath, "utf-8")) as {
  cube: YamlCase[];
  osi: YamlCase[];
  metricflow: MfCase[];
};

describe("semantic consume-side parsers — parity with Python", () => {
  describe("cube: emit(parse(yaml)) round-trips byte-for-byte", () => {
    for (const c of fixture.cube) {
      it(c.name, () => {
        const doc = parseYaml(c.yaml) as LoadedDoc;
        expect(emitCubeYaml(parseCubeModels(doc))).toBe(c.yaml);
      });
    }
  });

  describe("osi: emit(parse(yaml)) round-trips byte-for-byte", () => {
    for (const c of fixture.osi) {
      it(c.name, () => {
        const doc = parseYaml(c.yaml) as LoadedDoc;
        expect(emitOsiYaml(parseOsiModels(doc))).toBe(c.yaml);
      });
    }
  });

  describe("metricflow: parseSemanticModels matches Python DeclaredKeySpec", () => {
    for (const c of fixture.metricflow) {
      it(c.name, () => {
        const doc = parseYaml(c.yaml) as LoadedDoc;
        const specs = parseSemanticModels(doc).map((s) => ({
          model: s.model,
          key: s.key,
          measures: s.measures,
          grain: s.grain,
          foreign_keys: s.foreignKeys,
        }));
        expect(specs).toEqual(c.specs);
      });
    }
  });
});
