/**
 * Cross-language parity: the TS semantic-model certifier (consume side, wedge A)
 * vs Python `certify_semantic_model`. The fixture is generated by
 * `packages/python/goldenmatch/scripts/emit_semantic_certify_fixtures.py` from the
 * REAL Python certifier over MetricFlow / Cube / OSI models + frames (several
 * models are the emitters' own output, so parse(emit(...)) round-trips). The TS
 * `certifySemanticModel` must produce the same per-key structural certification.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { certifySemanticModel } from "../../src/core/semantic/certify.js";
import type { SemanticFrames } from "../../src/core/semantic/frame.js";

interface ExpectedEntry {
  target: string;
  key: string[];
  context: string;
  is_unique_at_grain: boolean;
  max_fan_out: number;
  estimate: number;
}
interface FixtureCase {
  name: string;
  model: Record<string, unknown>;
  frames: Record<string, Record<string, unknown[]>>;
  expected: {
    dialect: string;
    n_certified: number;
    all_trustworthy: boolean;
    skipped: string[];
    entries: ExpectedEntry[];
  };
}

const fixturePath = fileURLToPath(new URL("./fixtures/semantic/certify.json", import.meta.url));
const fixture = JSON.parse(readFileSync(fixturePath, "utf-8")) as { cases: FixtureCase[] };

function run(c: FixtureCase) {
  const report = certifySemanticModel(c.model, c.frames as SemanticFrames);
  return {
    dialect: report.dialect,
    n_certified: report.nCertified,
    all_trustworthy: report.allTrustworthy,
    skipped: report.skipped,
    entries: report.entries.map((e) => ({
      target: e.target,
      key: e.key,
      context: e.context,
      is_unique_at_grain: e.certificate.isUniqueAtGrain,
      max_fan_out: e.certificate.maxFanOut,
      estimate: e.certificate.estimate,
    })),
  };
}

describe("certifySemanticModel — parity with Python certify_semantic_model", () => {
  it("covers all three dialects", () => {
    const dialects = new Set(fixture.cases.map((c) => c.expected.dialect));
    expect(dialects).toEqual(new Set(["metricflow", "cube", "osi"]));
  });

  for (const c of fixture.cases) {
    it(`${c.name} certifies identically`, () => {
      expect(run(c)).toEqual(c.expected);
    });
  }
});
