/**
 * Byte-for-byte parity: the TS semantic catalog emitters vs Python
 * `yaml.safe_dump`. The fixture is generated by
 * `packages/python/goldenmatch/scripts/emit_semantic_catalog_fixtures.py` from the
 * REAL Python emitters (metricflow / cube / osi over a stats-only crosswalk).
 * Each case's TS-emitted YAML must equal Python's exactly — including the block
 * layout, scalar quoting (`on`/`123`/`ref('x')`/`{CUBE}...` SQL), and the
 * integer-float `reduction_ratio` (`0.0`/`0.2`).
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { ResolvedCrosswalk } from "../../src/core/semantic/crosswalk.js";
import { emitFromCrosswalk } from "../../src/core/semantic/metricflow.js";
import { emitCubeFromCrosswalk } from "../../src/core/semantic/cube.js";
import { emitOsiFromCrosswalk } from "../../src/core/semantic/osi.js";

interface FixtureCase {
  name: string;
  dialect: "metricflow" | "cube" | "osi";
  crosswalk: {
    source: string;
    source_pk_column: string;
    resolved_key?: string;
    n_records: number;
    n_entities: number;
  };
  source_target: string;
  emit: {
    entity_name?: string;
    measures?: string[];
    grain?: string[] | string | null;
    model_ref?: string;
  };
  yaml: string;
}

const fixturePath = fileURLToPath(
  new URL("./fixtures/semantic/catalog-emit.json", import.meta.url),
);
const fixture = JSON.parse(readFileSync(fixturePath, "utf-8")) as {
  cases: FixtureCase[];
};

function buildCrosswalk(c: FixtureCase): ResolvedCrosswalk {
  return new ResolvedCrosswalk({
    source: c.crosswalk.source,
    sourcePkColumn: c.crosswalk.source_pk_column,
    ...(c.crosswalk.resolved_key !== undefined ? { resolvedKey: c.crosswalk.resolved_key } : {}),
    nRecords: c.crosswalk.n_records,
    nEntities: c.crosswalk.n_entities,
  });
}

function emit(c: FixtureCase): string {
  const xw = buildCrosswalk(c);
  if (c.dialect === "metricflow") {
    return emitFromCrosswalk(xw, c.source_target, {
      ...(c.emit.entity_name !== undefined ? { entityName: c.emit.entity_name } : {}),
      ...(c.emit.measures !== undefined ? { measures: c.emit.measures } : {}),
      ...(c.emit.grain !== undefined ? { grain: c.emit.grain } : {}),
      ...(c.emit.model_ref !== undefined ? { modelRef: c.emit.model_ref } : {}),
    });
  }
  if (c.dialect === "cube") {
    return emitCubeFromCrosswalk(xw, { sourceCube: c.source_target });
  }
  return emitOsiFromCrosswalk(xw, { sourceDataset: c.source_target });
}

describe("semantic catalog emitters — byte parity with Python yaml.safe_dump", () => {
  it("has cases across all three dialects", () => {
    const dialects = new Set(fixture.cases.map((c) => c.dialect));
    expect(dialects).toEqual(new Set(["metricflow", "cube", "osi"]));
    expect(fixture.cases.length).toBeGreaterThanOrEqual(9);
  });

  for (const c of fixture.cases) {
    it(`${c.name} (${c.dialect}) emits byte-identical YAML`, () => {
      expect(emit(c)).toBe(c.yaml);
    });
  }
});
