/**
 * Cross-language parity: the TS metric-aware roles reader (`semanticFieldRoles` /
 * `metricAwareAttributes`) vs Python `semantic/blocking.py`. The fixture is
 * generated by `packages/python/goldenmatch/scripts/emit_semantic_roles_fixtures.py`
 * from the REAL Python readers, per dialect. This selection is DETERMINISTIC (no ER
 * engine), so — unlike the resolution tier itself — it's a byte-parity surface: the
 * TS reader must reproduce Python's `{keys, dimensions, measures}` and its
 * `metric_aware_attributes(roles, columns)` allow-list exactly.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import {
  semanticFieldRoles,
  metricAwareAttributes,
} from "../../src/core/semantic/blocking.js";
import type { LoadedDoc } from "../../src/core/semantic/parseUtil.js";

interface FixtureCase {
  name: string;
  model: Record<string, unknown>;
  roles: { keys: string[]; dimensions: string[]; measures: string[] };
  attribute_selection: Array<{ columns: string[]; attributes: string[] }>;
}

const fixturePath = fileURLToPath(new URL("./fixtures/semantic/roles.json", import.meta.url));
const fixture = JSON.parse(readFileSync(fixturePath, "utf-8")) as { cases: FixtureCase[] };

describe("semantic roles + metric-aware selection — parity with Python semantic/blocking.py", () => {
  for (const c of fixture.cases) {
    it(`${c.name}: semanticFieldRoles matches Python`, () => {
      const roles = semanticFieldRoles(c.model as LoadedDoc);
      expect(roles.keys).toEqual(c.roles.keys);
      expect(roles.dimensions).toEqual(c.roles.dimensions);
      expect(roles.measures).toEqual(c.roles.measures);
    });

    it(`${c.name}: metricAwareAttributes matches Python for every column list`, () => {
      const roles = semanticFieldRoles(c.model as LoadedDoc);
      for (const sel of c.attribute_selection) {
        expect(metricAwareAttributes(roles, sel.columns)).toEqual(sel.attributes);
      }
    });
  }
});
