/**
 * Runnable conformance for the DIVERGENT standardize boundary (decision 0046).
 *
 * The 0046 verdict table lists "standardize/transforms" as divergent but named it
 * only in prose — the one non-exact boundary with no runnable test
 * (thesis-conformance decision 0047, weakness `standardize-dates-no-conformance-test`).
 * goldenmatch ships no date standardizer (that is GoldenFlow's divergence); the real
 * goldenmatch divergence is the standardizer SET — chiefly Python `None` vs TS `""`
 * for non-matching input, plus whitespace + title-casing differences.
 *
 * This is the TS half of a CHARACTERIZATION: it pins the TS output and the
 * agree/diverge partition against the committed fixture so the divergence cannot
 * silently widen. The Python half is tests/test_standardizer_conformance.py; the
 * Python-oracle block is regenerated by scripts/emit_standardizer_conformance_fixture.py.
 *
 * To regenerate the `typescript` block after an intended standardizer change, run a
 * probe that maps each (standardizer, input) through `applyStandardizer` and writes
 * the result into the fixture's `typescript` object (same shape as `python`).
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, it, expect } from "vitest";
import { applyStandardizer } from "../../src/core/standardize.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(join(here, "fixtures", "standardizer-conformance.json"), "utf8"),
) as {
  inputs: string[];
  standardizers: string[];
  python: Record<string, Record<string, string | null>>;
  typescript: Record<string, Record<string, string>>;
  summary: { agree: number; diverge: number };
};

describe("standardizer cross-surface characterization (0046 divergent boundary)", () => {
  it("TS standardizer output is pinned to the committed fixture", () => {
    for (const name of fixture.standardizers) {
      for (const s of fixture.inputs) {
        expect(
          applyStandardizer(s, name),
          `TS standardizer '${name}' on ${JSON.stringify(s)} drifted from the fixture`,
        ).toBe(fixture.typescript[name][s]);
      }
    }
  });

  it("agreement partition holds: where the fixture records agreement, live TS === Python", () => {
    let agree = 0;
    let diverge = 0;
    for (const name of fixture.standardizers) {
      for (const s of fixture.inputs) {
        const py = fixture.python[name][s];
        const ts = applyStandardizer(s, name);
        if (py === ts) {
          agree++;
        } else {
          diverge++;
          // A recorded divergence must still be recorded as one on the TS side.
          expect(ts).toBe(fixture.typescript[name][s]);
        }
      }
    }
    // The characterization headline is pinned — a new agreement or a new
    // divergence shifts these and fails, forcing a deliberate re-bless.
    expect(agree).toBe(fixture.summary.agree);
    expect(diverge).toBe(fixture.summary.diverge);
  });

  it("pins the dominant divergence: Python null vs TS empty-string on invalid input", () => {
    // email on a non-email input: Python None (JSON null) vs TS "".
    expect(fixture.python.email.MCDONALD).toBeNull();
    expect(applyStandardizer("MCDONALD", "email")).toBe("");
  });
});
