/**
 * suggest-column-signals.parity.test.ts — TS `buildColumnSignals` vs Python
 * `adapter.py::_build_column_signals_batch`.
 *
 * The fixture (`fixtures/suggest/column_signals_basic.json`) is generated by
 * `packages/python/goldenmatch/tests/fixtures/emit_column_signals_fixture.py`
 * (run by the controller via the Python .venv). It carries the `rows` +
 * `clusters` inputs and Python's `expected` ColumnSignal[]. The config is held
 * in LOCKSTEP with the emitter here (it doesn't round-trip — keep the two in
 * sync if either changes).
 *
 * Until the emitter has run, `expected` is null and this test skips. The
 * autoconfig wasm backend is enabled so `col_type` routes through the SAME
 * classifier Python uses (the shared autoconfig-core), removing the one field
 * where pure-TS heuristics could diverge from Python.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  buildColumnSignals,
  type ColumnSignal,
  type ColumnSignalCluster,
} from "../../src/core/suggestColumnSignals.js";
import {
  makeConfig,
  makeMatchkeyConfig,
  makeMatchkeyField,
  makeNegativeEvidenceField,
  type GoldenMatchConfig,
  type Row,
} from "../../src/core/types.js";
import {
  enableAutoconfigWasm,
  disableAutoconfigWasm,
} from "../../src/core/autoconfigWasm.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = join(here, "fixtures", "suggest", "column_signals_basic.json");

interface Fixture {
  readonly rows: Row[];
  readonly clusters: ColumnSignalCluster[];
  readonly expected?: readonly ColumnSignal[] | null;
}

/** Config held in lockstep with emit_column_signals_fixture.py. */
function fixtureConfig(): GoldenMatchConfig {
  return makeConfig({
    blocking: {
      strategy: "static",
      keys: [{ fields: ["zip"], transforms: [] }],
      maxBlockSize: 5000,
      skipOversized: false,
    },
    matchkeys: [
      makeMatchkeyConfig({
        name: "person",
        type: "weighted",
        fields: [makeMatchkeyField({ field: "name", scorer: "jaro_winkler" })],
        threshold: 0.85,
        negativeEvidence: [
          makeNegativeEvidenceField({ field: "email", scorer: "exact" }),
        ],
      }),
    ],
  });
}

const NUMERIC_FIELDS: ReadonlyArray<keyof ColumnSignal> = [
  "identity_score",
  "corruption_score",
  "collision_rate",
  "cardinality_ratio",
  "null_rate",
  "variant_rate",
];

describe("suggest column-signals parity (TS == Python)", () => {
  const fixture: Fixture | null = existsSync(fixturePath)
    ? (JSON.parse(readFileSync(fixturePath, "utf8")) as Fixture)
    : null;
  const ready = fixture !== null && Array.isArray(fixture.expected);

  beforeAll(() => {
    enableAutoconfigWasm();
  });
  afterAll(() => {
    disableAutoconfigWasm();
  });

  it.skipIf(!ready)("buildColumnSignals matches the Python fixture", () => {
    const f = fixture as Fixture;
    const expected = f.expected as readonly ColumnSignal[];
    const got = buildColumnSignals(f.rows, f.clusters, fixtureConfig());

    expect(got.length).toBe(expected.length);
    for (let i = 0; i < expected.length; i++) {
      const g = got[i]!;
      const e = expected[i]!;
      expect(g.field).toBe(e.field);
      expect(g.col_type).toBe(e.col_type);
      expect(g.scorer).toBe(e.scorer);
      expect(g.in_blocking).toBe(e.in_blocking);
      expect(g.in_negative_evidence).toBe(e.in_negative_evidence);
      for (const k of NUMERIC_FIELDS) {
        expect(g[k] as number).toBeCloseTo(e[k] as number, 9);
      }
    }
  });
});
