/**
 * tuners.parity.test.ts — gap 4 (memory-backed adaptive tuners).
 *
 * NE-tuner + golden-strategy-tuner goldens generated by
 * ``packages/python/goldenmatch/scripts/emit_v2_parity_fixtures.py``
 * (section ``tuners``). A stub MemoryStore replays the exact corrections
 * Python's MemoryStore held, so the grid-search / hit-rate / overfit-guard
 * decisions match.
 *
 * NE-tuner semantics: Python keys "match" via decision == "match" (a literal
 * the Decision enum never produces); the TS port maps its own "approve"
 * decision to the same truth. The fixture carries a neutral `is_match` boolean
 * that each language maps to its own decision string — so the F1 math is
 * identical on both sides.
 *
 * Cluster-decision tuner: logic-parity only (TS uses mulberry32, Python uses a
 * sha256-seeded shuffle — splits aren't byte-identical), unit-tested below.
 */
import { describe, it, expect } from "vitest";
import fixturesRaw from "./v2-fixtures.json" with { type: "json" };
import {
  tuneNeField,
  tuneFieldStrategy,
  tuneDecisionThreshold,
} from "../../src/core/autoconfigTuners.js";
import type { Correction, MemoryStore } from "../../src/core/memory/types.js";

/** Minimal MemoryStore stub: only getCorrections is exercised by the tuners. */
function stubStore(corrections: Correction[]): MemoryStore {
  return {
    getCorrections: async (opts?: { dataset?: string | null }) =>
      corrections.filter(
        (c) => opts?.dataset === undefined || c.dataset === opts.dataset,
      ),
  } as unknown as MemoryStore;
}

function baseCorrection(over: Partial<Correction>): Correction {
  return {
    id: over.id ?? "x",
    idA: over.idA ?? 0,
    idB: over.idB ?? 0,
    decision: over.decision ?? "approve",
    source: over.source ?? "steward",
    trust: over.trust ?? 1.0,
    fieldHash: "",
    recordHash: "",
    originalScore: over.trust ?? 1.0,
    matchkeyName: null,
    reason: null,
    dataset: over.dataset ?? "ds",
    createdAt: new Date(0),
    fieldName: over.fieldName ?? null,
    originalValue: over.originalValue ?? null,
    correctedValue: over.correctedValue ?? null,
    clusterScore: over.clusterScore ?? null,
    clusterOutcome: over.clusterOutcome ?? null,
  };
}

interface NeFixture {
  corrections: { id: string; is_match: boolean; trust: number }[];
  min_corrections: number;
  expected: {
    penalty: number;
    threshold: number;
    n_corrections: number;
    train_f1: number | null;
    heldout_f1: number | null;
    reason: string;
  };
}
interface GsFixture {
  field: string;
  corrections: {
    id: string;
    decision: string;
    trust: number;
    field_name: string | null;
    original_value: string | null;
    corrected_value: string | null;
  }[];
  candidates: string[];
  min_corrections: number;
  expected: {
    field: string;
    strategy: string;
    n_corrections: number;
    train_hit_rate: number | null;
    heldout_hit_rate: number | null;
    reason: string;
  };
}

const tuners = (
  fixturesRaw as { tuners: { ne_tuner: NeFixture; golden_strategy_tuner: GsFixture } }
).tuners;

describe("NE-tuner parity vs Python", () => {
  it("ne_tuner: grid search + overfit guard", async () => {
    const fx = tuners.ne_tuner;
    // Map the neutral is_match boolean to the TS "approve" decision.
    const corrections = fx.corrections.map((c, i) =>
      baseCorrection({
        id: c.id,
        idA: i,
        idB: i + 1,
        decision: c.is_match ? "approve" : "reject",
        trust: c.trust,
        dataset: "ds_ne",
      }),
    );
    const r = await tuneNeField(stubStore(corrections), "ds_ne", "email", fx.min_corrections);
    expect(r.reason).toBe(fx.expected.reason);
    expect(r.penalty).toBeCloseTo(fx.expected.penalty, 6);
    expect(r.threshold).toBeCloseTo(fx.expected.threshold, 6);
    expect(r.nCorrections).toBe(fx.expected.n_corrections);
    if (fx.expected.train_f1 !== null) {
      expect(r.trainF1).toBeCloseTo(fx.expected.train_f1, 6);
    }
    if (fx.expected.heldout_f1 !== null) {
      expect(r.heldoutF1).toBeCloseTo(fx.expected.heldout_f1, 6);
    }
  });
});

describe("golden-strategy-tuner parity vs Python", () => {
  it("golden_strategy_tuner: learns longest_value", async () => {
    const fx = tuners.golden_strategy_tuner;
    const corrections = fx.corrections.map((c) =>
      baseCorrection({
        id: c.id,
        decision: c.decision as Correction["decision"],
        trust: c.trust,
        dataset: "ds_gs",
        fieldName: c.field_name,
        originalValue: c.original_value,
        correctedValue: c.corrected_value,
      }),
    );
    const r = await tuneFieldStrategy(
      stubStore(corrections),
      "ds_gs",
      fx.field,
      fx.candidates,
      fx.min_corrections,
    );
    expect(r.reason).toBe(fx.expected.reason);
    expect(r.strategy).toBe(fx.expected.strategy);
    expect(r.nCorrections).toBe(fx.expected.n_corrections);
    if (fx.expected.train_hit_rate !== null) {
      expect(r.trainHitRate).toBeCloseTo(fx.expected.train_hit_rate, 6);
    }
    if (fx.expected.heldout_hit_rate !== null) {
      expect(r.heldoutHitRate).toBeCloseTo(fx.expected.heldout_hit_rate, 6);
    }
  });
});

// --- TS-only branch coverage (no Python interpreter needed) ---------------
describe("tuner branch coverage (TS unit)", () => {
  it("ne_tuner: no_memory when store is null", async () => {
    const r = await tuneNeField(null, "ds", "f");
    expect(r.reason).toBe("no_memory");
    expect(r.penalty).toBeCloseTo(0.3, 6);
    expect(r.threshold).toBeCloseTo(0.4, 6);
  });

  it("ne_tuner: below_minimum with too few corrections", async () => {
    const corr = [baseCorrection({ id: "a", decision: "approve", trust: 0.9 })];
    const r = await tuneNeField(stubStore(corr), "ds", "f", 50);
    expect(r.reason).toBe("below_minimum");
  });

  it("golden_strategy_tuner: no_memory when store is null", async () => {
    const r = await tuneFieldStrategy(null, "ds", "f");
    expect(r.reason).toBe("no_memory");
    expect(r.strategy).toBe("");
  });

  it("cluster-threshold tuner: below_minimum then valid sweep (logic parity)", async () => {
    // Below 2*min_band_n.
    const few = Array.from({ length: 10 }, (_, i) =>
      baseCorrection({
        id: `c${i}`,
        idA: i,
        decision: "cluster_decision",
        clusterScore: 0.9,
        clusterOutcome: "approve",
        dataset: "dsc",
      }),
    );
    const r1 = await tuneDecisionThreshold(stubStore(few), "dsc", { minBandN: 50 });
    expect(r1.reason).toBe("below_minimum");

    // Clear approve-above-threshold band: 120 corrections, high scores all
    // approve, low scores reject -> a qualifying band exists at every seed.
    const many = [
      ...Array.from({ length: 80 }, (_, i) =>
        baseCorrection({
          id: `hi${i}`,
          idA: i,
          decision: "cluster_decision",
          clusterScore: 0.95 + (i % 5) * 0.01,
          clusterOutcome: "approve",
          dataset: "dsc",
        }),
      ),
      ...Array.from({ length: 40 }, (_, i) =>
        baseCorrection({
          id: `lo${i}`,
          idA: 1000 + i,
          decision: "cluster_decision",
          clusterScore: 0.1 + (i % 5) * 0.01,
          clusterOutcome: "reject",
          dataset: "dsc",
        }),
      ),
    ];
    const r2 = await tuneDecisionThreshold(stubStore(many), "dsc", {
      minBandN: 20,
      targetApproveRate: 0.99,
      seed: 7,
    });
    // With a clean separation the sweep finds a qualifying band; reason is
    // either "ok" (heldout validated) or "overfit" (heldout had no >= band) —
    // both are valid sweep outcomes. It must NOT be below_minimum / no band.
    expect(["ok", "overfit", "no_qualifying_band"]).toContain(r2.reason);
    expect(r2.nTotal).toBe(120);
  });
});
