/* AUTO-GENERATED by scripts/build_goldencheck_wasm.mjs — DO NOT EDIT. */
export function gc_discover_functional_dependencies(columns_json: string): string;
export function gc_discover_approximate_fds(columns_json: string, min_confidence: number): string;
export function gc_functional_dependency_holds(lhs_json: string, rhs_json: string): string;
export function gc_fd_violation_rows(det_json: string, dep_json: string): string;
export function gc_composite_key_search(columns_json: string, max_size: number, single_unique_json: string): string;
export function gc_benford_leading_digits(values_json: string): string;
export function gc_near_duplicate_clusters(values_json: string, min_similarity: number): string;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export function initSync(
  module: { module: SyncInitInput } | SyncInitInput,
): unknown;
