"""Identity Graph -- durable, queryable graph of identities, source records,
match evidence, conflicts, and versioned changes over time.

See ``docs/superpowers/specs/2026-05-12-identity-graph-design.md``.
"""
from __future__ import annotations

from goldenmatch.identity.audit import (
    AuditVerification,
    audit_log_page,
    event_content_hash,
    seal_audit_log,
    seal_result_dict,
    verify_audit_chain,
)
from goldenmatch.identity.mediation import (
    ConflictItem,
    ConflictResolution,
    MediationVerdict,
    mediate_conflict,
    mediation_summary,
    open_conflicts,
    pair_verdict,
)
from goldenmatch.identity.migrate_ids import MigrationReport, migrate_record_ids
from goldenmatch.identity.model import (
    AuditSeal,
    ClaimType,
    EdgeKind,
    EventKind,
    EvidenceEdge,
    EvidenceRef,
    IdentityAlias,
    IdentityEvent,
    IdentityNode,
    IdentityStatus,
    SourceRecord,
)
from goldenmatch.identity.profile import (
    EntityProfile,
    IdentitySummary,
    WorklistItem,
    entity_profile,
    identity_summary_stats,
    steward_worklist,
    steward_worklist_page,
)
from goldenmatch.identity.query import (
    IdentityView,
    amend_claim,
    claim_record,
    find_by_record,
    find_conflicts,
    get_entity,
    history,
    list_entities,
    manual_merge,
    manual_split,
    promote_claim,
    revoke_claim,
)
from goldenmatch.identity.resolve import (
    ResolveSummary,
    match_record_to_entity,
    resolve_clusters,
    resolve_record_incremental,
)
from goldenmatch.identity.stabilize import (
    ConsolidationGroup,
    OverlapCandidate,
    StabilizeReport,
    entity_version,
    find_persistent_overlaps,
    stabilize_identities,
)
from goldenmatch.identity.stitching import (
    DEFAULT_CHANNEL_TRUST,
    DEFAULT_DEVICE_KEYS,
    StitchGroup,
    StitchResult,
    adjust_score,
    channel_trust,
    classify_channel,
    cross_channel_factor,
    deterministic_stitch_pairs,
    stitch_frame,
)
from goldenmatch.identity.store import IdentityStore, new_entity_id
from goldenmatch.identity.survivorship import (
    CellProvenance,
    FieldStrategyRecommendation,
    GoldenRecordWithProvenance,
    build_golden_with_provenance,
    learn_field_survivorship,
    learned_field_strategies,
)

__all__ = [
    "ConsolidationGroup",
    "OverlapCandidate",
    "StabilizeReport",
    "entity_version",
    "find_persistent_overlaps",
    "stabilize_identities",
    "ConflictItem",
    "ConflictResolution",
    "MediationVerdict",
    "mediate_conflict",
    "mediation_summary",
    "open_conflicts",
    "pair_verdict",
    "IdentityView",
    "MigrationReport",
    "ResolveSummary",
    "find_by_record",
    "find_conflicts",
    "get_entity",
    "history",
    "list_entities",
    "manual_merge",
    "manual_split",
    "claim_record",
    "promote_claim",
    "amend_claim",
    "revoke_claim",
    "match_record_to_entity",
    "migrate_record_ids",
    "resolve_clusters",
    "resolve_record_incremental",
    "DEFAULT_CHANNEL_TRUST",
    "DEFAULT_DEVICE_KEYS",
    "StitchGroup",
    "StitchResult",
    "adjust_score",
    "channel_trust",
    "classify_channel",
    "cross_channel_factor",
    "deterministic_stitch_pairs",
    "stitch_frame",
    "CellProvenance",
    "FieldStrategyRecommendation",
    "GoldenRecordWithProvenance",
    "build_golden_with_provenance",
    "learn_field_survivorship",
    "learned_field_strategies",
    "EntityProfile",
    "IdentitySummary",
    "WorklistItem",
    "entity_profile",
    "identity_summary_stats",
    "steward_worklist",
    "steward_worklist_page",
    "AuditSeal",
    "AuditVerification",
    "audit_log_page",
    "event_content_hash",
    "seal_audit_log",
    "seal_result_dict",
    "verify_audit_chain",
    "ClaimType",
    "EvidenceRef",
    "EdgeKind",
    "EventKind",
    "EvidenceEdge",
    "IdentityAlias",
    "IdentityEvent",
    "IdentityNode",
    "IdentityStatus",
    "IdentityStore",
    "SourceRecord",
    "new_entity_id",
]
