"""Rust == Python parity for the documents-core kernels (schema/parse/prompt/normalize).

Every row in documents_corpus.jsonl (generated by scripts/gen_documents_corpus.py
from the PURE-PYTHON kernels) is replayed against:
  1. the pure-Python reference -- must always match `expected` (locks Python
     behavior regardless of the machine's native wheel state).
  2. the native kernel, ONLY when `native_enabled("documents")` and the specific
     symbol is importable -- asserts native == expected too. Skipped (not
     failed) on a pure-Python machine so the test stays green there, and is
     strict wherever native IS available (including CI's GOLDENMATCH_NATIVE=1
     lane).

Error-case parity is by OUTCOME (raises / returns error), not exact message
text -- Rust and Python phrase envelope/malformed errors differently. The one
shared exact message is the finish_reason=length truncation, asserted via a
substring on both legs.

Normalize column ORDER is asserted explicitly (ordered [col, val] pairs in
the corpus) since a plain dict compare wouldn't catch a reordering.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from goldenmatch.core._native_loader import native_module, native_enabled
from goldenmatch.documents._openai import parse_message_text
from goldenmatch.documents.schema_io import schema_from_dict, schema_to_dict
from goldenmatch.documents.suggest import _PROMPT
from goldenmatch.documents.types import ExtractedRow
from goldenmatch.documents.vlm_backend import _instruction

CORPUS = Path(__file__).parent / "documents_corpus.jsonl"


def _load_corpus() -> list[dict]:
    rows = []
    with CORPUS.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


CORPUS_ROWS = _load_corpus()


def _run_pure(kernel: str, input_: object):
    """Run the PURE-PYTHON kernel for one corpus row. Returns the 'ok' payload
    (in the same shape gen_documents_corpus.py wrote), raising on error."""
    if kernel == "schema":
        s = schema_from_dict(input_)
        return schema_to_dict(s)
    if kernel == "parse":
        return parse_message_text(input_)
    if kernel == "prompt_extract":
        s = schema_from_dict(input_)
        return _instruction(s)
    if kernel == "prompt_suggest":
        return _PROMPT
    if kernel == "normalize":
        ts = schema_from_dict(input_["schema"])
        cols = ts.column_names()
        row = ExtractedRow.from_partial(
            input_["values"], input_["confidence"], ts, source_file="", source_page=0
        )
        return {
            "values": [[c, row.values[c]] for c in cols],
            "confidence": [[c, row.confidence[c]] for c in cols],
        }
    raise AssertionError(f"unknown kernel {kernel!r}")


def _run_native(kernel: str, input_: object, symbol: str):
    """Run the NATIVE kernel directly (bypassing the Python fallback wiring) for
    one corpus row. Raises ValueError on kernel failure, mirroring the pure
    path's contract."""
    nm = native_module()
    if kernel == "schema":
        out = nm.documents_schema_validate(json.dumps(input_))
        return json.loads(out)
    if kernel == "parse":
        return nm.documents_parse_message_text(json.dumps(input_))
    if kernel == "prompt_extract":
        return nm.documents_extract_instruction(json.dumps(input_))
    if kernel == "prompt_suggest":
        return nm.documents_suggest_prompt()
    if kernel == "normalize":
        schema_json = json.dumps(input_["schema"])
        cols = [f["name"] for f in input_["schema"]["fields"]]
        out = json.loads(
            nm.documents_normalize_record(
                json.dumps(input_["values"]), json.dumps(input_["confidence"]), schema_json
            )
        )
        pv, pc = out["values"], out["confidence"]
        return {
            "values": [[c, pv.get(c)] for c in cols],
            "confidence": [[c, float(pc.get(c, 0.0))] for c in cols],
        }
    raise AssertionError(f"unknown kernel {kernel!r}")


_KERNEL_SYMBOL = {
    "schema": "documents_schema_validate",
    "parse": "documents_parse_message_text",
    "prompt_extract": "documents_extract_instruction",
    "prompt_suggest": "documents_suggest_prompt",
    "normalize": "documents_normalize_record",
}


@pytest.mark.parametrize("row", CORPUS_ROWS, ids=[f"{r['kernel']}-{i}" for i, r in enumerate(CORPUS_ROWS)])
def test_pure_python_matches_corpus(row):
    kernel, input_, expected = row["kernel"], row["input"], row["expected"]
    if expected.get("error"):
        with pytest.raises(ValueError) as exc_info:
            _run_pure(kernel, input_)
        substring = expected.get("substring")
        if substring:
            assert substring in str(exc_info.value)
        return
    assert _run_pure(kernel, input_) == expected["ok"]


@pytest.mark.parametrize("row", CORPUS_ROWS, ids=[f"{r['kernel']}-{i}" for i, r in enumerate(CORPUS_ROWS)])
def test_native_matches_corpus(row):
    kernel, input_, expected = row["kernel"], row["input"], row["expected"]
    symbol = _KERNEL_SYMBOL[kernel]
    nm = native_module()
    if nm is None or not hasattr(nm, symbol):
        pytest.skip("native kernel not importable on this machine")
    if os.environ.get("GOLDENMATCH_NATIVE", "auto").lower() == "0":
        pytest.skip("GOLDENMATCH_NATIVE=0 forces pure-Python; native leg not exercised")

    if expected.get("error"):
        with pytest.raises(ValueError) as exc_info:
            _run_native(kernel, input_, symbol)
        substring = expected.get("substring")
        if substring:
            assert substring in str(exc_info.value)
        return
    assert _run_native(kernel, input_, symbol) == expected["ok"]
