#!/usr/bin/env bash
# Build score-wasm for wasm32 and copy the artifact + glue into the goldenmatch
# TS package. Run from anywhere. Requires: rustup wasm32 target + wasm-bindgen-cli.
set -euo pipefail
export CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-$HOME/.rustup}"
export PATH="$CARGO_HOME/bin:$PATH"

CRATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$CRATE_DIR/../../../typescript/goldenmatch/src/core/wasm/artifacts"

rustup target add wasm32-unknown-unknown
cargo build --manifest-path "$CRATE_DIR/Cargo.toml" --target wasm32-unknown-unknown --release

# Install wasm-bindgen-cli at the EXACT version pinned in Cargo.lock — a CLI/crate
# version skew produces broken JS glue that fails at runtime, not build time
# (a known wasm-bindgen footgun). Read the pinned version straight from the
# committed lockfile (the reason we commit it). The anchored grep matches the
# exact `wasm-bindgen` package, never `wasm-bindgen-macro`/`-shared`.
WB_VER="$(grep -A1 '^name = "wasm-bindgen"$' "$CRATE_DIR/Cargo.lock" | grep '^version = ' | head -1 | sed -E 's/version = "([^"]+)"/\1/')"
if [ -z "$WB_VER" ]; then echo "could not resolve wasm-bindgen version from Cargo.lock" >&2; exit 1; fi
echo "Using wasm-bindgen $WB_VER"

# Only (re)install when the on-PATH cli doesn't already match the pinned version.
if ! wasm-bindgen --version 2>/dev/null | grep -q "$WB_VER"; then
  cargo install wasm-bindgen-cli --version "=$WB_VER" --locked
fi
command -v wasm-bindgen >/dev/null 2>&1 || { echo "wasm-bindgen not on PATH after install; aborting" >&2; exit 1; }

wasm-bindgen \
  "$CRATE_DIR/target/wasm32-unknown-unknown/release/goldenmatch_score_wasm.wasm" \
  --target web --out-dir "$OUT_DIR" --out-name score_wasm

# Also emit the UNIVERSAL-loader artifact: the .wasm base64-inlined into a tiny
# JS module (`score_wasm_base64.js`, exporting `WASM_BASE64`). This is what the
# opt-in universal loader (enableWasm({ universal: true })) imports so it can
# resolve the bytes with NO fetch / fs / import.meta.url — the only path that
# loads edge-safe across Node / browser / Cloudflare Workers / Deno + every
# bundler. Gitignored like the .wasm itself; built here so CI/devs get it for free.
# (Portable base64: `base64 -w0` is GNU-only; pipe through `tr -d '\n'` instead.)
B64="$(base64 "$OUT_DIR/score_wasm_bg.wasm" | tr -d '\n')"
cat > "$OUT_DIR/score_wasm_base64.js" <<EOF
// GENERATED by score-wasm/build_wasm.sh — do not edit. The .wasm bytes inlined
// as standard base64 for the universal (edge-safe) loader. Gitignored.
export const WASM_BASE64 = "$B64";
EOF

echo "Artifact written to $OUT_DIR (score_wasm_bg.wasm + score_wasm.js + score_wasm_base64.js)"
