"""Ratchet for layer detection against foreign-key-derived ground truth.

The sibling ``test_layers_precision.py`` pins a HAND-AUTHORED corpus, which has
a weakness it cannot fix: its labels were written by whoever tuned the
detector, so a perfect score there partly measures self-agreement.

Here nothing is hand-labelled. Wide tables are generated by joining a fact to
its dimensions in reconstructed public schemas (TPC-H, Northwind, Sakila), and
each column's party is simply **the table it came from** -- the grouping is the
original schema designer's, not ours. That makes this the check on whether the
hand corpus was being overfit.

Two floors, deliberately different in kind:

* ``exact partition`` -- unforgiving, the honest headline.
* ``pairwise F1`` -- partial credit over column pairs, so a partition that is
  mostly right stays distinguishable from one that is wrong.

The ``initial`` convention (TPC-H's own ``c_name``/``s_name`` style) is
EXCLUDED from the floors and asserted as a known blind spot instead: a
one-character qualifier is below the kernel's ``MIN_QUALIFIER_LEN``, so those
schemas cannot be segmented by name at all. It is measured rather than hidden
-- see ``test_single_char_qualifiers_are_a_known_blind_spot``.
"""
from __future__ import annotations

import sys
from pathlib import Path

from infermap import detect_identity_layers

sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "scripts"))

from layers_fk_groundtruth import run  # noqa: E402

#: Measured behaviour on conventions the affix signal can see. Floors, not goals.
#:
#: Was 22 of 24 cases (0.9166...), with both misses on `claims_ledger`: the
#: three dimension parties scored 0.90-0.93 while the FACT's own columns were
#: dropped, because `claim` tokenizes out of healthcare's `claim_status` type
#: hint and is stop-listed. Declaring `claim` as a role took this to 24 of 24
#: (#2574), so the floors are pinned at the exact values -- the same posture
#: `test_layers_precision.py` takes with MIN_SPECIFICITY.
#:
#: This corpus has now SATURATED on detectable conventions, which is a reason
#: to grow it rather than to celebrate. The discriminating signal has moved to
#: the `initial` convention (still 0%, see the blind-spot test below) and to
#: the blind-labelling corpus.
MIN_EXACT_PARTITION = 1.0
MIN_PAIRWISE_F1 = 1.0

#: The `initial` convention was a hard blind spot -- 0% exact, pairwise F1 0.08
#: -- because a one-character qualifier is below the kernel's floor. The
#: whole-frame partition gate (#2574) took it to 5 of 8 exact (0.625) and
#: pairwise F1 0.88. Floors sit just below the measured values.
#:
#: It does NOT join the headline floors above. The residual 3 of 8 is
#: irreducible from column names (see the collision test below), so folding
#: `initial` into one number would report a permanent ceiling as a score.
MIN_INITIAL_EXACT = 0.62
MIN_INITIAL_PAIRWISE_F1 = 0.87


def _summary():
    return run(detect_identity_layers)["summary"]


def test_exact_partition_does_not_regress():
    d = _summary()["detectable"]
    assert d["exact_partition"] >= MIN_EXACT_PARTITION, (
        f"exact partition fell to {d['exact_partition']:.0%}"
    )


def test_pairwise_f1_does_not_regress():
    """Partial credit, so a near-miss partition is not scored the same as a rout."""
    d = _summary()["detectable"]
    assert d["pairwise_f1"] >= MIN_PAIRWISE_F1, (
        f"pairwise F1 fell to {d['pairwise_f1']:.2f}"
    )


def test_party_count_error_stays_below_one():
    """The quantity per-block config (#2575) would partition on."""
    d = _summary()["detectable"]
    assert d["mean_count_error"] < 1.0


def test_single_char_qualifiers_are_detected_when_initials_are_distinct():
    """The inversion the previous version of this test asked for.

    TPC-H ships natively as ``c_name``/``s_name``/``o_orderkey``. Those
    qualifiers are one character, below ``MIN_QUALIFIER_LEN``, and detection
    could not see the parties at all: 0% exact, pairwise F1 0.08, a quarter of
    this corpus. The whole-frame partition gate (#2574) took it to 62% / 0.88.
    """
    blind = _summary()["known_blind_spot"]
    assert blind["n"] > 0
    assert blind["exact_partition"] >= MIN_INITIAL_EXACT, (
        f"initial-convention exact fell to {blind['exact_partition']:.0%}"
    )
    assert blind["pairwise_f1"] >= MIN_INITIAL_PAIRWISE_F1


def test_the_initial_residual_is_exactly_the_colliding_schemas():
    """The residual is a property of the CONVENTION, not of the detector.

    ``provider`` and ``patient`` both abbreviate to ``p``, so ``p_name`` cannot
    name which one — irreducible from column names alone. This derives the
    colliding set from the schema fixture rather than pinning a list, so it
    stays true as the corpus grows, and asserts the failure MODE too: pairwise
    recall stays at 1.0 on every miss, meaning nothing is wrongly split and the
    only error is two parties forced into one.
    """
    import json

    from layers_fk_groundtruth import SCHEMAS

    spec = json.loads(Path(SCHEMAS).read_text(encoding="utf-8"))
    collides = set()
    for schema in spec["schemas"]:
        entities = [schema["fact"], *schema["dimensions"]]
        initials = [e[0] for e in entities]
        if len(initials) != len(set(initials)):
            collides.add(schema["name"])
    assert collides, "corpus no longer exercises an initial collision"

    for case in run(detect_identity_layers)["cases"]:
        if case["convention"] != "initial":
            continue
        if case["schema"] in collides:
            assert not case["exact_partition"], case["schema"]
            assert case["pairwise_recall"] == 1.0, (
                f"{case['schema']}: a collision should FUSE parties, never split one"
            )
        else:
            assert case["exact_partition"], case["schema"]


def test_ground_truth_is_not_hand_labelled():
    """The property that makes this corpus worth having.

    Every label must be derivable from the schema definition alone; if a case
    ever carries a hand-written expected grouping, this corpus has lost the
    independence that distinguishes it from the precision corpus.
    """
    import json

    from layers_fk_groundtruth import SCHEMAS

    spec = json.loads(Path(SCHEMAS).read_text(encoding="utf-8"))
    for schema in spec["schemas"]:
        assert set(schema) <= {"name", "source", "fact", "own_columns", "dimensions"}
        assert schema["dimensions"], schema["name"]
