"""Ratchet for layer detection against foreign-key-derived ground truth.

The sibling ``test_layers_precision.py`` pins a HAND-AUTHORED corpus, which has
a weakness it cannot fix: its labels were written by whoever tuned the
detector, so a perfect score there partly measures self-agreement.

Here nothing is hand-labelled. Wide tables are generated by joining a fact to
its dimensions in reconstructed public schemas (TPC-H, Northwind, Sakila), and
each column's party is simply **the table it came from** -- the grouping is the
original schema designer's, not ours. That makes this the check on whether the
hand corpus was being overfit.

Two floors, deliberately different in kind:

* ``exact partition`` -- unforgiving, the honest headline.
* ``pairwise F1`` -- partial credit over column pairs, so a partition that is
  mostly right stays distinguishable from one that is wrong.

The ``initial`` convention (TPC-H's own ``c_name``/``s_name`` style) is
EXCLUDED from the floors and asserted as a known blind spot instead: a
one-character qualifier is below the kernel's ``MIN_QUALIFIER_LEN``, so those
schemas cannot be segmented by name at all. It is measured rather than hidden
-- see ``test_single_char_qualifiers_are_a_known_blind_spot``.
"""
from __future__ import annotations

import sys
from pathlib import Path

from infermap import detect_identity_layers

sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "scripts"))

from layers_fk_groundtruth import run  # noqa: E402

#: Measured behaviour on conventions the affix signal can see. Floors, not goals.
#:
#: Exact partition is 22 of 24 cases (0.9166...). The floor sits just below it
#: rather than at the rounded 92% the report prints -- a floor set from a
#: displayed figure fails on the value it was derived from.
MIN_EXACT_PARTITION = 0.91
MIN_PAIRWISE_F1 = 0.98


def _summary():
    return run(detect_identity_layers)["summary"]


def test_exact_partition_does_not_regress():
    d = _summary()["detectable"]
    assert d["exact_partition"] >= MIN_EXACT_PARTITION, (
        f"exact partition fell to {d['exact_partition']:.0%}"
    )


def test_pairwise_f1_does_not_regress():
    """Partial credit, so a near-miss partition is not scored the same as a rout."""
    d = _summary()["detectable"]
    assert d["pairwise_f1"] >= MIN_PAIRWISE_F1, (
        f"pairwise F1 fell to {d['pairwise_f1']:.2f}"
    )


def test_party_count_error_stays_below_one():
    """The quantity per-block config (#2575) would partition on."""
    d = _summary()["detectable"]
    assert d["mean_count_error"] < 1.0


def test_single_char_qualifiers_are_a_known_blind_spot():
    """Pinned so the limitation is visible, and so a fix is noticed.

    TPC-H ships natively as ``c_name``/``s_name``/``p_name``. Those qualifiers
    are one character, below ``MIN_QUALIFIER_LEN``, so detection cannot see the
    parties at all. If this ever starts passing, the floors above should gain
    the ``initial`` convention and this test should be inverted.
    """
    blind = _summary()["known_blind_spot"]
    assert blind["n"] > 0
    assert blind["exact_partition"] == 0.0


def test_ground_truth_is_not_hand_labelled():
    """The property that makes this corpus worth having.

    Every label must be derivable from the schema definition alone; if a case
    ever carries a hand-written expected grouping, this corpus has lost the
    independence that distinguishes it from the precision corpus.
    """
    import json

    from layers_fk_groundtruth import SCHEMAS

    spec = json.loads(Path(SCHEMAS).read_text(encoding="utf-8"))
    for schema in spec["schemas"]:
        assert set(schema) <= {"name", "source", "fact", "own_columns", "dimensions"}
        assert schema["dimensions"], schema["name"]
