/**
 * FastDC-style minimal-cover derivation of denial constraints from evidence.
 * Parity port of `packages/python/goldencheck/goldencheck/denial/discover.py`.
 *
 * An evidence map is `{mask: count}` where `mask` (u64 → bigint) is the set of
 * predicates one element satisfies. A DC is a predicate set `X` (bitmask) whose
 * conjunction is (almost) never satisfied: the count of elements whose mask is a
 * superset of `X` is `<= eps * total`. We derive the MINIMAL such `X`s.
 */

import { MAX_CONSTRAINTS, MAX_REPORT_ARITY } from "./constants.js";

/** Bit-complement of `mask` bounded to `nPredicates` low bits. */
export function complement(mask: bigint, nPredicates: number): bigint {
  return ~mask & ((1n << BigInt(nPredicates)) - 1n);
}

/** Number of elements whose mask is a superset of `maskX` (X ⊆ mask). */
function satisfiedCount(maskX: bigint, evidence: ReadonlyMap<bigint, number>): number {
  let total = 0;
  for (const [mask, cnt] of evidence) {
    if ((mask & maskX) === maskX) total += cnt;
  }
  return total;
}

/** Popcount over a bigint mask. */
function arity(mask: bigint): number {
  let m = mask;
  let count = 0;
  while (m > 0n) {
    count += Number(m & 1n);
    m >>= 1n;
  }
  return count;
}

/** Lexicographic k-combinations of `items` (ascending index order preserved). */
function* combinations<T>(items: readonly T[], k: number): Generator<T[]> {
  const n = items.length;
  if (k > n || k < 0) return;
  const idx = Array.from({ length: k }, (_, i) => i);
  while (true) {
    yield idx.map((i) => items[i]!);
    let i = k - 1;
    while (i >= 0 && idx[i] === i + n - k) i--;
    if (i < 0) return;
    idx[i]!++;
    for (let j = i + 1; j < k; j++) idx[j] = idx[j - 1]! + 1;
  }
}

/**
 * Return minimal DC bitmasks. `total` is the true element count. Candidates are
 * generated by INCREASING size, so every DC found is minimal by construction (a
 * superset of an already-found DC is pruned before its count is computed).
 */
export function discover(
  evidence: ReadonlyMap<bigint, number>,
  nPredicates: number,
  total: number,
  eps: number,
  arityBound: number = MAX_REPORT_ARITY,
): bigint[] {
  const threshold = eps * total;

  // Predicate bit indices set in at least one evidence mask.
  const active: number[] = [];
  for (let b = 0; b < nPredicates; b++) {
    let any = false;
    for (const mask of evidence.keys()) {
      if ((mask >> BigInt(b)) & 1n) {
        any = true;
        break;
      }
    }
    if (any) active.push(b);
  }

  const found: bigint[] = [];
  for (let size = 1; size <= arityBound; size++) {
    for (const combo of combinations(active, size)) {
      let xmask = 0n;
      for (const b of combo) xmask |= 1n << BigInt(b);
      // Minimality prune: skip any superset of a known DC.
      if (found.some((f) => (f & xmask) === f)) continue;
      if (satisfiedCount(xmask, evidence) <= threshold) found.push(xmask);
    }
  }
  return found;
}

/**
 * Rank DCs by interestingness = support * succinctness, return top-N. Descending
 * interestingness; ascending `(arity, mask)` tie-break (mask compared numerically).
 */
export function rank(
  dcs: readonly bigint[],
  evidence: ReadonlyMap<bigint, number>,
  total: number,
  maxConstraints: number = MAX_CONSTRAINTS,
): bigint[] {
  const keyed = dcs.map((x) => {
    const support = 1.0 - (total ? satisfiedCount(x, evidence) / total : 0.0);
    const succinctness = x ? 1.0 / arity(x) : 0.0;
    return { x, interestingness: support * succinctness, ar: arity(x) };
  });
  keyed.sort((a, b) => {
    if (a.interestingness !== b.interestingness) return b.interestingness - a.interestingness;
    if (a.ar !== b.ar) return a.ar - b.ar;
    return a.x < b.x ? -1 : a.x > b.x ? 1 : 0;
  });
  return keyed.slice(0, maxConstraints).map((e) => e.x);
}
