#!/usr/bin/env python3
"""Every repo path a CLAUDE.md names must exist.

WHY THIS EXISTS
---------------
The 21 `check_*.py` gates are the pattern that works: an assertion in code cannot
rot. The prose in the 22 CLAUDE.md files can, and does -- and unlike a stale
comment, agents ACT on it, because these files are loaded into every session as
authoritative context.

Measured on the tree the day this landed: 38 dead path references, including 24
design docs under `docs/superpowers/` that no longer exist anywhere, three
workflows deleted in the monorepo fold (`npm-publish.yml`, `pages.yml`,
`try-it.yml`), a `parity/goldengraph.yaml` manifest that was never created, and a
`_archive/goldenmatch-pre-fold/` tree the root file tells you to go search which
is not in the repo at all. That last one is the shape that costs the most: it
does not merely fail to help, it sends the reader somewhere empty and they
conclude the thing was never designed.

This gate catches the largest and most mechanical rot class -- things that moved
or were deleted. It cannot catch a semantically wrong claim ("FOLLOW-UP: not
done" when it is done); for those the convention is to record the COMMAND that
checks the state, not the state.

HOW
---
A backticked token is treated as a repo path when it contains `/`, ends in a
known source/config extension, and has no placeholder characters. Markdown links
to relative files are checked too.

Resolution is deliberately generous: a token resolves if it matches a tracked
path exactly OR is the tail of one. So a Python package's CLAUDE.md may refer to
its TypeScript sibling's `core/scorers/registry.ts` without spelling out the full
path -- that is how these docs are written, and demanding full paths would be a
gate that fights the house style instead of catching rot. What it still catches
is a file that exists NOWHERE, which is exactly what deletion and renaming look
like.

FAIL (exit 1) on an unresolved reference not in `_ALLOW`. Exit 2 if the scan
itself looks broken.

Run from the repo root:  python scripts/check_claude_refs.py
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Directories holding prose EXTRACTED from a CLAUDE.md. Scanned alongside the
# CLAUDE.md files themselves so a split cannot move dead references out of scope.
EXTRACTED_CONTEXT_DIRS = (
    "context-network/operations",
    "packages/python/goldenmatch/docs/context",
)

# Extensions that make a slash-containing token a plausible file reference.
SOURCE_EXT = {
    ".cfg", ".ini", ".js", ".json", ".lock", ".md", ".mdx", ".mjs", ".py",
    ".rs", ".sh", ".sql", ".toml", ".ts", ".tsx", ".txt", ".yaml", ".yml",
}

# Tokens that are paths but are NOT expected to exist, each with the reason.
# Same discipline as `scorer_kernels_deferred`: an entry here is a DECLARED
# exception, not a silent skip. Prefer fixing the reference.
_ALLOW: dict[str, str] = {
    "scripts/baselines/qis_scorecard.json": (
        "intentionally absent -- the QIS gate ships with no committed baseline on "
        "purpose; the first `-f mode=bless` run in CI creates it"
    ),
    "goldencheck/profilers/my_check.py": (
        "tutorial placeholder -- the 'write your own profiler' walkthrough names a "
        "file the reader creates"
    ),
    "tests/profilers/test_my_check.py": (
        "tutorial placeholder -- companion test in the same walkthrough"
    ),
    "dist/core/index.js": (
        "build output -- gitignored, exists only after `pnpm build`"
    ),
    "artifacts/score_wasm_base64.js": (
        "build output -- generated by the wasm build, gitignored"
    ),
    ".profile_tmp/profile_ncvr.py": (
        "gitignored by design -- `.profile_tmp/` holds local profiling artifacts and "
        "is never committed, so this reference can never resolve"
    ),
    "packages/tests/fixtures/parity_cases.json": (
        "documented AS broken -- the note exists precisely to record that the infermap "
        "parity test still points at a pre-monorepo path; fixing the test retires both"
    ),
}

# The scan must find at least this much, or it is broken rather than clean.
MIN_CLAUDE_FILES = 10
MIN_CANDIDATES = 100

_TICKED = re.compile(r"`([^`\n]+)`")
_MD_LINK = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
_PLACEHOLDER = set("<>*{}| ")


def tracked_paths() -> set[str]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout
    return set(out.split())


def claude_files() -> list[pathlib.Path]:
    """Every file that is loaded as, or directly linked from, agent context.

    The extraction targets are included deliberately: the root and goldenmatch
    CLAUDE.md files were split into them, and a gate that stopped at CLAUDE.md would
    have let those splits HIDE the rot it exists to catch -- moving prose out of
    scope is not the same as fixing it. Any future split must add its target here.
    """
    files = [
        p
        for p in ROOT.rglob("CLAUDE.md")
        if "node_modules" not in p.parts and "_archive" not in p.parts
    ]
    for extracted in EXTRACTED_CONTEXT_DIRS:
        files.extend(sorted((ROOT / extracted).glob("*.md")))
    return sorted(set(files))


def _is_path_like(token: str) -> bool:
    if "/" not in token or "..." in token:
        return False
    if any(c in _PLACEHOLDER for c in token):
        return False
    if token.startswith(("http", "#", "/", "~", "$")):
        return False
    return pathlib.PurePosixPath(token).suffix in SOURCE_EXT


def references(path: pathlib.Path) -> dict[str, int]:
    """Path-like references in one file, mapped to the line they first appear on."""
    found: dict[str, int] = {}
    for lineno, line in enumerate(path.read_text(encoding="utf-8", errors="ignore").splitlines(), 1):
        for pattern in (_TICKED, _MD_LINK):
            for m in pattern.finditer(line):
                token = m.group(1).strip().split("#", 1)[0].strip()
                if _is_path_like(token):
                    found.setdefault(token, lineno)
    return found


def _resolver(tracked: set[str]):
    by_basename: dict[str, list[str]] = {}
    for p in tracked:
        by_basename.setdefault(p.rsplit("/", 1)[-1], []).append(p)

    def resolves(token: str) -> bool:
        if token in tracked:
            return True
        tail = "/" + token
        return any(p.endswith(tail) for p in by_basename.get(token.rsplit("/", 1)[-1], []))

    return resolves


def check() -> tuple[list[tuple[pathlib.Path, int, str]], int, int]:
    """Return (problems, files_scanned, candidates_seen)."""
    tracked = tracked_paths()
    resolves = _resolver(tracked)
    problems: list[tuple[pathlib.Path, int, str]] = []
    files = claude_files()
    candidates = 0
    for path in files:
        for token, lineno in sorted(references(path).items()):
            candidates += 1
            if token in _ALLOW or resolves(token):
                continue
            problems.append((path, lineno, token))
    return problems, len(files), candidates


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--list-allowed", action="store_true", help="print the declared exceptions and exit"
    )
    args = ap.parse_args(argv)

    if args.list_allowed:
        for token, reason in sorted(_ALLOW.items()):
            print(f"{token}\n    {reason}")
        return 0

    problems, files, candidates = check()

    if files < MIN_CLAUDE_FILES or candidates < MIN_CANDIDATES:
        print(
            f"::error::scanned {files} CLAUDE.md file(s) and {candidates} path "
            f"reference(s) -- below the {MIN_CLAUDE_FILES}/{MIN_CANDIDATES} floor, "
            f"so the scan is broken, not clean",
            file=sys.stderr,
        )
        return 2

    print(
        f"CLAUDE.md path refs: {candidates} reference(s) across {files} file(s), "
        f"{len(_ALLOW)} declared exception(s)"
    )
    if problems:
        for path, lineno, token in problems:
            rel = path.relative_to(ROOT).as_posix()
            print(
                f"::error file={rel},line={lineno}::{rel}:{lineno}: `{token}` does not "
                f"exist anywhere in the repo",
                file=sys.stderr,
            )
        print(
            f"\n{len(problems)} dead path reference(s). Fix the reference, or -- if the "
            f"path is intentionally absent -- add it to _ALLOW in "
            f"scripts/check_claude_refs.py with the reason.",
            file=sys.stderr,
        )
        return 1
    print("  OK -- every path a CLAUDE.md names exists.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
