"""Regenerate scripts/coverage_baseline.json from a coverage.xml.

Usage:
    python scripts/regen_coverage_baseline.py packages/python/goldenmatch/coverage.xml

Run this when the gate tells you to: a module was added, removed or renamed, or
coverage improved and you want the new level locked in. It is deliberately a
separate command rather than something the gate does for itself -- a gate that
rewrites its own expectations cannot fail.

Ratcheting is ONE-WAY by default: a module's recorded rate never decreases, so
regenerating after an accidental drop does not quietly bless it. Pass
`--allow-lower` for a deliberate, explained reduction (deleting tests for a
retired feature, say).
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from coverage_baseline import (  # noqa: E402
    BASELINE_PATH,
    overall_rate,
    parse_report,
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("coverage_xml", type=Path)
    ap.add_argument(
        "--allow-lower",
        action="store_true",
        help="permit recording a LOWER rate than the current baseline "
             "(default: ratchet up only)",
    )
    args = ap.parse_args()

    if not args.coverage_xml.exists():
        print(f"coverage.xml not found: {args.coverage_xml}", file=sys.stderr)
        return 2

    measured = parse_report(args.coverage_xml)
    if not measured:
        print("coverage report contains no modules -- refusing to write an "
              "empty baseline (this would disable the gate entirely).",
              file=sys.stderr)
        return 2

    old_modules: dict[str, dict] = {}
    if BASELINE_PATH.exists():
        old_modules = json.loads(BASELINE_PATH.read_text(encoding="utf-8")).get("modules", {})

    modules: dict[str, dict] = {}
    lowered: list[str] = []
    raised = added = 0
    for name, info in sorted(measured.items()):
        prev = old_modules.get(name)
        rate = info["rate"]
        if prev is None:
            added += 1
        elif rate < prev["rate"]:
            if args.allow_lower:
                lowered.append(f"{name}: {prev['rate']:.1%} -> {rate:.1%}")
            else:
                rate = prev["rate"]  # ratchet: keep the higher recorded value
        elif rate > prev["rate"]:
            raised += 1
        modules[name] = {"rate": rate, "statements": info["statements"]}

    removed = sorted(set(old_modules) - set(measured))

    payload = {
        "_meta": {
            "generated": dt.date.today().isoformat(),
            "overall": round(overall_rate(args.coverage_xml), 4),
            "module_count": len(modules),
            "note": (
                "Generated by scripts/regen_coverage_baseline.py. Every measured "
                "module is recorded so a regression anywhere fails, not only in "
                "the curated table in check_coverage_floors.py. Ratchets upward "
                "only unless --allow-lower is passed."
            ),
        },
        "modules": modules,
    }
    BASELINE_PATH.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n",
                             encoding="utf-8")

    print(f"wrote {BASELINE_PATH.name}: {len(modules)} modules, "
          f"overall {payload['_meta']['overall']:.1%}")
    print(f"  added {added}, ratcheted up {raised}, removed {len(removed)}")
    for name in removed:
        print(f"  - dropped (no longer measured): {name}")
    for line in lowered:
        print(f"  ! LOWERED: {line}")
    if lowered:
        print("\n--allow-lower was used. State why in the commit message.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
