"""5M scale audit runner — DuckDB backend lane.

Loads a synthetic 5M CSV (generated by ``scale_audit_5m_generate.py``),
runs zero-config dedupe via the DuckDB backend, and emits a JSON +
markdown report.

Measures:

- Wall clock, total
- Per-stage timing via the controller telemetry
- Peak RSS (psutil polling, since GH runners don't carry
  ``/usr/bin/time`` consistently across distros)
- Cluster count + member-count distribution (P50/P95/P99)
- Pair-based F1 against the synthetic ground truth

Usage::

    python scripts/scale_audit_5m.py \\
        --fixture tests/benchmarks/datasets/synthetic_5m.csv \\
        --ground-truth tests/benchmarks/datasets/synthetic_5m.ground_truth.csv \\
        --output .profile_tmp/scale_audit_5m_result.json \\
        --summary-md .profile_tmp/scale_audit_5m_summary.md
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import threading
import time
from pathlib import Path

# Force cross-run autoconfig memory off so the numbers are clean.
os.environ.setdefault("GOLDENMATCH_AUTOCONFIG_MEMORY", "0")


def _poll_rss_mb(stop_event: threading.Event, peak: list[float]) -> None:
    """Background thread polling current-process RSS every 0.5s.

    No-op when ``psutil`` isn't installed — peak stays at 0.0.
    """
    try:
        import psutil
    except ImportError:
        return
    proc = psutil.Process(os.getpid())
    while not stop_event.is_set():
        try:
            rss_mb = proc.memory_info().rss / 1024 / 1024
            if rss_mb > peak[0]:
                peak[0] = rss_mb
        except Exception:
            pass
        stop_event.wait(0.5)


def _percentile(sorted_values: list[int], p: float) -> int:
    if not sorted_values:
        return 0
    idx = max(0, int(p * len(sorted_values)) - 1)
    return sorted_values[idx]


def _pairs_from_ground_truth(gt_path: Path) -> set[tuple[int, int]]:
    """Convert ``id,cluster_id`` ground truth to canonical pair set.

    Groups by ``cluster_id``, expands each cluster of size >= 2 into
    sorted ``(row_a, row_b)`` pairs. Converts the 1-based ``id`` column
    to 0-based row indices so the pair set aligns with GoldenMatch's
    internal ``__row_id__`` space (which is what ``cluster.members``
    holds).
    """
    from itertools import combinations

    import polars as pl

    df = pl.read_csv(gt_path)
    pairs: set[tuple[int, int]] = set()
    for (_cid,), group in df.group_by("cluster_id"):
        # id is 1-based row order; __row_id__ is 0-based.
        ids = sorted(int(i) - 1 for i in group["id"].to_list())
        if len(ids) < 2:
            continue
        for a, b in combinations(ids, 2):
            pairs.add((a, b))
    return pairs


def run_audit(
    fixture: Path,
    ground_truth: Path,
    output_json: Path,
    summary_md: Path | None,
) -> dict:
    import goldenmatch as gm
    import polars as pl
    from goldenmatch.core.evaluate import evaluate_clusters

    print(f"Loading fixture {fixture}...")
    t_load_start = time.time()
    df = pl.read_csv(fixture, ignore_errors=True, infer_schema_length=0)
    t_load = time.time() - t_load_start
    print(f"Loaded {df.height:,} rows × {df.width} cols in {t_load:.1f}s")

    # Drop ground-truth-only column so it doesn't leak into the matcher.
    if "cluster_id" in df.columns:
        df = df.drop("cluster_id")

    print("Computing ground-truth pair set...")
    t_gt_start = time.time()
    truth_pairs = _pairs_from_ground_truth(ground_truth)
    t_gt = time.time() - t_gt_start
    print(f"Loaded {len(truth_pairs):,} ground-truth pairs in {t_gt:.1f}s")

    # Peak-RSS poller in a background thread.
    peak_rss = [0.0]
    stop = threading.Event()
    poller = threading.Thread(target=_poll_rss_mb, args=(stop, peak_rss), daemon=True)
    poller.start()

    print("Auto-configuring (GoldenCheck quality scan disabled — not what we're benchmarking)...")
    config = gm.auto_configure_df(df)
    config.backend = "duckdb"
    if config.quality is not None:
        config.quality.mode = "disabled"
    else:
        from goldenmatch.config.schemas import QualityConfig
        config.quality = QualityConfig(mode="disabled")

    print("Running dedupe (backend=duckdb)...")
    # Capture per-stage wall + pair-count accounting under the bench
    # harness (no cost when no recorder is pushed; we push one here).
    from goldenmatch.core.bench import bench_capture
    t_dedupe_start = time.time()
    with bench_capture() as bench:
        result = gm.dedupe_df(df, config=config)
    t_dedupe = time.time() - t_dedupe_start
    stop.set()
    poller.join(timeout=1.0)
    print(f"Dedupe done in {t_dedupe:.1f}s. Peak RSS: {peak_rss[0]:,.0f} MB")
    pipeline_bench = bench.to_dict() if bench is not None else {}

    # Cluster size distribution.
    cluster_sizes = sorted(
        (info.get("size", len(info.get("members", []))) for info in result.clusters.values()),
    )
    p50 = _percentile(cluster_sizes, 0.50)
    p95 = _percentile(cluster_sizes, 0.95)
    p99 = _percentile(cluster_sizes, 0.99)
    max_cluster = cluster_sizes[-1] if cluster_sizes else 0
    n_multi_member = sum(1 for s in cluster_sizes if s >= 2)

    # F1 vs ground truth.
    print("Evaluating against ground truth...")
    t_eval_start = time.time()
    eval_result = evaluate_clusters(result.clusters, truth_pairs)
    t_eval = time.time() - t_eval_start
    print(f"F1={eval_result.f1:.4f}  P={eval_result.precision:.4f}  R={eval_result.recall:.4f}  "
          f"TP={eval_result.tp:,} FP={eval_result.fp:,} FN={eval_result.fn:,} ({t_eval:.1f}s)")

    # Per-stage controller telemetry, if available.
    stage_breakdown: dict[str, float] = {}
    try:
        from goldenmatch.core.autoconfig import _LAST_CONTROLLER_RUN
        last = _LAST_CONTROLLER_RUN.get()
        if last is not None:
            _profile, history = last
            committed = history.pick_committed() if history else None
            if committed is not None and getattr(committed, "stage_timings", None):
                stage_breakdown = dict(committed.stage_timings)
    except Exception as exc:  # pragma: no cover — best-effort
        print(f"(stage breakdown unavailable: {exc!r})")

    report = {
        "fixture": str(fixture),
        "n_records": df.height,
        "ground_truth_pairs": len(truth_pairs),
        "load_seconds": round(t_load, 1),
        "ground_truth_load_seconds": round(t_gt, 1),
        "dedupe_seconds": round(t_dedupe, 1),
        "eval_seconds": round(t_eval, 1),
        "peak_rss_mb": round(peak_rss[0], 0),
        "f1": round(eval_result.f1, 4),
        "precision": round(eval_result.precision, 4),
        "recall": round(eval_result.recall, 4),
        "tp": eval_result.tp,
        "fp": eval_result.fp,
        "fn": eval_result.fn,
        "n_clusters": len(result.clusters),
        "n_multi_member_clusters": n_multi_member,
        "cluster_size_p50": p50,
        "cluster_size_p95": p95,
        "cluster_size_p99": p99,
        "cluster_size_max": max_cluster,
        "stage_breakdown_seconds": stage_breakdown,
        "pipeline_bench": pipeline_bench,
        "backend": "duckdb",
    }
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(report, indent=2))
    print(f"Wrote {output_json}")

    if summary_md is not None:
        summary_md.parent.mkdir(parents=True, exist_ok=True)
        md = _render_markdown(report)
        summary_md.write_text(md)
        print(f"Wrote {summary_md}")
        gh_summary = os.environ.get("GITHUB_STEP_SUMMARY")
        if gh_summary:
            Path(gh_summary).write_text(md)
    return report


def _render_markdown(report: dict) -> str:
    lines = [
        "## 5M scale audit — DuckDB backend",
        "",
        f"- **Records:** {report['n_records']:,}",
        f"- **Dedupe wall:** {report['dedupe_seconds']}s ({report['dedupe_seconds']/60:.1f} min)",
        f"- **Peak RSS:** {report['peak_rss_mb']:,.0f} MB",
        f"- **F1 / P / R:** {report['f1']:.4f} / {report['precision']:.4f} / {report['recall']:.4f}",
        f"- **TP/FP/FN:** {report['tp']:,} / {report['fp']:,} / {report['fn']:,}",
        f"- **Clusters:** {report['n_clusters']:,} total, {report['n_multi_member_clusters']:,} multi-member",
        f"- **Cluster size dist:** P50={report['cluster_size_p50']} P95={report['cluster_size_p95']} P99={report['cluster_size_p99']} max={report['cluster_size_max']}",
        "",
    ]
    if report.get("stage_breakdown_seconds"):
        lines.append("### Controller per-iteration breakdown")
        lines.append("")
        for stage_name, secs in report["stage_breakdown_seconds"].items():
            lines.append(f"- {stage_name}: {secs:.1f}s")
        lines.append("")
    bench = report.get("pipeline_bench") or {}
    if bench.get("stage_timings_seconds"):
        lines.append("### Pipeline stage wall (s)")
        lines.append("")
        # Sort descending — biggest wall first, so the bottleneck is at top.
        sorted_stages = sorted(
            bench["stage_timings_seconds"].items(),
            key=lambda kv: kv[1],
            reverse=True,
        )
        for stage_name, secs in sorted_stages:
            lines.append(f"- {stage_name}: {secs:.2f}s")
        lines.append("")
    if bench.get("metrics"):
        lines.append("### Pipeline metrics")
        lines.append("")
        for key, val in sorted(bench["metrics"].items()):
            if isinstance(val, (int, float)):
                lines.append(f"- {key}: {val:,}")
            else:
                lines.append(f"- {key}: {val}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixture", type=Path, required=True)
    parser.add_argument("--ground-truth", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(".profile_tmp/scale_audit_5m_result.json"),
    )
    parser.add_argument(
        "--summary-md",
        type=Path,
        default=Path(".profile_tmp/scale_audit_5m_summary.md"),
    )
    args = parser.parse_args(argv)

    if not args.fixture.exists():
        print(f"FAIL: fixture {args.fixture} does not exist", file=sys.stderr)
        return 1
    if not args.ground_truth.exists():
        print(f"FAIL: ground truth {args.ground_truth} does not exist", file=sys.stderr)
        return 1

    run_audit(args.fixture, args.ground_truth, args.output, args.summary_md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
