// GENERATED by scripts/sync_ts_refdata.mjs from
// packages/python/goldenmatch/goldenmatch/refdata/data/given_name_aliases.json
// Do NOT edit by hand. Run `node scripts/sync_ts_refdata.mjs` to refresh.
// Drift is guarded by tests/unit/refdata-sync.test.ts.
export const GIVEN_NAME_ALIASES = {
  "_meta": {
    "description": "Canonical English given names mapped to their common nicknames/short forms. Curated from public-knowledge naming conventions; no license restrictions. v1: ~140 canonicals covering the most common US given names. Each list is the set of forms commonly used interchangeably for the same person; equivalence is symmetric and transitive within a list.",
    "source": "Hand-curated from common-knowledge English given-name conventions; cross-referenced against US SSA top-given-names lists.",
    "version": "1",
    "last_updated": "2026-05-13"
  },
  "aliases": {
    "abigail": [
      "abby",
      "abbie",
      "gail"
    ],
    "alexander": [
      "alex",
      "al",
      "lex",
      "xander",
      "sandy"
    ],
    "alexandra": [
      "alex",
      "alexa",
      "sandra",
      "sandy",
      "lexi",
      "lexie"
    ],
    "alexis": [
      "lexi",
      "lexie",
      "lex"
    ],
    "alice": [
      "allie",
      "ally",
      "ali"
    ],
    "amanda": [
      "mandy",
      "mandi"
    ],
    "andrew": [
      "andy",
      "drew"
    ],
    "angela": [
      "angie",
      "angel"
    ],
    "anne": [
      "ann",
      "annie",
      "nan",
      "nancy"
    ],
    "anthony": [
      "tony",
      "ant",
      "antonio"
    ],
    "barbara": [
      "barb",
      "barbie",
      "babs"
    ],
    "benjamin": [
      "ben",
      "benny",
      "benji"
    ],
    "bernard": [
      "bernie",
      "bern"
    ],
    "bradley": [
      "brad"
    ],
    "brandon": [
      "brand"
    ],
    "brendan": [
      "bren"
    ],
    "brian": [
      "bryan"
    ],
    "carolyn": [
      "carol",
      "carrie"
    ],
    "catherine": [
      "cathy",
      "kate",
      "katie",
      "katy",
      "cate",
      "kitty"
    ],
    "kathleen": [
      "kathy",
      "kate",
      "katie",
      "kat"
    ],
    "charles": [
      "charlie",
      "chuck",
      "chas",
      "chip"
    ],
    "charlotte": [
      "charlie",
      "lottie",
      "char"
    ],
    "christopher": [
      "chris",
      "topher",
      "kit"
    ],
    "christine": [
      "chris",
      "christy",
      "tina",
      "chrissy"
    ],
    "christina": [
      "chris",
      "tina",
      "christy",
      "chrissy"
    ],
    "claire": [
      "clare"
    ],
    "cynthia": [
      "cindy",
      "cyndi"
    ],
    "daniel": [
      "dan",
      "danny"
    ],
    "david": [
      "dave",
      "davey",
      "davy"
    ],
    "deborah": [
      "deb",
      "debbie",
      "debby"
    ],
    "denise": [
      "dee"
    ],
    "diana": [
      "di"
    ],
    "donald": [
      "don",
      "donnie",
      "donny"
    ],
    "dorothy": [
      "dot",
      "dottie",
      "dotty",
      "dora"
    ],
    "douglas": [
      "doug"
    ],
    "edward": [
      "ed",
      "eddie",
      "ned",
      "ted",
      "teddy"
    ],
    "edwin": [
      "ed",
      "eddie",
      "ned",
      "win"
    ],
    "elizabeth": [
      "liz",
      "lizzie",
      "beth",
      "betty",
      "betsy",
      "eliza",
      "libby"
    ],
    "emily": [
      "em",
      "emmy"
    ],
    "emma": [
      "em",
      "emmie"
    ],
    "eric": [
      "rick",
      "ricky"
    ],
    "eugene": [
      "gene"
    ],
    "florence": [
      "flo",
      "flossie"
    ],
    "francis": [
      "frank",
      "frankie",
      "fran"
    ],
    "francisco": [
      "frank",
      "frankie",
      "paco",
      "pancho",
      "cisco"
    ],
    "franklin": [
      "frank",
      "frankie"
    ],
    "frederick": [
      "fred",
      "freddie",
      "freddy"
    ],
    "gabriel": [
      "gabe"
    ],
    "geoffrey": [
      "geoff",
      "jeff"
    ],
    "george": [
      "georgie"
    ],
    "gerald": [
      "gerry",
      "jerry"
    ],
    "gregory": [
      "greg",
      "gregg"
    ],
    "harold": [
      "hal",
      "harry"
    ],
    "harriet": [
      "hattie",
      "hetty"
    ],
    "henry": [
      "hank",
      "hal",
      "harry"
    ],
    "isabella": [
      "isa",
      "bella",
      "izzy"
    ],
    "jacob": [
      "jake"
    ],
    "james": [
      "jim",
      "jimmy",
      "jamie",
      "jay"
    ],
    "janet": [
      "jan",
      "jenny"
    ],
    "janice": [
      "jan",
      "jen"
    ],
    "jasper": [
      "jas"
    ],
    "jean": [
      "jeannie",
      "jeanie"
    ],
    "jeffrey": [
      "jeff",
      "geoff"
    ],
    "jennifer": [
      "jen",
      "jenny",
      "jenn"
    ],
    "jeremy": [
      "jem",
      "jerry"
    ],
    "jessica": [
      "jess",
      "jessie",
      "jessi"
    ],
    "joan": [
      "joanie"
    ],
    "joanne": [
      "jo",
      "joey"
    ],
    "johanna": [
      "jo",
      "hannah"
    ],
    "john": [
      "jack",
      "johnny",
      "jon",
      "jonny"
    ],
    "jonathan": [
      "jon",
      "john",
      "jonny",
      "nathan",
      "nat"
    ],
    "joseph": [
      "joe",
      "joey",
      "jos"
    ],
    "joshua": [
      "josh"
    ],
    "judith": [
      "judy",
      "jude"
    ],
    "julia": [
      "julie",
      "jules"
    ],
    "julian": [
      "jules"
    ],
    "kaitlyn": [
      "kate",
      "katie",
      "kat",
      "kaitie"
    ],
    "kenneth": [
      "ken",
      "kenny"
    ],
    "kimberly": [
      "kim",
      "kimmy"
    ],
    "kristine": [
      "kris",
      "kristy",
      "krissy"
    ],
    "lawrence": [
      "larry",
      "lawrie",
      "lonnie"
    ],
    "leonard": [
      "leo",
      "lenny",
      "len"
    ],
    "leslie": [
      "les"
    ],
    "lillian": [
      "lily",
      "lil"
    ],
    "lincoln": [
      "linc"
    ],
    "lindsey": [
      "lin",
      "lindsay"
    ],
    "louis": [
      "lou",
      "louie"
    ],
    "louise": [
      "lou",
      "lulu",
      "lula"
    ],
    "lucas": [
      "luke"
    ],
    "madeline": [
      "maddie",
      "maddy",
      "lena"
    ],
    "madison": [
      "maddie",
      "maddy"
    ],
    "margaret": [
      "maggie",
      "meg",
      "peggy",
      "peg",
      "marge",
      "margie",
      "madge",
      "greta"
    ],
    "marilyn": [
      "mary",
      "lyn"
    ],
    "martin": [
      "marty",
      "mart"
    ],
    "matthew": [
      "matt",
      "matty"
    ],
    "maxwell": [
      "max"
    ],
    "melanie": [
      "mel"
    ],
    "melissa": [
      "mel",
      "missy",
      "lissa"
    ],
    "michael": [
      "mike",
      "mick",
      "mickey",
      "mikey"
    ],
    "michelle": [
      "shelly",
      "mich"
    ],
    "nancy": [
      "nan",
      "nance"
    ],
    "natalie": [
      "nat",
      "tally"
    ],
    "nathaniel": [
      "nat",
      "nate"
    ],
    "nicholas": [
      "nick",
      "nicky",
      "cole"
    ],
    "nicole": [
      "nikki",
      "nicki"
    ],
    "norman": [
      "norm",
      "normie"
    ],
    "oliver": [
      "ollie",
      "oli"
    ],
    "patricia": [
      "pat",
      "patty",
      "patsy",
      "tricia",
      "trish"
    ],
    "patrick": [
      "pat",
      "paddy",
      "rick"
    ],
    "paul": [
      "paulie",
      "pauly"
    ],
    "peter": [
      "pete",
      "petey"
    ],
    "philip": [
      "phil",
      "pip"
    ],
    "phillip": [
      "phil",
      "pip"
    ],
    "rachel": [
      "rae"
    ],
    "ralph": [
      "ralphie"
    ],
    "rebecca": [
      "becky",
      "becca",
      "beck",
      "reba"
    ],
    "regina": [
      "reggie",
      "gina"
    ],
    "reginald": [
      "reg",
      "reggie"
    ],
    "richard": [
      "rick",
      "ricky",
      "rich",
      "dick",
      "dicky"
    ],
    "robert": [
      "rob",
      "bob",
      "bobby",
      "robby",
      "robbie"
    ],
    "roberta": [
      "bobbi",
      "bobbie",
      "berta"
    ],
    "ronald": [
      "ron",
      "ronny",
      "ronnie"
    ],
    "rosemary": [
      "rose",
      "rosie",
      "marie"
    ],
    "russell": [
      "russ"
    ],
    "samantha": [
      "sam",
      "sammie",
      "sammy"
    ],
    "samuel": [
      "sam",
      "sammy",
      "sammie"
    ],
    "sandra": [
      "sandy",
      "sandi"
    ],
    "sarah": [
      "sara",
      "sally"
    ],
    "sebastian": [
      "seb",
      "bash"
    ],
    "shannon": [
      "shan"
    ],
    "sharon": [
      "shari"
    ],
    "sheldon": [
      "shel"
    ],
    "stephanie": [
      "steph",
      "steffi",
      "stevie"
    ],
    "stephen": [
      "steve",
      "stevie"
    ],
    "steven": [
      "steve",
      "stevie"
    ],
    "susan": [
      "sue",
      "susie",
      "suzy"
    ],
    "suzanne": [
      "sue",
      "susie",
      "suzy",
      "suzi"
    ],
    "sylvester": [
      "sly"
    ],
    "terence": [
      "terry"
    ],
    "theodore": [
      "ted",
      "teddy",
      "theo"
    ],
    "thomas": [
      "tom",
      "tommy"
    ],
    "timothy": [
      "tim",
      "timmy"
    ],
    "valerie": [
      "val"
    ],
    "veronica": [
      "roni",
      "ronnie",
      "ronni"
    ],
    "victoria": [
      "vicki",
      "vicky",
      "vickie",
      "tori"
    ],
    "vincent": [
      "vince",
      "vinny",
      "vin"
    ],
    "virginia": [
      "ginny",
      "ginger"
    ],
    "walter": [
      "walt",
      "wally"
    ],
    "wendy": [
      "wen"
    ],
    "william": [
      "will",
      "willy",
      "willie",
      "bill",
      "billy",
      "liam"
    ],
    "winston": [
      "winnie",
      "win"
    ],
    "yvonne": [
      "vonnie"
    ],
    "zachary": [
      "zach",
      "zack",
      "zac"
    ]
  }
} as const;
