#!/usr/bin/env python3
"""Synthetic labeled record-pair generator for the OSS ER-matcher (P1).

Emits JSONL rows ``{a, b, label, domain, source, eid_a, eid_b}`` for SFT:
  - label "match": a synthetic entity vs a realistically CORRUPTED copy of itself
    (typos, case, whitespace, nicknames, abbreviations, dropped fields,
    phone/email reformatting) -- the seeds are generated by us, so there is NO
    license to violate (spec 2026-07-26 §7: synthetic-first).
  - label "no_match" (easy): two clearly different entities.
  - label "no_match" (hard): two DIFFERENT entities that look deceptively similar
    (shared surname / near-twin name but conflicting strong identifiers) -- the
    close-but-distinct boundary the model most needs. (FS-pipeline-mined hard
    negatives are a P1b enhancement; these are the deterministic synthetic ones.)

Guarantees (locked by test_gen_pairs.py):
  - Deterministic: same --seed -> byte-identical output.
  - Entity-level splits: no entity appears in two splits; negatives only pair
    entities within the SAME split; one --holdout-domain is fully reserved to
    `test` to measure cross-domain generalization.
  - Balanced: ~50/50 match/no_match; a configurable share of no_match is hard.

Pure stdlib. Reuses the corruption ideas from tests/generate_synthetic.py.
"""
from __future__ import annotations

import argparse
import json
import random
import string
from pathlib import Path
from typing import Any

from sources.splits import split_of

# --- vendored compact reference data (stdlib-only; no faker) ----------------
FIRST = [
    "John", "Jane", "Robert", "Mary", "James", "Patricia", "Michael", "Jennifer",
    "William", "Linda", "David", "Elizabeth", "Richard", "Barbara", "Joseph",
    "Susan", "Thomas", "Jessica", "Charles", "Sarah", "Daniel", "Nancy",
    "Matthew", "Lisa", "Anthony", "Margaret", "Mark", "Sandra", "Steven", "Emily",
]
LAST = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
    "Rodriguez", "Martinez", "Wilson", "Anderson", "Taylor", "Moore", "Jackson",
    "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Clark", "Lewis",
    "Walker", "Young", "Allen", "King", "Wright", "Scott", "Nguyen",
]
# Nicknames are a load-bearing ER signal (same entity, very different string).
NICKS = {
    "Robert": ["Bob", "Rob", "Bobby"], "William": ["Bill", "Will", "Billy"],
    "Richard": ["Rick", "Dick", "Rich"], "James": ["Jim", "Jimmy"],
    "Michael": ["Mike", "Mickey"], "Joseph": ["Joe", "Joey"],
    "Charles": ["Charlie", "Chuck"], "Thomas": ["Tom", "Tommy"],
    "Elizabeth": ["Liz", "Beth", "Betty"], "Jennifer": ["Jen", "Jenny"],
    "Patricia": ["Pat", "Patty"], "Margaret": ["Peg", "Maggie"],
    "Jessica": ["Jess"], "Daniel": ["Dan", "Danny"], "Matthew": ["Matt"],
    "Anthony": ["Tony"], "Steven": ["Steve"],
}
EMAIL_HOSTS = ["gmail.com", "yahoo.com", "outlook.com", "aol.com", "proton.me"]
STREETS = ["Main St", "Oak Ave", "Elm Blvd", "Pine Dr", "Maple Ln", "Cedar Rd", "Walnut Way"]
CITIES = ["Philadelphia", "Newark", "Wilmington", "Baltimore", "Hartford", "Richmond", "Trenton"]
STATES = ["PA", "NJ", "NY", "DE", "MD", "CT", "VA", "OH"]
SPECIALTIES = ["Cardiology", "Oncology", "Neurology", "Pediatrics", "Radiology", "Urology"]
BIZ_WORDS = ["Acme", "Globex", "Initech", "Umbrella", "Soylent", "Stark", "Wayne", "Wonka"]
BIZ_SUFFIX = ["Inc", "LLC", "Corp", "Group", "Co", "Holdings"]

DOMAINS = ("people", "healthcare", "business")


def _phone(rng: random.Random) -> str:
    return f"{rng.randint(200,989)}-{rng.randint(200,989)}-{rng.randint(1000,9999)}"


def _make_entity(rng: random.Random, eid: int, domain: str) -> dict[str, Any]:
    """Generate one canonical synthetic entity for a domain."""
    if domain == "healthcare":
        f, l = rng.choice(FIRST), rng.choice(LAST)
        return {
            "first_name": f, "last_name": l,
            "npi": str(rng.randint(1_000_000_000, 1_999_999_999)),
            "specialty": rng.choice(SPECIALTIES),
            "phone": _phone(rng), "state": rng.choice(STATES),
        }
    if domain == "business":
        name = f"{rng.choice(BIZ_WORDS)} {rng.choice(BIZ_WORDS)} {rng.choice(BIZ_SUFFIX)}"
        slug = name.lower().replace(" ", "")
        return {
            "name": name, "email": f"info@{slug}.com", "phone": _phone(rng),
            "city": rng.choice(CITIES), "state": rng.choice(STATES),
            "website": f"https://www.{slug}.com",
        }
    f, l = rng.choice(FIRST), rng.choice(LAST)
    return {
        "first_name": f, "last_name": l,
        "email": f"{f.lower()}.{l.lower()}{rng.randint(1,499)}@{rng.choice(EMAIL_HOSTS)}",
        "phone": _phone(rng), "city": rng.choice(CITIES),
        "state": rng.choice(STATES), "zip": str(rng.randint(10000, 99999)),
    }


# --- corruption (applied only to entities we generated) ---------------------
def _typo(rng: random.Random, s: str) -> str:
    if len(s) > 3:
        i = rng.randint(1, len(s) - 2)
        return s[:i] + rng.choice(string.ascii_lowercase) + s[i + 1:]
    return s


def _reformat_phone(rng: random.Random, s: str) -> str:
    d = "".join(ch for ch in s if ch.isdigit())
    if len(d) < 10:
        return s
    return rng.choice([d, f"({d[:3]}) {d[3:6]}-{d[6:]}", f"{d[:3]}.{d[3:6]}.{d[6:]}", f"+1{d}"])


def _corrupt(rng: random.Random, entity: dict[str, Any]) -> dict[str, Any]:
    """Return a realistically messy COPY of a match (same real entity)."""
    rec = dict(entity)
    ops = rng.randint(1, 3)
    keys = list(rec.keys())
    for _ in range(ops):
        k = rng.choice(keys)
        v = rec[k]
        if not isinstance(v, str) or not v:
            continue
        choice = rng.random()
        if k == "first_name" and v in NICKS and choice < 0.5:
            rec[k] = rng.choice(NICKS[v])                       # nickname
        elif "phone" in k:
            rec[k] = _reformat_phone(rng, v)                    # phone reformat
        elif choice < 0.25:
            rec[k] = v.upper() if rng.random() < 0.5 else v.lower()   # case
        elif choice < 0.5:
            rec[k] = (" " * rng.randint(1, 3)) + v              # whitespace
        elif choice < 0.75:
            rec[k] = _typo(rng, v)                              # typo
        else:
            rec.pop(k, None)                                    # dropped field (one-sided)
            keys = list(rec.keys())
            if not keys:
                break
    return rec


# --- pair construction ------------------------------------------------------
def _strong_id_keys(domain: str) -> list[str]:
    return {"people": ["email", "phone"], "healthcare": ["npi", "phone"],
            "business": ["email", "website", "phone"]}[domain]


def _hard_negative(rng: random.Random, a: dict[str, Any], b: dict[str, Any],
                   domain: str) -> dict[str, Any]:
    """Make B look deceptively like A (share the weak/name fields) while KEEPING
    B's own conflicting strong identifiers -> a true no_match at the boundary."""
    b2 = dict(b)
    if domain == "business":
        b2["name"] = a.get("name", b2.get("name"))            # same displayed name...
    else:
        # same surname (and sometimes same given name) -> namesake collision.
        b2["last_name"] = a.get("last_name", b2.get("last_name"))
        if rng.random() < 0.5:
            b2["first_name"] = a.get("first_name", b2.get("first_name"))
    # ...but strong ids stay B's own (the conflict that makes it a real no_match).
    return b2


def _pair_row(a: dict, b: dict, label: str, domain: str, source: str,
              eid_a: int, eid_b: int) -> dict[str, Any]:
    return {"a": a, "b": b, "label": label, "domain": domain, "source": source,
            "eid_a": eid_a, "eid_b": eid_b}


def _split_of(eid: int, domain: str, seed: int, val_frac: float, test_frac: float,
              holdout_domain: str | None) -> str:
    """Deterministic entity-level split. The holdout domain is fully reserved to
    `test` (cross-domain generalization); all other entities hash into
    train/val/test by a stable digest of (seed, eid). Thin wrapper: delegates to
    the shared `sources.splits.split_of` helper (DRY) without changing behavior."""
    return split_of(eid, seed=seed, val_frac=val_frac, test_frac=test_frac,
                     holdout_domain=holdout_domain, domain=domain)


def generate_dataset(
    n_entities: int = 3000, seed: int = 20260726, val_frac: float = 0.15,
    test_frac: float = 0.15, hard_neg_frac: float = 0.5,
    holdout_domain: str | None = "business",
) -> dict[str, list[dict[str, Any]]]:
    """Return {split: [pair rows]}. ~50/50 match/no_match; `hard_neg_frac` of the
    negatives are boundary hard-negatives. Fully deterministic in `seed`."""
    rng = random.Random(seed)
    # 1. entities, each tagged with a domain + a precomputed split.
    entities: list[dict[str, Any]] = []
    by_split_domain: dict[tuple[str, str], list[int]] = {}
    for eid in range(n_entities):
        domain = DOMAINS[eid % len(DOMAINS)]
        ent = _make_entity(rng, eid, domain)
        split = _split_of(eid, domain, seed, val_frac, test_frac, holdout_domain)
        entities.append({"eid": eid, "domain": domain, "split": split, "rec": ent})
        by_split_domain.setdefault((split, domain), []).append(eid)

    out: dict[str, list[dict[str, Any]]] = {"train": [], "val": [], "test": []}
    for ent in entities:
        eid, domain, split, rec = ent["eid"], ent["domain"], ent["split"], ent["rec"]
        # one positive per entity (canonical vs corrupted self).
        out[split].append(_pair_row(rec, _corrupt(rng, rec), "match", domain,
                                    "synthetic", eid, eid))
        # one negative per entity, paired with another entity IN THE SAME split+domain.
        pool = [x for x in by_split_domain.get((split, domain), []) if x != eid]
        if not pool:
            continue
        other = entities[rng.choice(pool)]["rec"]
        if rng.random() < hard_neg_frac:
            b = _hard_negative(rng, rec, other, domain)
            out[split].append(_pair_row(rec, b, "no_match", domain, "synthetic_hard", eid,
                                        _hard_neg_eid(entities, other)))
        else:
            out[split].append(_pair_row(rec, other, "no_match", domain, "synthetic_easy",
                                        eid, _hard_neg_eid(entities, other)))
    return out


def _hard_neg_eid(entities: list[dict], rec: dict) -> int:
    for e in entities:
        if e["rec"] is rec:
            return e["eid"]
    return -1


def _write(out: dict[str, list[dict]], out_dir: Path, config: dict) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    counts: dict[str, Any] = {}
    for split, rows in out.items():
        path = out_dir / f"{split}.jsonl"
        with path.open("w", encoding="utf-8") as fh:
            for r in rows:
                fh.write(json.dumps(r, sort_keys=True, ensure_ascii=True) + "\n")
        labels: dict[str, int] = {}
        sources: dict[str, int] = {}
        for r in rows:
            labels[r["label"]] = labels.get(r["label"], 0) + 1
            sources[r["source"]] = sources.get(r["source"], 0) + 1
        counts[split] = {"n": len(rows), "labels": labels, "sources": sources}
    manifest = {"config": config, "counts": counts,
                "serializer_version": _serializer_version()}
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True))
    return manifest


def _serializer_version() -> str:
    try:
        from goldenmatch.core.er_matcher import SERIALIZER_VERSION
        return SERIALIZER_VERSION
    except Exception:
        return "unknown"


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description="Generate synthetic ER-matcher training pairs.")
    ap.add_argument("--n-entities", type=int, default=3000)
    ap.add_argument("--seed", type=int, default=20260726)
    ap.add_argument("--val-frac", type=float, default=0.15)
    ap.add_argument("--test-frac", type=float, default=0.15)
    ap.add_argument("--hard-neg-frac", type=float, default=0.5)
    ap.add_argument("--holdout-domain", default="business",
                    help="Domain fully reserved to the test split (or 'none').")
    ap.add_argument("--out-dir", type=Path, default=Path("data/er_matcher"))
    args = ap.parse_args(argv)
    holdout = None if args.holdout_domain == "none" else args.holdout_domain
    config = {
        "n_entities": args.n_entities, "seed": args.seed, "val_frac": args.val_frac,
        "test_frac": args.test_frac, "hard_neg_frac": args.hard_neg_frac,
        "holdout_domain": holdout,
    }
    out = generate_dataset(**{k: config[k] for k in (
        "n_entities", "seed", "val_frac", "test_frac", "hard_neg_frac")},
        holdout_domain=holdout)
    manifest = _write(out, args.out_dir, config)
    print(json.dumps(manifest["counts"], indent=2))


if __name__ == "__main__":
    main()
