/**
 * Format-canonical golden strategies (Phase 5 Part 2 of N -- closes
 * the next 7 of 22 plugins from goldenmatch issue #208).
 *
 * Parity contract: byte-identical output with Python's
 * `goldenmatch.plugins.builtin.format` for fixed inputs. Fixtures
 * generated by `scripts/generate_parity_fixtures.py`.
 */

import type {
  GoldenStrategyMergeOpts,
  GoldenStrategyPlugin,
  GoldenStrategyResult,
} from "../base.js";

// Mirrors Python's `_EMAIL_PLUS_RE`. Anchored at start so it only
// matches well-formed local+suffix@domain shapes.
const EMAIL_PLUS_RE = /^([^+@]+)\+[^@]*(@.+)$/;
// Mirrors Python's `_NON_DIGIT_RE`. The `g` flag matches re.sub semantics.
const NON_DIGIT_RE = /\D+/g;
// Mirrors Python's `_URL_RE` (scheme://host[rest]).
// `rest` must START with a path/query/fragment delimiter (or be absent) so it
// can't overlap with `host`'s character class. The earlier `(?<host>[^/?#]+)`
// + `(?<rest>.*)` pair had two adjacent quantifiers matching the same chars,
// which CodeQL flags as polynomial-ReDoS (js/polynomial-redos #303). This form
// is unambiguous (linear) and matches the exact same set of strings.
const URL_RE =
  /^(?<scheme>[a-zA-Z][a-zA-Z0-9+.-]*:\/\/)(?<host>[^/?#]+)(?<rest>[/?#].*)?$/;
const WHITESPACE_RE = /\s+/g;
const BOOL_TRUTHY = new Set(["true", "t", "yes", "y", "1", "on"]);
const BOOL_FALSY = new Set(["false", "f", "no", "n", "0", "off"]);

/** Python's `str(v)` -- coerce any value to string. */
function pyStr(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "boolean") return value ? "True" : "False";
  return String(value);
}

/** Python `Counter.most_common(1)` -- first-inserted key wins ties. */
function mostCommon(items: ReadonlyArray<string>): { key: string; count: number } {
  const counts = new Map<string, number>();
  for (const item of items) {
    counts.set(item, (counts.get(item) ?? 0) + 1);
  }
  let bestKey: string | null = null;
  let bestCount = -1;
  for (const [key, count] of counts) {
    if (count > bestCount) {
      bestCount = count;
      bestKey = key;
    }
  }
  return { key: bestKey ?? "", count: bestCount };
}

export class ShortestValueStrategy implements GoldenStrategyPlugin {
  readonly name = "shortest_value";

  merge(
    values: ReadonlyArray<unknown>,
    opts: GoldenStrategyMergeOpts = {},
  ): GoldenStrategyResult {
    const nonNull: Array<{ idx: number; raw: unknown; s: string }> = [];
    for (let i = 0; i < values.length; i++) {
      const v = values[i];
      if (v === null || v === undefined) continue;
      nonNull.push({ idx: i, raw: v, s: pyStr(v) });
    }
    if (nonNull.length === 0) return [null, 0.0] as const;
    let minLen = nonNull[0]!.s.length;
    for (let i = 1; i < nonNull.length; i++) {
      if (nonNull[i]!.s.length < minLen) minLen = nonNull[i]!.s.length;
    }
    const shortest = nonNull.filter((x) => x.s.length === minLen);
    if (shortest.length === 1) {
      return [shortest[0]!.raw, 1.0, shortest[0]!.idx] as const;
    }
    const weights = opts.qualityWeights;
    if (weights !== undefined) {
      let bestIdx = 0;
      let bestWeight = -Infinity;
      for (let i = 0; i < shortest.length; i++) {
        const sIdx = shortest[i]!.idx;
        const w = sIdx < weights.length ? Number(weights[sIdx]) : 1.0;
        if (w > bestWeight) {
          bestWeight = w;
          bestIdx = i;
        }
      }
      const best = shortest[bestIdx]!;
      return [best.raw, 0.7, best.idx] as const;
    }
    return [shortest[0]!.raw, 0.5, shortest[0]!.idx] as const;
  }
}

export class ConcatUniqueStrategy implements GoldenStrategyPlugin {
  readonly name = "concat_unique";

  merge(
    values: ReadonlyArray<unknown>,
    opts: GoldenStrategyMergeOpts = {},
  ): GoldenStrategyResult {
    const nonNull: string[] = [];
    for (const v of values) {
      if (v === null || v === undefined) continue;
      const s = pyStr(v);
      if (s === "") continue;
      nonNull.push(s);
    }
    if (nonNull.length === 0) return [null, 0.0] as const;
    const sep =
      (opts.ruleKwargs?.["separator"] as string | undefined) ?? ", ";
    const uniqueSorted = Array.from(new Set(nonNull)).sort();
    return [uniqueSorted.join(sep), 1.0, 0] as const;
  }
}

function canonicalizeEmail(value: string): string {
  const v = value.trim().toLowerCase();
  const match = v.match(EMAIL_PLUS_RE);
  if (match) {
    return match[1]! + match[2]!;
  }
  return v;
}

export class EmailNormalizeStrategy implements GoldenStrategyPlugin {
  readonly name = "email_normalize";

  merge(
    values: ReadonlyArray<unknown>,
    _opts?: GoldenStrategyMergeOpts,
  ): GoldenStrategyResult {
    const nonNull: Array<{ idx: number; s: string }> = [];
    for (let i = 0; i < values.length; i++) {
      const v = values[i];
      if (v === null || v === undefined) continue;
      nonNull.push({ idx: i, s: pyStr(v) });
    }
    if (nonNull.length === 0) return [null, 0.0] as const;
    const normalized = nonNull.map((x) => ({ idx: x.idx, n: canonicalizeEmail(x.s) }));
    const { key: winner, count } = mostCommon(normalized.map((x) => x.n));
    const firstIdx = normalized.find((x) => x.n === winner)!.idx;
    return [winner, count / nonNull.length, firstIdx] as const;
  }
}

export class PhoneDigitsOnlyStrategy implements GoldenStrategyPlugin {
  readonly name = "phone_digits_only";

  merge(
    values: ReadonlyArray<unknown>,
    _opts?: GoldenStrategyMergeOpts,
  ): GoldenStrategyResult {
    const nonNull: Array<{ idx: number; s: string }> = [];
    for (let i = 0; i < values.length; i++) {
      const v = values[i];
      if (v === null || v === undefined) continue;
      nonNull.push({ idx: i, s: pyStr(v) });
    }
    if (nonNull.length === 0) return [null, 0.0] as const;
    const stripped: Array<{ idx: number; d: string }> = [];
    for (const x of nonNull) {
      const d = x.s.replace(NON_DIGIT_RE, "");
      if (d) stripped.push({ idx: x.idx, d });
    }
    if (stripped.length === 0) return [null, 0.0] as const;
    let maxLen = stripped[0]!.d.length;
    for (let i = 1; i < stripped.length; i++) {
      if (stripped[i]!.d.length > maxLen) maxLen = stripped[i]!.d.length;
    }
    const tied = stripped.filter((x) => x.d.length === maxLen);
    const conf = tied.length === 1 ? 1.0 : 0.7;
    return [tied[0]!.d, conf, tied[0]!.idx] as const;
  }
}

function canonicalizeUrl(value: string): string {
  const v = value.trim();
  const match = v.match(URL_RE);
  if (!match) return v;
  let scheme = (match.groups!["scheme"] as string).toLowerCase();
  if (scheme === "http://") scheme = "https://";
  const host = (match.groups!["host"] as string).toLowerCase();
  // `rest` is an optional group now (absent on bare `scheme://host`).
  let rest = (match.groups!["rest"] as string | undefined) ?? "";
  if (rest === "/") {
    rest = "";
  } else if (
    rest.endsWith("/") &&
    !rest.includes("?") &&
    !rest.includes("#")
  ) {
    rest = rest.slice(0, -1);
  }
  return scheme + host + rest;
}

export class UrlCanonicalStrategy implements GoldenStrategyPlugin {
  readonly name = "url_canonical";

  merge(
    values: ReadonlyArray<unknown>,
    _opts?: GoldenStrategyMergeOpts,
  ): GoldenStrategyResult {
    const nonNull: Array<{ idx: number; s: string }> = [];
    for (let i = 0; i < values.length; i++) {
      const v = values[i];
      if (v === null || v === undefined) continue;
      nonNull.push({ idx: i, s: pyStr(v) });
    }
    if (nonNull.length === 0) return [null, 0.0] as const;
    const normalized = nonNull.map((x) => ({ idx: x.idx, n: canonicalizeUrl(x.s) }));
    const { key: winner, count } = mostCommon(normalized.map((x) => x.n));
    const firstIdx = normalized.find((x) => x.n === winner)!.idx;
    return [winner, count / nonNull.length, firstIdx] as const;
  }
}

export class WhitespaceNormalizeStrategy implements GoldenStrategyPlugin {
  readonly name = "whitespace_normalize";

  merge(
    values: ReadonlyArray<unknown>,
    _opts?: GoldenStrategyMergeOpts,
  ): GoldenStrategyResult {
    const nonNull: Array<{ idx: number; s: string }> = [];
    for (let i = 0; i < values.length; i++) {
      const v = values[i];
      if (v === null || v === undefined) continue;
      nonNull.push({ idx: i, s: pyStr(v) });
    }
    if (nonNull.length === 0) return [null, 0.0] as const;
    const normalized: Array<{ idx: number; n: string }> = [];
    for (const x of nonNull) {
      const n = x.s.replace(WHITESPACE_RE, " ").trim();
      if (n) normalized.push({ idx: x.idx, n });
    }
    if (normalized.length === 0) return [null, 0.0] as const;
    const { key: winner, count } = mostCommon(normalized.map((x) => x.n));
    const firstIdx = normalized.find((x) => x.n === winner)!.idx;
    return [winner, count / nonNull.length, firstIdx] as const;
  }
}

export class BooleanNormalizeStrategy implements GoldenStrategyPlugin {
  readonly name = "boolean_normalize";

  merge(
    values: ReadonlyArray<unknown>,
    _opts?: GoldenStrategyMergeOpts,
  ): GoldenStrategyResult {
    const parsed: Array<{ idx: number; b: boolean }> = [];
    for (let i = 0; i < values.length; i++) {
      const v = values[i];
      if (v === null || v === undefined) continue;
      if (typeof v === "boolean") {
        parsed.push({ idx: i, b: v });
        continue;
      }
      const token = String(v).trim().toLowerCase();
      if (BOOL_TRUTHY.has(token)) {
        parsed.push({ idx: i, b: true });
      } else if (BOOL_FALSY.has(token)) {
        parsed.push({ idx: i, b: false });
      }
    }
    if (parsed.length === 0) return [null, 0.0] as const;
    let truthy = 0;
    for (const p of parsed) if (p.b) truthy++;
    const falsy = parsed.length - truthy;
    // Python tie-breaks to True.
    const winner = truthy >= falsy;
    const winCount = winner ? truthy : falsy;
    const firstIdx = parsed.find((p) => p.b === winner)!.idx;
    return [winner, winCount / parsed.length, firstIdx] as const;
  }
}

export const FORMAT_BUILTINS: readonly GoldenStrategyPlugin[] = [
  new ShortestValueStrategy(),
  new ConcatUniqueStrategy(),
  new EmailNormalizeStrategy(),
  new PhoneDigitsOnlyStrategy(),
  new UrlCanonicalStrategy(),
  new WhitespaceNormalizeStrategy(),
  new BooleanNormalizeStrategy(),
] as const;
