/**
 * Numeric-aggregate golden strategies (Phase 5 Part 1 of N -- closes
 * the first 6 of 22 plugins from goldenmatch issue #208).
 *
 * Parity contract: byte-identical output with Python's
 * `goldenmatch.plugins.builtin.numeric` for fixed inputs. Fixtures
 * generated by `scripts/generate_numeric_parity_fixtures.py` live at
 * `packages/typescript/goldenmatch/tests/parity/fixtures/numeric_*.json`.
 *
 * All 6 strategies share the same null-handling: non-numeric values
 * and `null` / `undefined` are dropped before the operation; all-null
 * input -> `[null, 0.0]`.
 *
 * Spec: docs/superpowers/specs/2026-05-22-phase-5-typescript-port-design.md
 */

import type {
  GoldenStrategyMergeOpts,
  GoldenStrategyPlugin,
  GoldenStrategyResult,
} from "../base.js";

function toFloat(value: unknown): number | null {
  if (value === null || value === undefined) return null;
  // Python's `_to_float` falls through to `float(value)` for non-bool
  // non-int non-float types -- which Python ACCEPTS for booleans
  // (True -> 1.0, False -> 0.0). The isinstance guard only blocks
  // the FAST path; the `float()` fallback succeeds. Mirror that.
  if (typeof value === "boolean") return value ? 1.0 : 0.0;
  if (typeof value === "number") {
    return Number.isFinite(value) ? value : null;
  }
  if (typeof value === "string") {
    const trimmed = value.trim();
    if (trimmed === "") return null;
    const n = Number(trimmed);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

/** Helper: collect (idx, parsedFloat, originalValue) for non-null
 *  numeric entries, preserving source positions. */
function collectNumeric(values: ReadonlyArray<unknown>): Array<{ idx: number; f: number; raw: unknown }> {
  const out: Array<{ idx: number; f: number; raw: unknown }> = [];
  for (let i = 0; i < values.length; i++) {
    const f = toFloat(values[i]);
    if (f === null) continue;
    out.push({ idx: i, f, raw: values[i] });
  }
  return out;
}

export class NumericMaxStrategy implements GoldenStrategyPlugin {
  readonly name = "numeric_max";

  merge(values: ReadonlyArray<unknown>, _opts?: GoldenStrategyMergeOpts): GoldenStrategyResult {
    const nums = collectNumeric(values);
    if (nums.length === 0) return [null, 0.0] as const;
    let maxF = nums[0]!.f;
    for (let i = 1; i < nums.length; i++) {
      if (nums[i]!.f > maxF) maxF = nums[i]!.f;
    }
    const tied = nums.filter((x) => x.f === maxF);
    const conf = tied.length === 1 ? 1.0 : 0.7;
    return [tied[0]!.raw, conf, tied[0]!.idx] as const;
  }
}

export class NumericMinStrategy implements GoldenStrategyPlugin {
  readonly name = "numeric_min";

  merge(values: ReadonlyArray<unknown>, _opts?: GoldenStrategyMergeOpts): GoldenStrategyResult {
    const nums = collectNumeric(values);
    if (nums.length === 0) return [null, 0.0] as const;
    let minF = nums[0]!.f;
    for (let i = 1; i < nums.length; i++) {
      if (nums[i]!.f < minF) minF = nums[i]!.f;
    }
    const tied = nums.filter((x) => x.f === minF);
    const conf = tied.length === 1 ? 1.0 : 0.7;
    return [tied[0]!.raw, conf, tied[0]!.idx] as const;
  }
}

export class NumericMeanStrategy implements GoldenStrategyPlugin {
  readonly name = "numeric_mean";

  merge(values: ReadonlyArray<unknown>, _opts?: GoldenStrategyMergeOpts): GoldenStrategyResult {
    const nums = collectNumeric(values);
    if (nums.length === 0) return [null, 0.0] as const;
    let sum = 0;
    for (const n of nums) sum += n.f;
    const mean = sum / nums.length;
    const conf = nums.length / values.length;
    return [mean, conf, 0] as const;
  }
}

export class NumericMedianStrategy implements GoldenStrategyPlugin {
  readonly name = "numeric_median";

  merge(values: ReadonlyArray<unknown>, _opts?: GoldenStrategyMergeOpts): GoldenStrategyResult {
    const nums = collectNumeric(values);
    if (nums.length === 0) return [null, 0.0] as const;
    const sorted = [...nums].sort((a, b) => a.f - b.f);
    // Mirror Python's "lower middle" choice: (n - 1) // 2.
    const midIdx = Math.floor((sorted.length - 1) / 2);
    const winner = sorted[midIdx]!;
    const conf = nums.length / values.length;
    return [winner.raw, conf, winner.idx] as const;
  }
}

export class NumericSumStrategy implements GoldenStrategyPlugin {
  readonly name = "numeric_sum";

  merge(values: ReadonlyArray<unknown>, _opts?: GoldenStrategyMergeOpts): GoldenStrategyResult {
    const nums = collectNumeric(values);
    if (nums.length === 0) return [null, 0.0] as const;
    let total = 0;
    for (const n of nums) total += n.f;
    return [total, 1.0, 0] as const;
  }
}

export class NumericWeightedAverageStrategy implements GoldenStrategyPlugin {
  readonly name = "numeric_weighted_average";

  merge(
    values: ReadonlyArray<unknown>,
    opts: GoldenStrategyMergeOpts = {},
  ): GoldenStrategyResult {
    const weights = opts.qualityWeights;
    const pairs: Array<readonly [number, number]> = [];
    for (let i = 0; i < values.length; i++) {
      const f = toFloat(values[i]);
      if (f === null) continue;
      const w = weights && i < weights.length ? Number(weights[i]) : 1.0;
      if (!(w > 0)) continue;
      pairs.push([f, w]);
    }
    if (pairs.length === 0) return [null, 0.0] as const;
    let weightedSum = 0;
    let totalWeight = 0;
    for (const [f, w] of pairs) {
      weightedSum += f * w;
      totalWeight += w;
    }
    const avg = weightedSum / totalWeight;
    // Confidence: sum(non-null weights) / sum(all weights) when weights
    // provided; otherwise non_null_count / total_count.
    let conf: number;
    if (weights) {
      let totalAllWeights = 0;
      for (let i = 0; i < weights.length; i++) {
        totalAllWeights += Math.max(0, Number(weights[i]));
      }
      conf = totalAllWeights > 0 ? totalWeight / totalAllWeights : pairs.length / values.length;
    } else {
      conf = pairs.length / values.length;
    }
    return [avg, conf, 0] as const;
  }
}

/** The 6 numeric builtin instances, ordered to match Python's
 *  `BUILTIN_PLUGINS` numeric slice. */
export const NUMERIC_BUILTINS: readonly GoldenStrategyPlugin[] = [
  new NumericMaxStrategy(),
  new NumericMinStrategy(),
  new NumericMeanStrategy(),
  new NumericMedianStrategy(),
  new NumericSumStrategy(),
  new NumericWeightedAverageStrategy(),
] as const;
