"""Cross-language END-TO-END split-run conformance.

The cluster-handoff harness proved: identical scored pairs -> identical clusters.
This goes further -- a REAL pipeline run. It answers two things:

  (a) HANDOFF FIDELITY: if Python runs standardize->block->score and hands its
      REAL scored pairs to TS `buildClusters`, does TS reproduce Python's own
      final clusters? (i.e. is "score in Python, cluster in TS" == all-Python?)

  (b) INDEPENDENT AGREEMENT: do a full all-Python run and a full all-TS run
      reach the same clusters on the same data + config? (This is where scoring
      tolerance / standardization can bite.)

To keep blocking out of the picture (so any divergence is scoring/standardize,
not a different candidate set), every row shares one blocking key -> the full
pair set is scored in both languages.

Emits: rows, an explicit config (no auto-config nondeterminism), Python's real
scored pairs, and Python's cluster partition. The TS test
(`tests/parity/split-run.parity.test.ts`) does (a) + (b).

Run: python packages/python/goldenmatch/scripts/emit_split_run_fixture.py
"""
from __future__ import annotations

import json
from pathlib import Path

import polars as pl

from goldenmatch.config.schemas import GoldenMatchConfig
from goldenmatch.tui.engine import MatchEngine

# Small person dataset with a mix: clear dupes, clear non-matches, and a couple
# of near-threshold pairs (where a 4th-decimal score delta could flip the match).
# Every row shares blk="x" so blocking never prunes -> full candidate set.
ROWS = [
    {"name": "Jonathan Smith", "blk": "x"},   # 0
    {"name": "Jonathan Smith", "blk": "x"},   # 1  exact dup of 0
    {"name": "Jon Smith", "blk": "x"},        # 2  near 0/1
    {"name": "Johnathan Smyth", "blk": "x"},  # 3  near-threshold vs 0/1/2
    {"name": "Robert Jones", "blk": "x"},     # 4  distinct
    {"name": "Bob Jones", "blk": "x"},        # 5  near 4 (nickname)
    {"name": "Katherine Ng", "blk": "x"},     # 6  distinct singleton
]

THRESHOLD = 0.85

CONFIG_DICT = {
    "blocking": {
        "strategy": "static",
        "keys": [{"fields": ["blk"], "transforms": []}],
    },
    "matchkeys": [
        {
            "name": "name_mk",
            "type": "weighted",
            "threshold": THRESHOLD,
            "fields": [
                {"field": "name", "scorer": "jaro_winkler", "weight": 1.0, "transforms": []}
            ],
        }
    ],
}


def _partition(clusters: dict[int, dict]) -> list[list[int]]:
    groups = [sorted(int(m) for m in c["members"]) for c in clusters.values()]
    groups.sort()
    return groups


def main() -> None:
    df = pl.DataFrame(ROWS)
    df = df.with_row_index("__row_id__").with_columns(
        pl.col("__row_id__").cast(pl.Int64),
        pl.lit("base").alias("__source__"),
    )
    config = GoldenMatchConfig.model_validate(CONFIG_DICT)

    engine = MatchEngine.from_dataframe(df)
    result = engine.run_full(config)

    # Scored pairs as [a, b, score] with a < b (canonical), sorted.
    pairs = sorted(
        [[min(int(a), int(b)), max(int(a), int(b)), round(float(s), 6)]
         for a, b, s in result.scored_pairs]
    )

    fixture = {
        "_note": (
            "Cross-language END-TO-END split-run conformance. Generated by "
            "scripts/emit_split_run_fixture.py. `py_scored_pairs` are Python's "
            "REAL pipeline scored pairs; `py_partition` its final clusters. The "
            "TS test asserts (a) TS buildClusters(py_scored_pairs) == py_partition "
            "[handoff fidelity], and measures (b) all-TS vs all-Python agreement."
        ),
        "rows": ROWS,
        "threshold": THRESHOLD,
        "config": CONFIG_DICT,
        "all_ids": list(range(len(ROWS))),
        "py_scored_pairs": pairs,
        "py_partition": _partition(result.clusters),
    }

    out = (
        Path(__file__).resolve().parents[3]
        / "typescript" / "goldenmatch" / "tests" / "parity" / "fixtures"
        / "conformance" / "split-run.json"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    print(f"  py scored pairs: {len(pairs)}  |  py partition: {_partition(result.clusters)}")


if __name__ == "__main__":
    main()
