"""Cross-language phase-handoff conformance: the CLUSTERING boundary.

The parity effort gives SURFACE parity (same ops in both languages). This
harness measures ARTIFACT interoperability at one pipeline boundary: given an
IDENTICAL set of scored pairs, do Python `build_clusters` and TS `buildClusters`
produce the IDENTICAL partition of records into clusters? If yes, the
score->cluster handoff is byte-safe (a user can score in one language and
cluster in the other and get the same answer).

Both entry points take the same inputs with the same defaults
(max_cluster_size=100, weak_cluster_threshold=0.3, auto_split=True), so this
isolates the clustering LOGIC from scoring tolerance.

Emits the scenarios + Python's clustering partition; the TS test
(`tests/parity/cluster-conformance.parity.test.ts`) reruns each through
`buildClusters` and asserts the same partition. Scenarios are chosen to probe
where divergence is plausible -- especially the oversized-cluster MST split.

Run: python packages/python/goldenmatch/scripts/emit_cluster_conformance_fixture.py
"""
from __future__ import annotations

import json
from pathlib import Path

from goldenmatch.core.cluster import build_clusters


def _partition(clusters: dict[int, dict]) -> list[list[int]]:
    """Normalize a clustering to a canonical partition: sorted list of sorted
    member groups (cluster-id labels are irrelevant to the handoff)."""
    groups = [sorted(int(m) for m in c["members"]) for c in clusters.values()]
    groups.sort()
    return groups


def _scenarios() -> list[dict]:
    scen: list[dict] = []

    # 1. Simple chain -> one cluster.
    scen.append({
        "name": "chain",
        "pairs": [[0, 1, 0.9], [1, 2, 0.9], [2, 3, 0.9]],
        "all_ids": [0, 1, 2, 3],
    })

    # 2. Two disjoint cliques + a singleton.
    scen.append({
        "name": "two_cliques_plus_singleton",
        "pairs": [[0, 1, 0.9], [0, 2, 0.88], [1, 2, 0.91], [3, 4, 0.95]],
        "all_ids": [0, 1, 2, 3, 4, 5],  # 5 is a singleton
    })

    # 3. A weak edge (below weak_cluster_threshold=0.3): membership must be
    #    unchanged (weak only downgrades cluster QUALITY, not the partition).
    scen.append({
        "name": "weak_edge_keeps_membership",
        "pairs": [[0, 1, 0.9], [1, 2, 0.25]],
        "all_ids": [0, 1, 2],
    })

    # 4. Oversized cluster (> max_cluster_size=100) with ONE clearly-weakest
    #    edge -> auto_split via MST should cut at the same unambiguous point in
    #    both languages. A 150-node chain, all edges strong except one weak link.
    n = 150
    weak_at = 75
    pairs = []
    for i in range(n - 1):
        w = 0.40 if i == weak_at else 0.90
        pairs.append([i, i + 1, w])
    scen.append({
        "name": "oversized_chain_unambiguous_split",
        "pairs": pairs,
        "all_ids": list(range(n)),
    })

    # 5. Oversized cluster with TIED weakest edges -> probes tie-breaking in the
    #    MST split. This is the most likely place for a legitimate divergence;
    #    the harness reports whichever way it lands.
    pairs2 = []
    for i in range(n - 1):
        w = 0.40 if i in (40, 90) else 0.90  # two equally-weak links
        pairs2.append([i, i + 1, w])
    scen.append({
        "name": "oversized_chain_tied_split",
        "pairs": pairs2,
        "all_ids": list(range(n)),
    })

    return scen


def main() -> None:
    out_scen = []
    for s in _scenarios():
        pairs = [(int(a), int(b), float(w)) for a, b, w in s["pairs"]]
        clusters = build_clusters(pairs, all_ids=list(s["all_ids"]))
        out_scen.append({
            "name": s["name"],
            "pairs": s["pairs"],
            "all_ids": s["all_ids"],
            # defaults both sides share -- pinned here so the TS side matches.
            "options": {
                "maxClusterSize": 100,
                "weakClusterThreshold": 0.3,
                "autoSplit": True,
            },
            "py_partition": _partition(clusters),
        })

    fixture = {
        "_note": (
            "Cross-language CLUSTERING conformance. Generated by "
            "scripts/emit_cluster_conformance_fixture.py. `py_partition` is the "
            "canonical partition (sorted member groups) from Python "
            "build_clusters; the TS test asserts buildClusters yields the same "
            "partition on the same scored pairs + options."
        ),
        "scenarios": out_scen,
    }

    out = (
        Path(__file__).resolve().parents[3]
        / "typescript" / "goldenmatch" / "tests" / "parity" / "fixtures"
        / "conformance" / "cluster-handoff.json"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(out_scen)} scenarios)")


if __name__ == "__main__":
    main()
