"""Emit the cross-language audit-hash parity fixture.

Constructs a battery of `IdentityEvent`s spanning every divergence risk between
Python `json.dumps(..., sort_keys=True, separators=(",",":"))` and a naive
TS `JSON.stringify` (non-ASCII payloads, `trust=1.0` float, micros==0 vs >0,
claim-authority fields set/unset), records each event's Python
`event_content_hash` hex, plus a multi-event seal + a verify pass/tamper case.

The TS test (`tests/parity/audit-hash.parity.test.ts`) asserts its own
`eventContentHash` reproduces every committed hex and its `sealAuditLog`
reproduces the committed `root_hash` -- proving the two toolkits cross-verify.

Determinism clamp: pinned `recorded_at` (no `datetime.now()`), pinned ids.
Run: python packages/python/goldenmatch/scripts/emit_audit_hash_fixture.py
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from goldenmatch.identity.audit import _fold_step, event_content_hash
from goldenmatch.identity.model import IdentityEvent


def _dt(y, mo, d, h, mi, s, us=0) -> datetime:
    return datetime(y, mo, d, h, mi, s, us)


# Each entry: a kwargs dict for IdentityEvent covering one or more divergences.
CASES: list[dict] = [
    # provenance-free (actor/trust None; no claim fields) + micros==0
    dict(entity_id="e1", kind="created", payload={"reason": "new"},
         run_name="run-a", dataset=None, recorded_at=_dt(2026, 7, 23, 12, 0, 0)),
    # trust = 1.0 (the float-repr landmine) + actor + micros>0
    dict(entity_id="e2", kind="manual_merge", payload={"records": [1, 2]},
         run_name="run-a", dataset="ds1", actor="steward:jo", trust=1.0,
         recorded_at=_dt(2026, 7, 23, 12, 0, 0, 123456)),
    # trust = 0.5, non-ASCII payload values + nested object (recursive key sort)
    dict(entity_id="e3", kind="claimed", payload={"z": "café", "a": {"y": "naïve", "x": "日本語"}},
         run_name="run-b", dataset="ds1", actor="agent", trust=0.5,
         recorded_at=_dt(2026, 7, 23, 12, 0, 1)),
    # trust = 0.0 + claim-authority fields all set (conditional keys present)
    dict(entity_id="e4", kind="claimed", payload=None, run_name="run-b",
         dataset="ds1", actor="agent", trust=0.0, claim_type="asserted",
         evidence_ref="doc:42", previous_claim_id=7,
         recorded_at=_dt(2026, 7, 23, 12, 0, 2, 900000)),
    # trust = 0.123456 (6dp) + partial claim fields (only claim_type set)
    dict(entity_id="e5", kind="absorbed_record", payload={"n": 3},
         run_name="run-c", dataset=None, actor="pipeline", trust=0.123456,
         claim_type="inferred", recorded_at=_dt(2026, 7, 23, 12, 0, 3)),
    # trust = 0.999999 + evidence_ref only
    dict(entity_id="e6", kind="merged_with", payload={"s": "a\"b\\c\n"},
         run_name="run-c", dataset=None, actor="agent", trust=0.999999,
         evidence_ref="url:https://x/y", recorded_at=_dt(2026, 7, 23, 12, 0, 4, 1)),
]


def _serialize_event(kw: dict, event_id: int) -> dict:
    ev = IdentityEvent(event_id=event_id, **kw)
    # The TS side reconstructs the event from this dict; recorded_at goes over
    # as the pyIsoformat string (what the DB stores + what the hash uses).
    return {
        "event_id": event_id,
        "entity_id": ev.entity_id,
        "kind": str(ev.kind),
        "payload": ev.payload,
        "run_name": ev.run_name,
        "dataset": ev.dataset,
        "actor": ev.actor,
        "trust": ev.trust,
        "claim_type": str(ev.claim_type) if ev.claim_type is not None else None,
        "evidence_ref": str(ev.evidence_ref) if ev.evidence_ref is not None else None,
        "previous_claim_id": ev.previous_claim_id,
        "recorded_at": ev.recorded_at.isoformat(),
        "expected_hash": event_content_hash(ev),
    }


def main() -> None:
    events = [_serialize_event(kw, i + 1) for i, kw in enumerate(CASES)]

    # Seal fold over all events (seeded by "") -> the committed root_hash.
    acc = ""
    for e in events:
        acc = _fold_step(acc, e["expected_hash"])
    seal_root = acc

    fixture = {
        "_note": (
            "Cross-language audit-hash parity oracle. Generated by "
            "scripts/emit_audit_hash_fixture.py. Each event's expected_hash is "
            "Python event_content_hash; seal.root_hash is the _fold_step chain."
        ),
        "events": events,
        "seal": {"root_hash": seal_root, "event_count": len(events),
                 "last_event_id": events[-1]["event_id"]},
    }

    out = (
        Path(__file__).resolve().parents[3]
        / "typescript" / "goldenmatch" / "tests" / "parity" / "fixtures"
        / "identity" / "audit-hash.json"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(fixture, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(events)} events, seal_root={seal_root[:12]}...)")


if __name__ == "__main__":
    main()
