#!/usr/bin/env python3
"""Generate the CANONICAL committed DCT basis for the perceptual image hash, in
BOTH Rust and Python, from ONE source.

Why: the pHash DCT basis has input-INDEPENDENT arguments, but the kernels
computed `cos` at runtime with whatever libm the target links. Native
(glibc/MSVC), wasm, and CPython differ in the last places, which flips bits on
borderline images (the median threshold is sensitive). That made the perceptual
hash non-deterministic across PLATFORMS and SURFACES (the committed golden test
passes on Linux CI but failed on Windows).

Fix: precompute the DCT basis ONCE and commit it as a constant that the Rust
kernel (native + wasm) AND the Python reference both read. The image hash is then
bit-identical everywhere -- the "one kernel, identical across surfaces" thesis
holds across platforms too.

Bit-exact across languages (Rust `f64::from_bits`, Python `float.fromhex`). Run
once and COMMIT the outputs; treat them as frozen constants (regenerating
re-bases the image fixture). Scope: image pHash only -- the radial profile and
the audio per-sample-rate DFT are NOT tabled (radial stays a Python/native
feature; audio's DFT argument depends on the runtime sample rate).

Usage:
    python scripts/gen_perceptual_tables.py
Writes:
    packages/rust/extensions/perceptual-core/src/tables.rs
    packages/python/goldenmatch/goldenmatch/core/_perceptual_tables.py
"""
from __future__ import annotations

import math
import struct
from pathlib import Path

IMG_RESIZE = 32
HASH_SIZE = 8

REPO = Path(__file__).resolve().parents[4]
RUST_OUT = REPO / "packages/rust/extensions/perceptual-core/src/tables.rs"
PY_OUT = REPO / "packages/python/goldenmatch/goldenmatch/core/_perceptual_tables.py"


def _bits(x: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", x))[0]


# The 8x32 unnormalized DCT-II basis `cos(pi*(i+0.5)*k/32)` -- the only slice
# `dct2_topleft` reads. Exact expression mirrors the kernel + the Python reference.
DCT_BASIS = [
    [math.cos(math.pi * (i + 0.5) * k / IMG_RESIZE) for i in range(IMG_RESIZE)]
    for k in range(HASH_SIZE)
]


def _rust() -> str:
    L = [
        "//! AUTO-GENERATED by scripts/gen_perceptual_tables.py -- DO NOT EDIT.",
        "//! Canonical committed DCT-II basis for the perceptual image hash, frozen as",
        "//! a constant so native / wasm / Python are bit-identical (no runtime libm).",
        "//! Python sibling: goldenmatch/core/_perceptual_tables.py (same f64s).",
        "",
        "#[rustfmt::skip]",
        "pub(crate) const DCT_BASIS: [[f64; 32]; 8] = [",
    ]
    for row in DCT_BASIS:
        cells = ", ".join(f"f64::from_bits(0x{_bits(v):016x})" for v in row)
        L.append(f"    [{cells}],")
    L.append("];")
    L.append("")
    return "\n".join(L)


def _py() -> str:
    L = [
        '"""AUTO-GENERATED by scripts/gen_perceptual_tables.py -- DO NOT EDIT.',
        "",
        "Canonical committed DCT-II basis for the perceptual image hash, shared",
        "bit-for-bit with the Rust sibling (perceptual-core/src/tables.rs) so the",
        "image hash is identical across CPython / native / wasm.",
        '"""',
        "from __future__ import annotations",
        "",
        "DCT_BASIS: list[list[float]] = [",
    ]
    for row in DCT_BASIS:
        cells = ", ".join(f'float.fromhex("{v.hex()}")' for v in row)
        L.append(f"    [{cells}],")
    L.append("]")
    L.append("")
    return "\n".join(L)


def main() -> None:
    RUST_OUT.write_text(_rust(), encoding="utf-8")
    PY_OUT.write_text(_py(), encoding="utf-8")
    print(f"wrote {RUST_OUT}")
    print(f"wrote {PY_OUT}")


if __name__ == "__main__":
    main()
