"""Generate the perceptual-core golden-vector fixture from the Python reference.

The reference (``goldenmatch.core.perceptual``) is authoritative (ADR 0022); the
Rust ``goldenmatch-perceptual-core`` crate reproduces these vectors byte-for-byte.
Run from the package root::

    python scripts/gen_perceptual_golden.py

Writes ``tests/fixtures/perceptual_golden.json``. The fixture stores the *raw
decoded inputs* (integer luma grids; int16 PCM) so every language's parity test
consumes identical inputs — re-deriving synthetic inputs per language would risk
ULP-tie bit flips. Audio samples are int16; the kernel input is ``pcm / 32768.0``.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

from goldenmatch.core import perceptual

FIXTURE = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "perceptual_golden.json"

PCM_SCALE = 32768.0


# --- deterministic synthetic inputs (stdlib only) ----------------------------
def _gradient(h: int, w: int) -> list[list[int]]:
    return [[(x + y) % 256 for x in range(w)] for y in range(h)]


def _checker(h: int, w: int, cell: int) -> list[list[int]]:
    return [[255 if ((x // cell + y // cell) % 2 == 0) else 0 for x in range(w)] for y in range(h)]


def _gratings(h: int, w: int) -> list[list[int]]:
    """Frequency-rich pattern (stable mid-band coefficients) -> robust hash."""
    out = []
    for y in range(h):
        row = []
        for x in range(w):
            v = (
                128
                + 40 * math.sin(x / 2.0)
                + 35 * math.sin(y / 3.0)
                + 30 * math.sin((x + y) / 2.5)
                + 25 * math.sin((x - y) / 4.0)
            )
            row.append(max(0, min(255, int(round(v)))))
        out.append(row)
    return out


def _sines_pcm16(length: int, sample_rate: int, freqs: list[float]) -> list[int]:
    out = []
    for n in range(length):
        t = n / sample_rate
        v = 0.0
        for i, f in enumerate(freqs):
            v += math.sin(2.0 * math.pi * f * t) / (i + 1)
        out.append(max(-32768, min(32767, int(round(v / len(freqs) * 30000)))))
    return out


def _pcm_to_float(pcm: list[int]) -> list[float]:
    return [s / PCM_SCALE for s in pcm]


def build() -> dict:
    images = {
        "gradient_16x16": _gradient(16, 16),
        "checker_24x24_c3": _checker(24, 24, 3),
        "gratings_40x28": _gratings(40, 28),  # non-square, frequency-rich
    }
    image_vectors = [
        {
            "name": name,
            "rows": len(g),
            "cols": len(g[0]),
            "pixels": g,
            "phash": hex(perceptual.phash_image(g)),
        }
        for name, g in images.items()
    ]

    sr = 44100
    audios = {
        "chord_a": _sines_pcm16(6144, sr, [440.0, 660.0, 880.0]),
        "sweep_b": _sines_pcm16(8192, sr, [320.0, 700.0, 1500.0]),
    }
    audio_vectors = [
        {
            "name": name,
            "sample_rate": sr,
            "pcm16": pcm,
            "fingerprint": [hex(w) for w in perceptual.fingerprint_audio(_pcm_to_float(pcm), sr)],
        }
        for name, pcm in audios.items()
    ]

    return {
        "_comment": "Generated by scripts/gen_perceptual_golden.py from "
        "goldenmatch.core.perceptual (ADR 0022). Do not hand-edit. Audio kernel "
        "input is pcm16 / 32768.0.",
        "pcm_scale": PCM_SCALE,
        "image_params": {"resize": perceptual.IMG_RESIZE, "hash_size": perceptual.HASH_SIZE},
        "audio_params": {
            "frame": perceptual.AUDIO_FRAME,
            "hop": perceptual.AUDIO_HOP,
            "bands": perceptual.AUDIO_BANDS,
            "f_min": perceptual.AUDIO_F_MIN,
            "f_max": perceptual.AUDIO_F_MAX,
        },
        "images": image_vectors,
        "audio": audio_vectors,
    }


def main() -> None:
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(build(), indent=2) + "\n")
    print(f"wrote {FIXTURE}")


if __name__ == "__main__":
    main()
