/**
 * Cross-surface byte-parity: the SAME oracle corpus
 * (`packages/python/goldenflow/tests/parity/identifiers_corpus.jsonl`,
 * generated by `packages/python/goldenflow/scripts/gen_identifiers_corpus.py`
 * from the goldenflow-core kernels) is asserted byte-identical against BOTH
 * the pure-TS identifier transforms (always) and the opt-in WASM backend
 * (only when the `.wasm` artifact has actually been built -- it is a CI-only
 * build product, never committed; see `src/core/wasm/artifacts/.gitignore`).
 *
 * This file is copied byte-for-byte from the Python corpus (NOT hand-edited
 * -- CI's sync-check enforces the two stay identical). Each row is
 * `{ transform, input, expected }`:
 *   - `input`: `string | null` (`null` mirrors Python `None`)
 *   - `expected`: `boolean | string | null` (`"true"`/`"false"` never appear
 *     -- the Python oracle serializes real JSON booleans; `null` covers both
 *     Python `None` and the Rust `Option::None` -> `null` format/normalize
 *     results)
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import {
  ccValidateTs,
  ccFormatTs,
  ccMaskTs,
  ibanValidateTs,
  ibanFormatTs,
  isbnValidateTs,
  isbnNormalizeTs,
  eanValidateTs,
  vatValidateTs,
  vatFormatTs,
  swiftValidateTs,
  swiftFormatTs,
  abaValidateTs,
  imeiValidateTs,
} from "../../src/core/transforms/identifiers.js";
import { nameTransliterateTs, nameScriptTs } from "../../src/core/transforms/names.js";
import {
  emailLowercaseTs,
  emailNormalizeTs,
  emailExtractDomainTs,
  emailValidateTs,
} from "../../src/core/transforms/email.js";
import { urlNormalizeTs, urlExtractDomainTs } from "../../src/core/transforms/url.js";
import {
  currencyStripTs,
  percentageNormalizeTs,
  toIntegerTs,
  commaDecimalTs,
  scientificToDecimalTs,
} from "../../src/core/transforms/numeric.js";
import {
  categoryNormalizeKeyTs,
  booleanNormalizeTs,
  genderStandardizeTs,
  nullStandardizeTs,
} from "../../src/core/transforms/categorical.js";
import { enableWasm, disableWasm } from "../../src/core/wasm/index.js";
import { getFlowWasmBackend, type FlowWasmBackend } from "../../src/core/wasm/backend.js";

interface CorpusRow {
  transform: string;
  input: string | null;
  expected: boolean | string | number | null;
}

const here = dirname(fileURLToPath(import.meta.url));
const corpusPath = resolve(here, "identifiers_corpus.jsonl");
const rows: CorpusRow[] = readFileSync(corpusPath, "utf8")
  .split("\n")
  .filter((line) => line.trim().length > 0)
  .map((line) => JSON.parse(line) as CorpusRow);

/** Pure-TS single-value functions, keyed by the corpus's `transform` name.
 * Each takes the raw `string` input (null rows are short-circuited before
 * calling into these -- the fns below don't accept null). */
const PURE_TS_FN: Record<string, (s: string) => boolean | string | number | undefined> = {
  cc_validate: ccValidateTs,
  cc_format: ccFormatTs,
  cc_mask: ccMaskTs,
  iban_validate: ibanValidateTs,
  iban_format: ibanFormatTs,
  isbn_validate: isbnValidateTs,
  isbn_normalize: isbnNormalizeTs,
  ean_validate: eanValidateTs,
  vat_validate: vatValidateTs,
  vat_format: vatFormatTs,
  swift_validate: swiftValidateTs,
  swift_format: swiftFormatTs,
  aba_validate: abaValidateTs,
  imei_validate: imeiValidateTs,
  name_transliterate: nameTransliterateTs,
  name_script: nameScriptTs,
  email_lowercase: emailLowercaseTs,
  email_normalize: emailNormalizeTs,
  email_extract_domain: emailExtractDomainTs,
  email_validate: emailValidateTs,
  url_normalize: urlNormalizeTs,
  url_extract_domain: urlExtractDomainTs,
  boolean_normalize: booleanNormalizeTs,
  gender_standardize: genderStandardizeTs,
  null_standardize: nullStandardizeTs,
  category_normalize_key: categoryNormalizeKeyTs,
  currency_strip: currencyStripTs,
  percentage_normalize: percentageNormalizeTs,
  to_integer: toIntegerTs,
  comma_decimal: commaDecimalTs,
  scientific_to_decimal: scientificToDecimalTs,
};

/** Same transform set, dispatched through the wasm backend's method of the
 * same name (the `FlowWasmBackend` interface intentionally mirrors these
 * names -- see `src/core/wasm/backend.ts`). */
function wasmFn(backend: FlowWasmBackend, transform: string): (s: string) => boolean | string | number | undefined {
  const map: Record<string, (s: string) => boolean | string | number | undefined> = {
    cc_validate: (s) => backend.ccValidate(s),
    cc_format: (s) => backend.ccFormat(s),
    cc_mask: (s) => backend.ccMask(s),
    iban_validate: (s) => backend.ibanValidate(s),
    iban_format: (s) => backend.ibanFormat(s),
    isbn_validate: (s) => backend.isbnValidate(s),
    isbn_normalize: (s) => backend.isbnNormalize(s),
    ean_validate: (s) => backend.eanValidate(s),
    vat_validate: (s) => backend.vatValidate(s),
    vat_format: (s) => backend.vatFormat(s),
    swift_validate: (s) => backend.swiftValidate(s),
    swift_format: (s) => backend.swiftFormat(s),
    aba_validate: (s) => backend.abaValidate(s),
    imei_validate: (s) => backend.imeiValidate(s),
    name_transliterate: (s) => backend.nameTransliterate(s),
    name_script: (s) => backend.nameScript(s),
    email_lowercase: (s) => backend.emailLowercase(s),
    email_normalize: (s) => backend.emailNormalize(s),
    email_extract_domain: (s) => backend.emailExtractDomain(s),
    email_validate: (s) => backend.emailValidate(s),
    url_normalize: (s) => backend.urlNormalize(s),
    url_extract_domain: (s) => backend.urlExtractDomain(s),
    boolean_normalize: (s) => backend.booleanNormalize(s),
    gender_standardize: (s) => backend.genderStandardize(s),
    null_standardize: (s) => backend.nullStandardize(s),
    category_normalize_key: (s) => backend.categoryNormalizeKey(s),
    currency_strip: (s) => backend.currencyStrip(s),
    percentage_normalize: (s) => backend.percentageNormalize(s),
    to_integer: (s) => backend.toInteger(s),
    comma_decimal: (s) => backend.commaDecimal(s),
    scientific_to_decimal: (s) => backend.scientificToDecimal(s),
  };
  const fn = map[transform];
  if (!fn) throw new Error(`no wasm dispatch for transform ${transform}`);
  return fn;
}

/** Normalize a raw fn result (`boolean | string | number | undefined`) and a
 * corpus `expected` (`boolean | string | number | null`) onto the same shape so
 * `undefined` (Rust `Option::None` / no-match) and `null` (Python `None`)
 * compare equal. Numeric transforms (currency/percentage/…) compare by VALUE:
 * `toEqual` does structural number equality, so identical IEEE-754 results from
 * the Rust kernel and the pure-TS parser match without string-repr coupling. */
function normalize(v: boolean | string | number | undefined | null): boolean | string | number | null {
  return v === undefined ? null : v;
}

describe("goldenflow identifiers: pure-TS matches oracle", () => {
  it("has corpus rows to assert", () => {
    expect(rows.length).toBeGreaterThan(0);
  });

  for (const row of rows) {
    it(`${row.transform}(${JSON.stringify(row.input)}) === ${JSON.stringify(row.expected)}`, () => {
      const fn = PURE_TS_FN[row.transform];
      if (!fn) throw new Error(`unknown transform in corpus: ${row.transform}`);
      const got = row.input === null ? undefined : fn(row.input);
      expect(normalize(got)).toEqual(normalize(row.expected));
    });
  }
});

describe("goldenflow identifiers: wasm matches oracle", () => {
  let wasmAvailable = false;

  beforeAll(async () => {
    // enableWasm() resolves false (no throw) when the `.wasm` artifact isn't
    // built -- true default/local state, since it's a CI-only build product
    // (never committed; src/core/wasm/artifacts/.gitignore). Only when it
    // resolves true do we have a real backend to assert against.
    wasmAvailable = await enableWasm();
  });

  afterAll(() => {
    disableWasm();
  });

  it("reports wasm availability", () => {
    if (!wasmAvailable) {
      console.warn(
        "goldenflow wasm artifact not built (src/core/wasm/artifacts/*.wasm absent) " +
          "-- skipping the wasm parity leg. This is expected outside the wasm_flow CI lane.",
      );
    }
    // Always passes -- this test's job is just to make the skip visible in
    // the run output, not to fail when the artifact is (expectedly) absent.
    expect(true).toBe(true);
  });

  for (const row of rows) {
    it.skipIf(!wasmAvailable)(
      `[wasm] ${row.transform}(${JSON.stringify(row.input)}) === ${JSON.stringify(row.expected)}`,
      () => {
        const backend = getFlowWasmBackend();
        if (!backend) throw new Error("wasmAvailable=true but getFlowWasmBackend() returned null");
        const fn = wasmFn(backend, row.transform);
        const got = row.input === null ? undefined : fn(row.input);
        expect(normalize(got)).toEqual(normalize(row.expected));
      },
    );
  }
});
